### ISSUE TITLE
Cropping Rectangle Becomes a Parallelogram

### ISSUE THREAD

**Issue by dxoxp** [nhn/tui.image-editor#101]
## Version

Toast Image Editor v3.2.2

## Development Environment
Windows 7
Chrome 71 (also reproduced on Firefox 63.0.3, and IE 11)

## Current Behavior

If you press and hold the Shift key while hovering over the crop zone rectangle's middle drag handles, the mouse cursor points the wrong way, and dragging that handle causes the crop zone rectangle to turn into a parallelogram.  This happens on the left, top, right, and bottom handles, not the corner handles.   

Steps:
1. On the sample page at http://ui.toast.com/tui-image-editor/, enable the "crop" feature and draw a crop zone rectangle on the image.
1. Ensure that the mouse button is no longer depressed.
1. Press and hold the "Shift" key while moving the mouse cursor to one of the middle drag handles on the crop zone rectangle.  (Notice that the mouse cursor points in the unexpected direction: up/down for the Left and Right drag handles, and left/right for the Top and Bottom drag handles.)
1. Click and drag the handle in the (unexpected) direction of the mouse cursor.  (Notice that the crop zone rectangle becomes a parallelogram.)

## Expected Behavior

When the Shift key is pressed, the drag handles of the crop zone rectangle should continue to drag in the expected directions.

**Comment by jinwoo-kim-nhn** [comment]
![71882270-79a5ce00-3177-11ea-93c8-9922d601be11](https://user-images.githubusercontent.com/35218826/73803270-962f3780-4803-11ea-8153-f7c11e26bf12.png)
