### ISSUE TITLE
TextArea is not resizing

### ISSUE THREAD

**Issue by qradle** [nhn/tui.image-editor#109]
## Version
3.3.0

## Development Environment
Chrome Firefox, ubuntu

## Current Behavior
You can found current behavior even in the examples. (so I use same api methods).
http://nhnent.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect.html

steps to reproduce:
1. add text object with addText method.
2. double click to enter editing mode
3. start typing
You can see that textarea width is not resizing while typing, and tail signs became hidden.

## Expected Behavior
Textarea width resizing by the content.
The proper behavior is expected just like in example with includeUI.
https://nhnent.github.io/tui.image-editor/latest/tutorial-example01-includeUi.html (example 1).

**Comment by calvinkei** [comment]
+1, the behavior of using API directly is different from includeUI

**Comment by sabinayakc** [comment]
I am having the same issue. Any updates on this or how we can update the API to use the same functionality as the UI? 

If you can point me to the code that updates the Text Area width I can maybe make a local code change for a temporary workaround.

**Comment by sabinayakc** [comment]
Found the problem. It has to do with IText settings when initializing the image editor. Currently, when you don't use UI, `useIText` is set to false. If you set that to true then the API version will use IText. I don't know the reason for setting that to false for API versions but setting that to true enables textArea resizing. Hope this helps @calvinkei  @qradle @jinwoo-kim-nhn 


### Line 178 - imageEditor.js 

https://github.com/nhn/tui.image-editor/blob/e22335d7e4fa6bc60d5b6b005d18344cdca42ace/src/js/imageEditor.js#L178

![image](https://user-images.githubusercontent.com/13154166/78060726-a8d07380-7351-11ea-81a2-7fe1ef32a905.png)

**Comment by jinwoo-kim-nhn** [comment]
I'm improving this. It's almost finished. Wait a minute.
