### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by lethnh** [nhn/tui.image-editor#113]
I have a problem about Tui image editor
That is my tui image editor follow the example can not
edit text, just add text "Double click"

![image](https://user-images.githubusercontent.com/22109557/50511651-088dfe00-0ac1-11e9-9cc1-70fad847b7cd.png)

**Comment by lethnh** [comment]
I hope you help me

**Comment by junghwan-park** [comment]
@lethnh 
I think you should _double click_ on text area for editing text. Adding text element when you just _click_ canvas.
