### ISSUE TITLE
Cropping Aspect Ratio Issue

### ISSUE THREAD

**Issue by rcohenprogrammer** [nhn/tui.image-editor#114]
## Version

v1.5.0/tui-code-snippet.min.js
v3.3.0/tui-image-editor.min.js

## Development Environment

MacOS 10.13.6
Chrome 71.0.3578.98 (Official Build) (64-bit)
Firefox 63.0 (64-bit)

## Current Behavior

When implementing certain aspect ratios to cropping an image, the cropping is not applied when an image has certain resolutions (in this particular case 408x312). 

My particular use case is that I implemented a button to snap the cropping selection box to a specified aspect ratio (I used 4:3 and 16:9), similar to the demo at "https://nhnent.github.io/tui.image-editor/latest/tutorial-example01-includeUi.html". I had to implement this because I am basing my use off of the mobile oriented example. 

Interestingly, when applying the '16:9' ratio on the '408x312' image the 'getCropzoneRect()' method is returning null. But, when I apply the '4:3' ratio or slightly alter the crop selection box width the 'getCropzoneRect()' returns a 'rect' object and successfully applies. I also noticed that this behavior is present on the  demo at the earlier mention link.

If this is already a known issue, or I am missing something obvious, I apologize and this can be disregarded.

```js
// Write example code
// Toggle the crop selection ratio //
toggle (imageEditor: any, input?: HTMLInputElement) {
        if (imageEditor.getDrawingMode() !== 'CROPPER') {
            imageEditor.startDrawingMode('CROPPER');
        }
        console.log(this.width / this.height);
        imageEditor.setCropzoneRect(this.width / this.height);
}
// Apply the cropping selection to the image //
set (imageEditor: any) {
        console.log(imageEditor.getCropzoneRect());
        if (!this.is_too_small(imageEditor.getCropzoneRect())) {
            imageEditor.crop(imageEditor.getCropzoneRect()).then( (result) => {
                imageEditor.stopDrawingMode();
                this.closeHiddenMenus();
            }).catch( e => {
                console.log(e);
            });
        }
}
```

## Expected Behavior

I expect the crop selection to, at least, snap to the best suitable aspect ration for the image. It would be nice if there was a built in event listener for changes to the crop selection box.

**Comment by dxoxp** [comment]
This same behavior happens with images of size 1000x1000, using the 16:9 preset.

In this case the cropzone rectangle's "left" value is calculated to be an incredibly small negative value (-5.684341886080802e-14) likely due to the imprecision of floating point calculations.  This causes the cropzone's "isValid" function to return false, thereby causing the getCropzoneRect function to return null.

**Comment by rcohenprogrammer** [comment]
In the _getPresetCropSizePosition method of v3.3.0/tui-image-editor.js file, if I change the lines
`return {
    top: (originalHeight - height) / 2,
    left: (originalWidth - width) / 2,
    width: width,
    height: height
};
`
to

`return {
    top: (originalHeight.toFixed(10) - height.toFixed(10)) / 2,
    left: (originalWidth.toFixed(10) - width.toFixed(10)) / 2,
    width: width,
    height: height
};
`

this seems to solve the issue in my particular case. I am uncertain if there are any unseen consequences to this by applying precision to the subtraction as "dxoxp" suggested.
