### ISSUE TITLE
Text not editable in fullscreen mode

### ISSUE THREAD

**Issue by maverick42** [nhn/tui.image-editor#117]
Hi,

awesome plugin :) !

In fullscreen mode (on image editor element ; https://github.com/private-face/jquery.fullscreen) 
`$('#tui-image-editor-container').fullscreen();`

=>the text is not editable ... ?? ! Only the escape key seems allowed. ...  

Any idea ?

Best Regards
Frédérik.

**Comment by maverick42** [comment]
Related issue from fabric.js

https://github.com/fabricjs/fabric.js/issues/5126

**Comment by philipstratford** [comment]
I'm having the same issue. My TUI Image Editor is inside a Bootstrap modal element. I can add text to an image but when I double-click on it, hitting keys on the keyboard has no effect. However, if I hit the ESCAPE key, I can see that the Boostrap modal closes behind the TUI Image Editor and then the text suddenly becomes editable.

**Comment by philipstratford** [comment]
For anyone else encountering this issue I've added a workaround to the comments of https://github.com/fabricjs/fabric.js/issues/5126. It's not pretty but it works.

**Comment by vsvanshi** [comment]
@philipstratford you have given a solution in the other thread, but can you please tell where to use it when using Image Editor.
I am trying to load the image editor inside a Dialog Component and there is same issue with the text field

**Comment by philipstratford** [comment]
@vsvanshi The workaround I've posted there references [another comment further up](https://github.com/fabricjs/fabric.js/issues/5126#issuecomment-571674322). Per that comment, add my code snippet to a separate Javascript file and include that file in your page after the standard TUI Javascript files. No guarantees it'll work!
