### ISSUE TITLE
Save Object data to allow editing after save

### ISSUE THREAD

**Issue by adoptavia** [nhn/tui.image-editor#126]
Hi,Is it possible to save object data so we can go back and edit the image after save

**Comment by junghwan-park** [comment]
@adoptavia 
What do you mean **object data**?
Is that TOAST UI Image-Editor's `Drawing`, `Text`, `Icon` and `Shape`?

**Comment by adoptavia** [comment]
> @adoptavia
> What do you mean **object data**?
> Is that TOAST UI Image-Editor's `Drawing`, `Text`, `Icon` and `Shape`?

Hi,
I mean what i would like to do is somehow save the canvas objects (is that the right word) as code? so for example if I add a text area and a triangle, save those objects properties (X Y etc) as a string. so effectively i could click save, and rather than save as an image, just save the object data and then when i repopened that file i could access the object data to repopulate the canvas and carry on editing

**Comment by junghwan-park** [comment]
@adoptavia 
Unfortunately, There is no API for save & restore canvas objects via canvas object's properties.
Yet, TOAST UI Image-Editor is built for simple image editing & drawing on the single image.
I think I'll add Image-Editor's event listener for what you want to do. I'll enhance Image-Editor event listeners for manipulating canvas objects.
ex) `changeObject` and `removeObject` event

Adding canvas objects is available by [add\[something\]()](https://nhnent.github.io/tui.image-editor/latest/ImageEditor.html#addShape) APIs.

**Comment by zhangran25** [comment]
Hello! I saw the question and the replies above about "save the canvas objects ". It seem that no answer or no solutions now? So anybody know how to save the middle status of the canvas objects like this? Im also really want to know it ...... Thank you so much.

**Comment by aaweb** [comment]
I'd also be interested in that. Even for simple edits like just adding a text it's super useful to be able to edit that later. It would be a killer feature!

**Comment by razorsharpshady** [comment]
First of all great job with the image editor guys. Congratulations for that. 

And yes I'm looking for save meta-data of the image editing too, to implement "save and edit later" functionality.

**Comment by cheeseinvert** [comment]
This would be very useful.

**Comment by yanivka** [comment]
I would like to reopen this issue ... it would be great to have a way to save the current image editor state (objects on the image) as json and load them afterword from a json object when editing the same image.

**Comment by Wasth** [comment]
Is there any way to do this? I mean, "save and edit later" functionality.

**Comment by MarcoBerubeBKOM** [comment]
Hi all, this is my chance to give back to the community!
Hi have managed to integrate a **save feature of the layers of type TEXT, SHAPE and ICON in Toast UI Editor**.
This in implemented within an Angular 10 component.

You'll need to adapt this code to your app context...

Here is a summary of my steps/logic:
 **--- SAVE STEPS --- :**
1. PREVIEW: Save full image preview with TUI.toDataURL(), ref: https://github.com/nhn/tui.image-editor/search?q=toDataURL
2. LAYOUT: Save layout object has JSON: TUI._graphics._canvas._objects: Keep only important properties by filtering them. ref: lodash _.pick()
3. BACKGROUND: Remove unwanted layers by setting to empty array Or filter layers TUI._graphics._canvas._objects = [], then save only the background image with TUI.toDataURL(), this image will be used on load

    
**--- LOAD STEPS --- :**

1.  LOAD BACKGROUND: load the saved background (from path or base64) with loadImage: { path: imgBase64, name: 'background' } ref: https://github.com/nhn/tui.image-editor/search?q=loadImage
2.  Add back layout object by filling TUI._graphics._canvas._objects with TUI.addText(), TUI.addShape(), TUI.addIcon() ref https://nhn.github.io/tui.image-editor/latest/ImageEditor#addText

[TUI-Editor-Save-example.txt](https://github.com/nhn/tui.image-editor/files/6704017/TUI-Editor-Save-example.txt)

`
import {Component, ElementRef, OnInit, ViewEncapsulation} from '@angular/core';
import * as _ from "lodash";
import {OverlayCustomRef} from "../../../../services/overlay-custom-ref";
import FileSaver from 'file-saver';
import ImageEditor from 'tui-image-editor';
import {ImgAssetStorage, ItemLayout} from 'src/app/interfaces/app-interface';

@Component({
  selector: 'app-deck-image-editor',
  templateUrl: './deck-image-editor.component.html',
  styleUrls: ['./deck-image-editor.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class DeckImageEditorComponent implements OnInit {

  /*  Toast UI Editor Ref:
    https://www.npmjs.com/package/tui-image-editor
    https://github.com/nhn/tui.editor
  */

  public TUI;
  public currentImage = null;
  public currentLayout = null;

  constructor(public ref: OverlayCustomRef) {
  }
  
  
  /* 
	/******************************
	 * Interface used for layout
	 *******************************/
	/*export interface IItemLayout {
	  objects: any;
	  background: IImgAssetStorage;
	}
	//Getter
	export class ItemLayout implements IItemLayout {
	  public objects: any = [];
	  public background: IImgAssetStorage = null;
	}
  */
  

  ngOnInit(): void {

    /* --- LOAD STEPS --- :
     * 1) LOAD BACKGROUND: load the saved background (from path or base64) with loadImage: { path: imgBase64, name: 'background' } ref: https://github.com/nhn/tui.image-editor/search?q=loadImage
     * 2) Add back layout object by filling TUI._graphics._canvas._objects with TUI.addText(), TUI.addShape(), TUI.addIcon() ref https://nhn.github.io/tui.image-editor/latest/ImageEditor#addText
     * */

    let divEditor = document.querySelector('#tui-image-editor');
    if(!divEditor){
      return;
    }

    let layout = null
    let itemImg = null;
    let imgBase64 = null;


    //Get layout and back image data
    layout = this.ref.data.layout;
    itemImg = this.ref.data.image;
     
  
    //If there is a background image saved in the layout
    if(layout && layout.background && layout.objects){
      this.currentImage = layout.background;
      this.currentLayout = layout;
      console.log("Init set current image from saved layout",  this.currentImage);
    } else {
      //Else take the preview image
      this.currentImage = itemImg;
    }


    //Get Base64 of the image
    imgBase64 = this.gameDataService.getAssetFromCatalog(this.currentImage);

    //Toast UI config
    this.TUI = new ImageEditor(divEditor, {
      includeUI: {
        loadImage: {
          path: imgBase64,
          name: 'background',
        },
        initMenu: 'text',
        menuBarPosition: 'left',
      },
      cssMaxWidth: 2000,
      cssMaxHeight: 2000,
      selectionStyle: {
        cornerSize: 12,
        rotatingPointOffset: 90,
      },
    });

  
    //Layout default init from interface
    if(!this.currentLayout){
      this.currentLayout = new ItemLayout();
    } else {
      //Load saved Object layout..
      //timeout is required because of the init lock state
      setTimeout(() => {
        this.manageAddLayers();
      }, 500);

      console.log("Load Image Editor objects", this.currentLayout.objects, this.TUI._graphics._canvas._objects);
    }

    //inject HTML elements into the Editor for Bootstrap alert display
    let drawMenu = document.querySelector('.tui-image-editor-menu-draw');
    drawMenu.insertAdjacentHTML('afterbegin', '<div class="alert alert-warning" role="alert">'+this.languagesService.getText('tui-warning-draw')+'</div>');

    let maskMenu = document.querySelector('.tui-image-editor-menu-mask');
    maskMenu.insertAdjacentHTML('afterbegin', '<div class="alert alert-warning" role="alert">'+this.languagesService.getText('tui-warning-mask')+'</div>');

    let cropMenu = document.querySelector('.tui-image-editor-menu-crop');
    cropMenu.insertAdjacentHTML('afterbegin', '<div class="alert alert-warning" role="alert">'+this.languagesService.getText('tui-warning-crop')+'</div>');


    console.log("Init Image Editor [after]",divEditor, itemImg);
  }


  cancel() {
    this.ref.close(null);
  }


  /********************************
   * Image File Change
   *******************************/
  async save() {

    /* --- SAVE STEPS --- :
    * 1) PREVIEW: Save full image preview with TUI.toDataURL(), ref: https://github.com/nhn/tui.image-editor/search?q=toDataURL
    * 2) LAYOUT: Save layout object has JSON: TUI._graphics._canvas._objects: Keep only important properties by filtering them. ref: lodash _.pick()
    * 3) BACKGROUND: Remove layout by setting to empty array TUI._graphics._canvas._objects = [],
    *     then save only the background image with TUI.toDataURL(), this image will be used on load
    * */


    //1) Save Preview Image PNG
    // -------------------------------------------------------------------------
    let tuiImageFull = this.TUI.toDataURL({"format": "png"});
    //console.log("saveImg", imgFromCancas);

    if (tuiImageFull) {
      let newAssetImage = await this.gameDataService.createAssetImage(this.currentImage.name, tuiImageFull);
      //console.warn("saveImg: createAssetImage [after]", newAssetImage);
      this.currentImage = newAssetImage;
    }


    //2) Save Layout
    // -------------------------------------------------------------------------
    let editorObjects = _.cloneDeep(this.TUI._graphics.getCanvas().getObjects());
    console.log("TUI RAW _objects", editorObjects, this.TUI);
    this.setFilteredTUIObject(editorObjects);


    //3) Save Background image without the layout
    // -------------------------------------------------------------------------
    //Clean Canvas for background image save
    this.cleanCanvasForBackImgSave();

    //Save Image again
    let tuiImageBack = this.TUI.toDataURL({"format": "png"});
    if (tuiImageBack) {
		// Saving into an asset server. Return image object
      let newAssetImage = await this.gameDataService.createAssetImage(this.currentImage.name, tuiImageBack);
      console.warn("saveImg Back: createAssetImage [after]", newAssetImage);

      if(!this.currentLayout.background){
        this.currentLayout.background = new ImgAssetStorage(null);
      }

      this.currentLayout.background = newAssetImage;
    }


    //Apply image and layout to the deck
    // -------------------------------------------------------------------------
    this.applyImgAndLayoutToDeckAndItems();

    console.log("saveImg [END]: createAssetImage", this.currentImage,this.currentLayout, this.ref.data);


    //Close overlay
    this.ref.close(this.ref.data);
  }

  /********************************
   * Clean Canvas for background image save
   *******************************/
  cleanCanvasForBackImgSave(){
    let objects:any = this.TUI._graphics._canvas._objects;
    let keptObjects: any = [];
    for (let i = 0; i < objects.length; i++) {
      //Keep free drawing into the background image as we cannot updated it or add it back
      console.log("cleanCanvasForBackImgSave",objects[i].type);
      if(objects[i].type == "path" || objects[i].type == "line"){
        keptObjects.push(objects[i]);
      }
    }
    this.TUI._graphics._canvas._objects = keptObjects;
    console.log("cleanCanvasForBackImgSave",objects, keptObjects, this.TUI._graphics._canvas._objects);
  }

  /********************************
   * Filter TUI Editor object
   *******************************/
  setFilteredTUIObject(editorObjects:any){

    this.currentLayout.objects = [];

    //Properties pick
    var modelProp = {
      aCoords:null, //Text
      lineCoords:null,
      angle:null,
      fontSize:null,
      fontWeight:null,
      fill:null,
      fontStyle:null,
      height:null,
      left:null,
      originX:null,
      originY:null,
      origins:null,
      value:null,
      rotatingPointOffset:null,
      text:null,
      textLines:null,
      textDecoration:null,
      top:null,
      underline:null,
      width:null,
      hasBorders:null, //Shape
      rx:null,
      ry:null,
      type:null,
	  scaleX:null,
      scaleY:null,
      startPoint:null,
      stroke:null,
      strokeWidth:null,
      path:null,
      pathOffset:null,
      position:null,
      lockSkewingX:null,
      lockSkewingY:null,
    };

    for (let i = 0; i < editorObjects.length; i++) {

      if(editorObjects[i].type != "path" && editorObjects[i].type != "line"){
        //Strip off not needed properties like "_", "__", canvas, mouseMoveHandler
        let filteredProp = _.pick(editorObjects[i], _.keys(modelProp));
        this.currentLayout.objects.push(filteredProp);
      }

    }

    console.log("convertTUIObject", this.currentLayout);
  }

  /********************************
   * Manage dynamic creation of layers
   *******************************/
   manageAddLayers(){
    console.log("manageAddLayers [START]", this.currentLayout.objects);

    /*  Create an array of await function excecution
     *   - The next loop wait for the promise return to resume
     *   - each loop is wrap within a setTimeout to avoid the "Uncaught (in promise) The executing command state is locked"
     */
    let asyncAddLayout = [];
    for (let i = 0; i < this.currentLayout.objects.length; i++) {
      setTimeout(async () => {
        asyncAddLayout.push(await this.addLayer(this.currentLayout.objects[i]));
      }, 100);
    }
    console.log("manageAddLayers [END]");
  }

  /********************************
   * Add layout to editor
   *******************************/
  addLayer(layer:any){

    console.log("addLayer [START]", layer);

    let options = {
      aCoords: layer.aCoords,
      angle: layer.angle,
      fill: layer.fill,
      fontSize: layer.fontSize,
      fontWeight: layer.fontWeight,
      fontStyle: layer.fontStyle,
      textDecoration: layer.textDecoration,
      underline: layer.underline,
      height: layer.height,
      stroke: layer.stroke,
      strokeWidth: layer.strokeWidth,
      top: layer.top,
      left: layer.left,
      rotatingPointOffset: layer.rotatingPointOffset,
      rx: layer.rx,
      ry: layer.ry,
      selected: false,
      width: layer.width,
      isRegular: layer.isRegular,
      path: layer.path,
      pathOffset: layer.pathOffset,
      lineCoords: layer.lineCoords,
      originX: layer.originX,
      originY: layer.originY,
      origins: layer.origins,
      position: layer.position,
	  startPoint: layer.startPoint,
      scaleX: layer.scaleX,
      scaleY: layer.scaleY,
      styles: { //Duplicate of some properties for addText()
        angle: layer.angle,
        fontSize: layer.fontSize,
        fontWeight: layer.fontWeight,
        fontStyle: layer.fontStyle,
        textDecoration: layer.textDecoration,
        underline: layer.underline,
        fill: layer.fill,
        top: layer.top,
        left: layer.left,
        originX: "left", //layer.originX, The 'left' value is reset to 'center' when there is no change, so we force it here
        originY: "top", //layer.originY, The 'top' value is reset to 'center' when there is no change, so we force it here
        aCoords: layer.aCoords,
        position: layer.aCoords.tl,
      },
    }

    //Add layer Object based on type
    switch (layer.type) {
      case "i-text":
        console.log("addLayer [TEXT]", layer.text);
        this.TUI.addText(layer.text, options).then(objectProps => {
          //Assign all other saved values to the newly created layer
          layer.originX= "left";
          layer.originY= "top";
          _.assign(objectProps, layer);
          console.log("addLayer [TEXT completed]", objectProps.id, objectProps);
        });
        break;

      case "circle":
      case "triangle":
      case "rect":
        console.log("addLayer [SHAPE]", layer.type);
        this.TUI.addShape(layer.type, options).then(objectProps => {
          //Assign all other saved values to the newly created layer
          _.assign(objectProps, layer);
          console.log("addLayer [SHAPE completed]", objectProps.id, objectProps);
        });
        break;

      case "icon":
        console.log("addLayer [ICON]", layer.type);

        this.TUI.addIcon('arrow', options).then(objectProps => {

          //Assign all other saved values to the newly created layer
          _.assign(objectProps, layer);
          console.log("addLayer [ICON completed]", objectProps.id, objectProps);
        });
        break;

      default:
        console.error("addLayer type is not managed", layer, layer.type);
    }

  }


  /********************************
   * Apply image to deck and items
   *******************************/
  applyImgAndLayoutToDeckAndItems() {

    console.log("applyImgAndLayoutToDeckAndItems [Start]", this.currentLayout);

    //Custom code to add layout values within my app data
  }

}


`

**Comment by muneerpuri** [comment]
people who are looking for solution in react ... 

```
import React from 'react'
import 'tui-image-editor/dist/tui-image-editor.css';
import ImageEditor from '@toast-ui/react-image-editor';
import * as _ from "lodash";

const myTheme = {
    // Theme object to extends default dark theme.
  };
let editorInstance;
function Editor({setData}) {
   const  editorRef = React.createRef();
   const [editor,setEditor]=React.useState("")
   const objectsArr = []


   async function addLayer(layer){

    console.log("addLayer [START]", layer.aCoords);

    let options = {
      aCoords: layer.aCoords,
      angle: layer.angle,
      fill: layer.fill,
      fontSize: layer.fontSize,
      fontWeight: layer.fontWeight,
      fontStyle: layer.fontStyle,
      textDecoration: layer.textDecoration,
      underline: layer.underline,
      height: layer.height,
      stroke: layer.stroke,
      strokeWidth: layer.strokeWidth,
      top: layer.top,
      left: layer.left,
      rotatingPointOffset: layer.rotatingPointOffset,
      rx: layer.rx,
      ry: layer.ry,
      selected: false,
      width: layer.width,
      isRegular: layer.isRegular,
      path: layer.path,
      pathOffset: layer.pathOffset,
      lineCoords: layer.lineCoords,
      originX: layer.originX,
      originY: layer.originY,
      origins: layer.origins,
      position: layer.position,
	  startPoint: layer.startPoint,
      scaleX: layer.scaleX,
      scaleY: layer.scaleY,
      styles: { //Duplicate of some properties for addText()
        angle: layer.angle,
        fontSize: layer.fontSize,
        fontWeight: layer.fontWeight,
        fontStyle: layer.fontStyle,
        textDecoration: layer.textDecoration,
        underline: layer.underline,
        fill: layer.fill,
        top: layer.top,
        left: layer.left,
        originX: "left", //layer.originX, The 'left' value is reset to 'center' when there is no change, so we force it here
        originY: "top", //layer.originY, The 'top' value is reset to 'center' when there is no change, so we force it here
        aCoords: layer.aCoords,
        position: layer.aCoords.tl,
      },
    }

    //Add layer Object based on type
    switch (layer.type) {
      case "i-text":
        console.log("addLayer [TEXT]", layer.text);
       await  editorInstance.addText(layer.text, options).then(objectProps => {
          //Assign all other saved values to the newly created layer
          layer.originX= "left";
          layer.originY= "top";
          _.assign(objectProps, layer);
          console.log("addLayer [TEXT completed]", objectProps.id, objectProps);
        });
        break;

      case "circle":
      case "triangle":
      case "rect":
        console.log("addLayer [SHAPE]", layer.type);
       await editorInstance.addShape(layer.type, options).then(objectProps => {
          //Assign all other saved values to the newly created layer
          _.assign(objectProps, layer);
          console.log("addLayer [SHAPE completed]", objectProps.id, objectProps);
        });
        break;

      case "icon":
        console.log("addLayer [ICON]", layer.type);

       await editorInstance.addIcon('arrow', options).then(objectProps => {

          //Assign all other saved values to the newly created layer
          _.assign(objectProps, layer);
          console.log("addLayer [ICON completed]", objectProps.id, objectProps);
        });
        break;

      default:
        console.error("addLayer type is not managed", layer, layer.type);
    }

  }


   function setFilteredTUIObject(editorObjects){


    //Properties pick
    var modelProp = {
      aCoords:null, //Text
      lineCoords:null,
      angle:null,
      fontSize:null,
      fontWeight:null,
      fill:null,
      fontStyle:null,
      height:null,
      left:null,
      originX:null,
      originY:null,
      origins:null,
      value:null,
      rotatingPointOffset:null,
      text:null,
      textLines:null,
      textDecoration:null,
      top:null,
      underline:null,
      width:null,
      hasBorders:null, //Shape
      rx:null,
      ry:null,
      type:null,
	  scaleX:null,
      scaleY:null,
      startPoint:null,
      stroke:null,
      strokeWidth:null,
      path:null,
      pathOffset:null,
      position:null,
      lockSkewingX:null,
      lockSkewingY:null,
    };

    for (let i = 0; i < editorObjects.length; i++) {

      if(editorObjects[i].type != "path" && editorObjects[i].type != "line"){
        //Strip off not needed properties like "_", "__", canvas, mouseMoveHandler
        let filteredProp = _.pick(editorObjects[i], _.keys(modelProp));
        objectsArr.push(filteredProp);
      }

      setData(objectsArr)

    }

  }
   function handleClickButton()  {
    setFilteredTUIObject(editorInstance._graphics.getCanvas()._objects);


    };
   function handleClickButton1()  {
    console.log(editorInstance._graphics.getObjectProperties(3));


    };
    function objectAdded(props){
        console.log(props)

    }
    React.useEffect(()=>{
         editorInstance = editorRef.current.getInstance();
        setEditor(editorRef.current.getInstance())
        // editorInstance.loadImageFromURL('https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-600w-1725825019.jpg', 'lena')
    })  

    React.useEffect(()=>{
      if(editorInstance){
        editorInstance.on('redoStackChanged',(props)=>console.log(props,"redoStackChanged"))
        editorInstance.on('objectAdded',(props)=>console.log(props,"objectAdded"))
        editorInstance.on('undoStackChanged',(props)=>console.log(props,"undoStackChanged"))
        editorInstance.on('addText',(props)=>console.log(props,"addText"))
        // editorInstance.on('textEditing',(props)=>console.log(props,"addText"))
        console.log(editorInstance._initHistory())
        // editorInstance.on('objectMoved',(props)=>console.log(props,"addText"))

      }
    })
    try{

    
  return (
    <div>

<ImageEditor
        ref={editorRef}
        includeUI={{
            objectAdded,
        loadImage: {
            path: 'https://image.shutterstock.com/image-photo/mountains-under-mist-morning-amazing-600w-1725825019.jpg',
            name: 'SampleImage'
          },
      theme: myTheme,
      menu: ['shape', 'filter','text','icon','crop',],
      initMenu: 'filter',
      uiSize: {
        width: '1000px',
        height: '700px',
      },
      menuBarPosition: 'bottom',
    }}
    cssMaxHeight={500}
    cssMaxWidth={700}
    selectionStyle={{
      cornerSize: 20,
      rotatingPointOffset: 70,
    }}
    usageStatistics={true}
  />
  <button onClick={handleClickButton}>Save all</button>
  <button onClick={()=>{

let asyncAddLayout = [];

    objectsArr.forEach(async (el)=>{
      setTimeout(async () => {
        asyncAddLayout.push( await addLayer(el))
    }, 100);
    })
  }}>Re paste all</button>
    </div>
  )
}catch(e){
    console.log(e);
    window.location.reload()

}
}

export default Editor
```
