### ISSUE TITLE
update: Update Fabric.js version

### ISSUE THREAD

**Issue by junghwan-park** [nhn/tui.image-editor#129]
## AS-IS

- Currently **TOAST UI Image-Editor** using **Fabric.js@1.6.7**
- **Fabric.js@1.6.7** doesn't support ES module `import`
- **TOAST UI Image-Editor** installs Fabric.js via _npm script_ `postinstall` and imports fabric `import fabric from 'fabric/dist/fabric.require';`

## TO-BE

- Update [Fabric.js](https://github.com/fabricjs/fabric.js) latest version.
- Change **Fabric.js** import method to ES module `(Named) import`

## Change

- `GradientTransparency` filter removed by fabric.js

**Comment by wroberts** [comment]
:+1:

**Comment by junghwan-park** [comment]
- fabric.js-v3.2.0 적용 테스트중
    - 사용에는 이상 없음.
    - 하지만, commonjs 패턴으로 모듈이 정의되면 amd 모듈을 정의할 수 있더라도 정의하지 않도록 번들링 코드가 수정되어서 karma로 수행하는 테스트에서 fabric을 정상적으로 가져올 수 없음.
    - 해당 이슈를 webpack 설정이나 karma 설정으로 해결 가능한지 R&D가 더 필요함.

**Comment by junghwan-park** [comment]
- karma내부 webpack 설정도 기존 webpack.config.json과 동일하게 `fabric.js`를 externals 에 추가하고 files에 `fabric.js`를 추가해서 브라우저에서 로드하도록 수정하여 해결함.
- fabric 수정은 필요하지 않았음.
