### ISSUE TITLE
How to add custom menu buttons

### ISSUE THREAD

**Issue by GEMI** [nhn/tui.image-editor#132]
## Version
3.4.0

## Development Environment
Windows 10

## Current Behavior
All menu buttons are predefined `menu: ['crop', 'flip', 'rotate', 'draw', 'shape', 'text', 'filter'],`

## Question
How can I add custom menu buttons? For example 'save'?

**Comment by junghwan-park** [comment]
@GEMI
Currently adding menu button or something functional into TOAST UI Image-Editor UI via Image-Editor constructor's `options` parameter or certain API is not available.

If you have to create `save` button and add that button among TOAST UI Image-Editor's menu buttons, you should extend TOAST UI Image-Editor `src/ui/template/controls.js` or just add a button into after Image-Editor rendered.

**Comment by arifhussain353** [comment]
This is not a proper solution but you can do with `JQuery` or `Javascript`  by replacing HTML on load. For example:
```   
 $('.tui-image-editor-header-buttons .tui-image-editor-download-btn').
replaceWith('<button class="tui-image-editor-save-btn" >Save</button>')
```
Replace `Download` button into `Save` and then attach event with `addEventListener`
```    
document.querySelector('.tui-image-editor-header-buttons .tui-image-editor-save-btn').
addEventListener('click', this.prcoessSaveImage)
```
```
fucntion prcoessSaveImage(){
//your code
}
```

**Comment by xiezm** [comment]
@arifhussain353 

虽然你这种侵入性的方法很龊，更新以后的新版本，可能就不兼容了。
但是目前要想解决问题，还不得不这么做。
看不懂，你自己去翻译吧。

**Comment by sergeizhukov** [comment]
Yeah It should be able at least to rename standard buttons. Add a new one.

**Comment by KunalBurangi** [comment]
The download button opes a new tab . i don't want that new tab how to stop that ?

**Comment by ravizeewee** [comment]
> @GEMI
> Currently adding menu button or something functional into TOAST UI Image-Editor UI via Image-Editor constructor's `options` parameter or certain API is not available.
> 
> If you have to create `save` button and add that button among TOAST UI Image-Editor's menu buttons, you should extend TOAST UI Image-Editor `src/ui/template/controls.js` or just add a button into after Image-Editor rendered.

Can you show the example?

**Comment by IrtazaHussain1** [comment]
Hi! I want to use the custom function on the download button  is it possible and how can I do that

**Comment by praveenrsg** [comment]
I want to remove "Load" and "Download" Button  and the header text 
Please have a look on the marked area of the below image
![image](https://user-images.githubusercontent.com/13588919/82176928-bd62ce00-98f5-11ea-8175-2bb6844a65b2.png)

**Comment by LemuelKL** [comment]
> I want to remove "Load" and "Download" Button and the header text
> Please have a look on the marked area of the below image
> ![image](https://user-images.githubusercontent.com/13588919/82176928-bd62ce00-98f5-11ea-8175-2bb6844a65b2.png)

I removed the header all together by overriding the following CSS properties in my Vue project:
`.tui-image-editor-header {
  display: none;
}
.tui-image-editor-container .tui-image-editor-main {
  top: 0;
}`

**Comment by vladsovetov** [comment]
> I want to remove "Load" and "Download" Button and the header text
> Please have a look on the marked area of the below image
> ![image](https://user-images.githubusercontent.com/13588919/82176928-bd62ce00-98f5-11ea-8175-2bb6844a65b2.png)

Seems slightly cleaner solution
`
const myTheme = {
    "header.display": "none"
};
var instance = new ImageEditor(document.querySelector('#tui-image-editor'), {
     includeUI: {
         ...
         theme: myTheme,
         ...
     },
    ...
});
`

**Comment by singhkirtii** [comment]
Hi. I want to save the edited image (without downloading it to the local system) in a storage system (maybe S3) and then save the image URL in database. How can I do that?

**Comment by azakero** [comment]
> Hi. I want to save the edited image (without downloading it to the local system) in a storage system (maybe S3) and then save the image URL in database. How can I do that?

@singhkirtii  I'm looking for this solution as well. Could you figure it out?

**Comment by singhkirtii** [comment]
Yes. You can fetch the image data using the editor's toDataURL() function. This data can also be converted into blob, if needed. Once you have the image data, you can send it to the server and then upload the dataURI/blob directly to S3.

**Comment by azakero** [comment]
Thanks mate. Understood

**Comment by eriksetiadi-pro** [comment]
how do i can add 1 or more menu?
![Screenshot_11](https://user-images.githubusercontent.com/68863121/111141776-819ca180-85b6-11eb-860b-842ae31b89ad.png)

**Comment by vijaykuamrparelli** [comment]
![git](https://user-images.githubusercontent.com/50367043/128979840-c1383857-8106-4ded-93bb-741076a964cf.PNG)
How to add one more menu item inti list with submenus

**Comment by naghamsayegh** [comment]
@eriksetiadi-pro  @vijaykuamrparelli  
just add them in the menu
`export default function App() {
  const props = {
    includeUI: {
      menu: [**"shape", "filter", "text","crop","draw","rotate","flip","icon","mask"**],
      initMenu: "filter",
      uiSize: {
        width: "1000px",
        height: "700px"
      },
      menuBarPosition: "bottom"
    },
    cssMaxWidth: 700,
    cssMaxHeight: 500,
    selectionStyle: {
      cornerSize: 20,
      rotatingPointOffset: 70
    }
  };
`

**Comment by naghamsayegh** [comment]
> > I want to remove "Load" and "Download" Button and the header text
> > Please have a look on the marked area of the below image
> > ![image](https://user-images.githubusercontent.com/13588919/82176928-bd62ce00-98f5-11ea-8175-2bb6844a65b2.png)
> 
> Seems slightly cleaner solution
> 
> ```
> const myTheme = {
>     "header.display": "none"
> };
> var instance = new ImageEditor(document.querySelector('#tui-image-editor'), {
>      includeUI: {
>          ...
>          theme: myTheme,
>          ...
>      },
>     ...
> });
> ```

How can I remove only the title and keep up the buttons

**Comment by Shane-Geary** [comment]
> 

Any suggestions on a React equivalent of this?

**Comment by lja1018** [comment]
@Shane-Geary 
There is no way to add a menu yet. We will decide after a discussion with the team.

**Comment by PrashantNandanvar** [comment]
![Screenshot from 2022-05-24 11-47-14](https://user-images.githubusercontent.com/101239469/169962072-575bb741-4a6e-45d8-a99e-885865c3540d.png)
How can i use this theme using html

**Comment by lja1018** [comment]
@PrashantNandanvar 
`Menubar Position Top` does not have a separate theme.
You can set the option by setting it to `includeUI.menuBarPosition.top = 'top'`.

**Comment by lja1018** [comment]
@yuban00018 
Would you like to use `file-saver`?

**Comment by shireennazneen** [comment]
const logImageContent = () => {
    const instance = refImage.current.imageEditorInst;
    let dataUrl = instance.toDataURL();
console.log(dataUrl)
  };

and add button  save and give the onClick ={logImageContent} you will get  bs64 data of image    and use it

**Comment by Breezewrf** [comment]
> @Shane-Geary There is no way to add a menu yet. We will decide after a discussion with the team.

Hi, 

Is there any solution?
