### ISSUE TITLE
how can i know this canvas has been edited?

### ISSUE THREAD

**Issue by hzeeli** [nhn/tui.image-editor#133]
## Version
v3.4.0

## Development Environment
windows/chrome

## Current Behavior

i want to know the canvas's editing status that i can send a prompt to users they hadn't save it

## Expected Behavior
get the status

**Comment by junghwan-park** [comment]
@hzeeli 

As user changes something, undo stack changes ether.
Capture first undo stack change and create `isEdited` state in your application and use that state for canvas edited or not.

- reference: https://nhnent.github.io/tui.image-editor/latest/ImageEditor.html#event:undoStackChanged

--- 

However, I found Image-Editor latest version has an undo stack issue about `loadImage` option.
It changes undo stack abnormally when initialize canvas with `loadImage` option's image resource. 
I'll solve this in next release.

**Comment by hzeeli** [comment]
@junghwan-park 
yeah,
i try to use `isEmptyUndoStack()` to catch the state of canvas
but 
after i use `loadImageFromURL()`,  `clearUndoStack()` doesn't work,i can't catch the `isEmptyUndoStack()` correctly

**Comment by hzeeli** [comment]
`undoStackChanged` it's a good way
and 
where is the reset method
like reset icon at slidemenu
to reset the editor 
thanks a lot

**Comment by hzeeli** [comment]
@junghwan-park 
how can i use the events in vueCli?
thanks a lot
