### ISSUE TITLE
Loading in Ionic 3

### ISSUE THREAD

**Issue by gelinger777** [nhn/tui.image-editor#141]
Could somebody help out? How can Tui be loaded in Ionic 3/4 ? 

Because traditional 

var ImageEditor = require('tui-image-editor');
var blackTheme = require('./js/theme/black-theme.js');

is not working with Typescript ...

**Comment by gelinger777** [comment]
@nhnent could you help out>

**Comment by junghwan-park** [comment]
@gelinger777 
Please follow the Issue template's guideline. Simply saying "not working with Typescript" is kind of implicit to me.
Could you tell me at least the environment of your development, AS-IS & TO-BE?

**Comment by gelinger777** [comment]
@junghwan-park  ionic  works with synthax like 


import tui from "tui"; 


I will try to send out actual error messages I am getting when I am back to office

**Comment by Nitinchavda** [comment]
@junghwan-park : You got it working?

**Comment by junghwan-park** [comment]
@Nitinchavda 
What kind of problem with CSS?
Tell me some details please.

**Comment by Nitinchavda** [comment]
@junghwan-park : thanks for the reply, i got it working in Ionic 3 app but having some trouble to access object in ionic page. :)

**Comment by junghwan-park** [comment]
@Nitinchavda 
You mean, you want to know how to import `ImageEditor`'s css into your Ionic3 app?
