### ISSUE TITLE
Confirmation of dependencies.

### ISSUE THREAD

**Issue by goldingdamien** [nhn/tui.image-editor#147]
I tried setting up this library in my project as shown in the README but I got the following error:

> Uncaught TypeError: Cannot read property 'createClass' of undefined
at:
`var Cropzone = _fabric2.default.util.createClass(_fabric2.default.Rect, /** @lends Cropzone.prototype */{`

I have not added any dependencies shown in the "dependency" section of README.
I could not tell whether "dependency" meant the libraries were included or needed to be included.
Please can you clarify this, and if not too much trouble update the README to make this clear.

An example would also be much appreciated, and any additional info on things such as if require/import can be used or setting to window is necessary would also.

Regards.

**Comment by junghwan-park** [comment]
@goldingdamien 
Okay, I'll clarify dependency meaning and add some tutorial/examples for users.
