### ISSUE TITLE
Image Editor UI for mobile

### ISSUE THREAD

**Issue by ion4927** [nhn/tui.image-editor#154]
## Version
"tui-image-editor": "3.4.0",

## Development Environment
Ionic 3, which uses Angular 5 (tested with Chrome)

## Current Behavior
Im trying to use the image editor with ionic.
Here the code from my test page:

```html
<ion-header no-border>
	<ion-navbar color="primary">
        <ion-title>Tui test page</ion-title>
    </ion-navbar>
</ion-header>


<ion-content>

	<div id="tui-image-editor">
		<canvas></canvas>
	</div>

</ion-content>
```

```ts
import { Component } from '@angular/core';
import { IonicPage } from 'ionic-angular';
import ImageEditor from 'tui-image-editor';
import { Meta } from '@angular/platform-browser';

@IonicPage()
@Component({
    selector: 'page-test',
    templateUrl: 'test.html'
})
export class TestPage {
    constructor(private meta: Meta) {
        this.meta.addTag({name: 'viewport', content: 'width=device-width, user-scalable=no'});
    }

    ionViewDidLoad() {
        var instance = new ImageEditor(document.querySelector('#tui-image-editor'), {
            includeUI: {
                loadImage: {
                    path: 'assets/img/example.jpg',
                    name: 'SampleImage'
                },
                initMenu: 'filter',
                menuBarPosition: 'bottom'
            },
            cssMaxWidth: document.documentElement.clientWidth,
            cssMaxHeight: document.documentElement.clientHeight,
            selectionStyle: {
                cornerSize: 20,
                rotatingPointOffset: 40
            }
        });
    }
}

```

first, it looked like this:  
https://i.imgur.com/hGiIemv.png  
then i copy pasted the style from the tui-image-editor.css file that i found in the node_modules package to the page's css file and it looked like this:  
https://i.imgur.com/ILS1Iss.png  
Functionality is there though. Here (https://github.com/nhnent/tui.image-editor/blob/master/docs/Apply-Mobile-Version.md) at Step 5 the css file that is added is called tui-image-editor-m.css, which i assume is for mobile, but i couldn't find it anywhere.  
So is there a way to get a working UI on mobile?

## Expected Behavior
something like this:
http://nhnent.github.io/tui.image-editor/latest/tutorial-example03-mobile.html

**Comment by junghwan-park** [comment]
@ion4927 
Currently [default UI\`s](http://nhnent.github.io/tui.image-editor/latest/tutorial-example01-includeUi.html) mobile version UI is not available yet.
I think that last example link of **Step 6. Apply the image editor API to the UI** section is mis-linked.

http://nhnent.github.io/tui.image-editor/latest/tutorial-example03-mobile.html is the right example of [Apply mobile version.md](https://github.com/nhnent/tui.image-editor/blob/master/docs/Apply-Mobile-Version.md).
I'll modify both example link and css file name on that document.

**Comment by Nitinchavda** [comment]
@ion4927 : you've demo app in Ionic 3?

**Comment by hannata** [comment]
@ion4927 did you fix the issue ? i have the same problem in ionic 4
