### ISSUE TITLE
Unable to add or overwrite editor default values, using in angular

### ISSUE THREAD

**Issue by pritamgudekar** [nhn/tui.image-editor#160]
## Version
 * tui-image-editor.js
 * @version 3.4.0 

Hi,

I have imported this library in angular successfully. I want to override default values of toolbar of the editor, e.g. change default text 'Double Click' to something else like 'Sample text here...'. I used following code:

```js
const imageEditor = this.imageEditor;
    this.imageEditor.on('addText', function(pos) {
      console.log('Called here...', pos);
      imageEditor.addText('Sample text here...', {
        position: pos.originPosition
      }).then(objectProps => {
        console.log(objectProps.id);
      });
    });
```
but I am getting this error:
       Unhandled promise rejection The executing command state is locked.
However the on event is getting called i.e. console.log('Called here...', pos); but imageEditor.addText('Sample text here...', is not executing.

Please help on this issue.

Thanks in advance!

**Comment by junghwan-park** [comment]
@pritamgudekar 
I think that example code is wrong. ImageEditor can't add text until `addText` event is done.
I'll edit example code. Thank you to reporting.

**Comment by pritamgudekar** [comment]
Oh ok. 
Is there any way to change default values for tools like 
 - change default range value for text font. Currently defaultTextRangeValus  = 50, want to change to 10
 - change default text from 'Double Click' to 'some other text' etc?

There is a provision to change default styles through theme file, but for tools default value, looking similar provision. Please advice.

Thanks

**Comment by junghwan-park** [comment]
@pritamgudekar 
Currently, there is no way to change both default **text** and **fontSize** handy.
It'll take some times for adding options for customization whole features like you said. I'll add this to enhancement task list.
Thanks.

**Comment by zhaoyuhang1033** [comment]
When the 'addtext' method is executed  
'Islock' locks all related operations  
So we have to wait until he's done. 
(This is not a good way to do it.)
(My English is not very good.  )
```js
setTimeout(() => {
        this.$refs.tuiImageEditor.invoke(
          'changeText',
          this.$refs.tuiImageEditor.editorInstance.activeObjectId,
          'init'
        )
      }, 0)
```

**Comment by lerit** [comment]
you can listen addText events,and execute changeText immediately.because addText command is executing,so changeText event should execute after addText,setTimeout may help you @pritamgudekar

**Comment by pritamgudekar** [comment]
Sure will try it out. thanks

**Comment by zxh2013** [comment]
@zhaoyuhang1033 , you are really 🐂
