### ISSUE TITLE
Latest fabric.js is not supported

### ISSUE THREAD

**Issue by T-vK** [nhn/tui.image-editor#161]
## Version
ToastUI Image Editor 3.5.1
fabric.js 2.7.0

## Development Environment
Linux (Fedora 29) x64; Firefox 65

## Current Behavior
Using a recent fabric.js version causes errors and unwanted behavior:

It complaints about  `this._canvas.discardActiveGroup();` in tui-image-editor.js `discardActiveGroup is not a function`.

```js
        fetch(imageUrl).then(res=>{
            return res.blob()
        }).then(file=>{
            return imageEditor.loadImageFromFile(file, 'example')
        }).then(result=>{
            imageEditor.ui.resizeEditor({
                imageSize: {oldWidth: result.oldWidth, oldHeight: result.oldHeight, newWidth: result.newWidth, newHeight: result.newHeight},
            })
        })
```

## Expected Behavior
Compatibility with the latest fabric.js

**Comment by junghwan-park** [comment]
@T-vK 
Currently ImageEditor not compatible with `fabric v2.x.x`. But, It'll be updated to 2.7.0 soon. I'm working on it.

**Comment by T-vK** [comment]
The problem is that the Readme says you need fabric.js >=1.6.7. That's why I chose 2.7.0.

**Comment by junghwan-park** [comment]
@T-vK
I think `& < 2.0.0` is missing. Sorry for dependency version misinforming.
