### ISSUE TITLE
How I can draw arrow with startDrawingMode function?

### ISSUE THREAD

**Issue by GHarutyunyan** [nhn/tui.image-editor#163]
Now I can only use 'CROPPER', 'FREE_DRAWING', 'LINE_DRAWING', 'TEXT', 'SHAPE' modes

**Comment by GHarutyunyan** [comment]
I want from this arrow

![0](https://user-images.githubusercontent.com/12736720/54120269-bea28c00-4410-11e9-86ca-dbc02f48070b.png)

**Comment by junghwan-park** [comment]
@GHarutyunyan 
`startDrawingMode()` only activates `cropper` or `drawing`, `text`, `shape` tool for mouse actions.
Sooner or later, I'll add some API's for creating and manipulating canvas objects with adding event listeners #136.

**Comment by Aarbel** [comment]
@GHarutyunyan have you found a solution for this ?

**Comment by Aarbel** [comment]
Works great with the api: http://nhn.github.io/tui.image-editor/latest/ImageEditor#startDrawingMode

**Comment by wtwsky** [comment]
@GHarutyunyan have you found a solution for this ?
