### ISSUE TITLE
When I call addText() function and after click on that text I can't edit that text and get error Uncaught TypeError: Cannot read property 'style' of null 

### ISSUE THREAD

**Issue by GHarutyunyan** [nhn/tui.image-editor#164]

**Comment by junghwan-park** [comment]
@GHarutyunyan Please follow issue template guideline. Describe some codes you wrote and environments.

**Comment by GHarutyunyan** [comment]
I check your codes and there I see that on line 13979 writed `this.useItext = useItext;` and for that I can't change text after call addText() function.When I change `this.useItext = useItext;`  to `this.useItext = true;` everything depends text working fine.

eg.I tried send useItext with `:options` prop but I doesn't works too.

**Comment by junghwan-park** [comment]
@GHarutyunyan 
Are you using custom UI your own? ImageEditor using `IText` when `includeUI` option is set.

Could you tell me more details of your development environment and codes for help you out?

**Comment by Akari1987** [comment]
Same issue, but I solved it.
In my case, I use custom UI. I need to init imageEditor.startDrawingMode('TEXT') before imageEditor.addText('text').

**Comment by EmilienLeroy** [comment]
Same as @Akari1987, init imageEditor.startDrawingMode('TEXT') work for me.
