### ISSUE TITLE
Free drawing line jump slightly left and top after next editing

### ISSUE THREAD

**Issue by junghwan-park** [nhn/tui.image-editor#167]
## Version

3.5.0
## Development Environment

OSX, Chrome
## Current Behavior

Free drawing line jumps after next editing. But Straight line doesn't.

![line jumping](https://user-images.githubusercontent.com/7088720/54401678-f4df5480-470b-11e9-9ec3-a29deb539561.gif)

![line jumping2](https://user-images.githubusercontent.com/7088720/54401765-60c1bd00-470c-11e9-952c-4fa169ead7bf.gif)

## Expected Behavior

Free drawing line should not move any pixels.

ref: #151

**Comment by zhaoyuhang1033** [comment]
I am the same,in the chrome  and vue

**Comment by syednoor6208** [comment]
same issue in react js.

**Comment by dexp-io** [comment]
Same issue on live demo
https://cl.ly/7c213f253101/Screen%20Recording%202019-06-24%20at%2009.00%20AM.gif

**Comment by calvinkei** [comment]
any fix yet?

**Comment by dexp-io** [comment]
Downgrade to 3.3.1 version seems to help

**Comment by dimakovalevskyi** [comment]
Try to use fabric.js 1.6.7. It helps me.

**Comment by stanleek** [comment]
downgrade does not help

**Comment by Langstra** [comment]
Any idea when this is going to be fixed?

**Comment by jinwoo-kim-nhn** [comment]
resolved at 3.7.1

**Comment by DishantOpenxcell** [comment]
I faced the same issue even after you fixed

**Comment by klmaaa** [comment]
You should update the brushWidth in tui-image-editor.js as follows:

**From**
```javascript
function getBrushSettings() {
  var brushWidth = $inputBrushWidthRange.val();
  var brushColor = brushColorpicker.getColor();

  return {
    width: brushWidth,
    color: hexToRGBa(brushColor, 0.5),
  };
}
```

**To**
```javascript
function getBrushSettings() {
  var brushWidth = parseInt($inputBrushWidthRange.val(), 10);
  var brushColor = brushColorpicker.getColor();

  return {
    width: brushWidth,
    color: hexToRGBa(brushColor, 0.5),
  };
}
```
