### ISSUE TITLE
Mobile version does not load color selection in box for icon and text 

### ISSUE THREAD

**Issue by Nitinchavda** [nhn/tui.image-editor#171]
## Version
3.5.1

## Development Environment
mobile 

## Current Behavior
Missing color in box
https://prnt.sc/mznvfu

// Write example code
```

## Expected Behavior
It should be fill like this
https://prnt.sc/mznw8w

**Comment by nikolayg** [comment]
I've noticed the fill colour appears on resizing ... any ideas how to force it programmatically.

**Comment by jinwoo-kim-nhn** [comment]
![71879559-b2db3f80-3171-11ea-9934-4c8eddcddbd8](https://user-images.githubusercontent.com/35218826/73803319-c24ab880-4803-11ea-81ee-1a4cad35f6ae.png)
