### ISSUE TITLE
Question (logo)

### ISSUE THREAD

**Issue by JY-Heo** [nhn/tui.image-editor#176]
## Version
3.5.1

## Current Behavior
색을 커스터마이징해 사용하려고 하는데..
다른부분 색을 변경하고 나니 로고 색상도 변경하고 싶어 질문 드립니다.

로고 색상을 노란색에서 => 그레이로 변경하려는데 변경해서 사용해도 되는지 궁금합니다.

**Comment by junghwan-park** [comment]
@JY-Heo 마음껏 변경해서 사용해도 됩니다~ MIT 라이선스로 배포되었으니까요. =)

**Comment by JY-Heo** [comment]
답변 감사드립니다 ㅎㅎㅎㅎㅎ
