### ISSUE TITLE
github page issue

### ISSUE THREAD

**Issue by markosjal** [nhn/tui.image-editor#182]
at
https://github.com/nhn/tui.image-editor/wiki/Basic-Tutorial
 very bottom, you list 

## More.. See the API page and the sample page * API: http://nhnent.github.io/tui.component.image-editor/latest/ * Sample: http://nhnent.github.io/tui.component.image-editor/latest/tutorial-basic.html

Both URLs do not load

would love to read them though

**Comment by junghwan-park** [comment]
@markosjal You can read from now on. I edited whole gh-page link URLs in wiki documents. 
My organization name changed `nhnent` to `nhn`. I think github supports repository subDomain auto redirecting like `github.com/nhnent/*` to `github.com/nhn/*` but `gh-pages` domain wasn't.
Thank you to report!
