### ISSUE TITLE
the rotate utility is too buggy to be useful

### ISSUE THREAD

**Issue by markosjal** [nhn/tui.image-editor#183]
## Version
3.5.2
Include UI as in example 1

## Development Environment
Chromium browser Ubuntu Linux 16.04 x86_64

## Current Behavior
The rotate feature is USELESS . It is impossible for example to set to 90 degrees . default is 30 degrees (why?) .  The slider control does not have the "resolution" as I am stuck selecting something close to 90 degrees andf can never get exactly 90 degrees. To complicate matters then I am left with HUNDREDS of undos to go back! It seems there are several undoss each time I move the slider.
Working from the included example 1 this problem occurs. It is more tolerable in example 2 because you can use left/right keys to fine tune but still unacceptable. Left right keys do not work at all on includeUI ex 1. the left right keys as well as being able to enter avalue are essential in making the "really work" .

## Expected Behavior
I would expect I could use left right keys as well as enter a numeric value where it is displayed. there is also no reason the slider could not be longer to give true 1 degree resolution. It needs 360 steps in this case.

**Comment by Fauxil-Fox** [comment]
Just click the rotate 30º three times, works for me!

**Comment by markosjal** [comment]
That is not a fix, it is a work-around  It also assumes I want to rotate 90 degress in that direction

**Comment by jinwoo-kim-nhn** [comment]
Improved to modify directly in input. v3.8.0
