### ISSUE TITLE
write the file back to the server?

### ISSUE THREAD

**Issue by markosjal** [nhn/tui.image-editor#184]
I do not needd upload and download features ,

What I do need is , I need to write the file back to the server when done. Is this possible?

**Comment by markosjal** [comment]
It seems to me that this is typically done by "document.getElementById" but from what I see there is no ID. getElementsByClassName returns a collection, not a single element and this complicates maters.

**Comment by markosjal** [comment]
No response on this whatsoever? I am sure it must be a common question.

**Comment by junghwan-park** [comment]
@markosjal Sorry for late reply. 

> I do not needd upload and download features ,
> 
> What I do need is , I need to write the file back to the server when done. Is this possible?

You can use [imageEditorInstance.toDataURL()](https://nhn.github.io/tui.image-editor/latest/ImageEditor#toDataURL) API and develop on your own server transfer feature.

> It seems to me that this is typically done by "document.getElementById" but from what I see there is no ID. getElementsByClassName returns a collection, not a single element and this complicates maters.

Sorry. I don't understand why you are saying about `document.getElementById()` and `document.getElementsByClassName()`. Is it related with your first comment's feature?

**Comment by markosjal** [comment]
I guess some people do not understand that not everyone is a developer of projects like this . This would seem to be a BASIC function that should be integrated to the core code. I mean why would anyone want a web page to upload an image , edit it then download it again? It really makes little sense. Especially given that there are better, more responsive editors for most any platform that eliminate the need to upload and download. From the numerous bugs I identified in a couple hours on day one of testing and the lack of ability to readily upload it seems it is a half-baked project , that nobody really seems to test or think about how it will be deployed. I think your biggest potential userbase is Social networking and dating sites where people want to upload an images make some changes and upload to server to be on their profile. Note the upload to server step.

**Comment by markosjal** [comment]
ALso from what I understand, which could be wrong, if you assign an ID to the canvas , which it apparently does not have, then one could document.getElementById. Why would you NOT assign an ID to the canvas?

**Comment by junghwan-park** [comment]
@markosjal 

> I guess some people do not understand that not everyone is a developer of projects like this . This would seem to be a BASIC function that should be integrated to the core code. I mean why would anyone want a web page to upload an image , edit it then download it again? It really makes little sense. Especially given that there are better, more responsive editors for most any platform that eliminate the need to upload and download. From the numerous bugs I identified in a couple hours on day one of testing and the lack of ability to readily upload it seems it is a half-baked project , that nobody really seems to test or think about how it will be deployed. I think your biggest potential userbase is Social networking and dating sites where people want to upload an images make some changes and upload to server to be on their profile. Note the upload to server step.



Okay. I'll think about that server transfer feature you said. That could be more responsible. Thanks.



> ALso from what I understand, which could be wrong, if you assign an ID to the canvas , which it apparently does not have, then one could document.getElementById. Why would you NOT assign an ID to the canvas?


The canvas in the image editor is controlled by fabric.js. If the canvas element of fabric.js is opened freely by element ID or class, it is likely that some users will be able to modify the canvas themselves. But Fabric.js doesn't know what's going on in the canvas. And that could be the cause of the malfunction. 
The best way is to easily provide image data to all users through the APIs of the Image Editor. And I'll try to find the best way. Thank you again for your suggestion.

**Comment by markosjal** [comment]
I do see this in tui-image-editor.js
      `
	         * To data url from canvas
	         * @param {Object} options - options for toDataURL
	         *   @param {String} [options.format=png] The format of the output image. Either "jpeg" or "png"
	         *   @param {Number} [options.quality=1] Quality level (0..1). Only used for jpeg.
	         *   @param {Number} [options.multiplier=1] Multiplier to scale by
	         *   @param {Number} [options.left] Cropping left offset. Introduced in fabric v1.2.14
	         *   @param {Number} [options.top] Cropping top offset. Introduced in fabric v1.2.14
	         *   @param {Number} [options.width] Cropping width. Introduced in fabric v1.2.14
	         *   @param {Number} [options.height] Cropping height. Introduced in fabric v1.2.14
	         * @returns {string} A DOMString containing the requested data URI.
	         */

	    }, {
	        key: 'toDataURL',
	        value: function toDataURL(options) {
	            return this._canvas && this._canvas.toDataURL(options);
	 `

**Comment by markosjal** [comment]
on addditional note the upload would be when the user leaves the editor so there would be no further reason that frabric.js would need to know if any change as all changes are DONE
