### ISSUE TITLE
 menuBarPosition: 'top' broken

### ISSUE THREAD

**Issue by markosjal** [nhn/tui.image-editor#185]
Downloaded yesterday and installed for testing
when modifying example 1 selecting  menuBarPosition: 'top'

breaks the page by causing the Load button to come out in a rectangle above where it should be and causing the buttons like "crop" to initiate "Load" function. 

![Screenshot at 2019-04-16 03:48:21](https://user-images.githubusercontent.com/281916/56195983-9b649100-5ffb-11e9-8c9a-7b47168a9ba1.png)

**Comment by markosjal** [comment]
Not fixed , just downloaded and tested. Still broken

**Comment by junghwan-park** [comment]
@markosjal 
Are you pull the `origin/master` branch and do code bundling or open `webpack-dev-server` on your PC? It works well.
I didn't deploy and publish to npm yet.

**Comment by markosjal** [comment]
I used themaster . What I see is it is missing a "<button>Load</button>"
<div style="background-color: #fff;border: 1px solid #ddd;color: #222;font-family: 'Noto Sans', sans-serif;font-size: 12px">
                    Load
                    <input type="file" class="tui-image-editor-load-btn">
                </div>

whereas the download button is 
<button class="tui-image-editor-download-btn" style="background-color: #fdba3b;border: 1px solid #fdba3b;color: #fff;font-family: 'Noto Sans', sans-serif;font-size: 12px">
                    Download
                </button>
