### ISSUE TITLE
Suggestion: Non- translatable portions

### ISSUE THREAD

**Issue by markosjal** [nhn/tui.image-editor#188]
Working from Example number 1 included in download 2 days agp

I set up translation to Spanish, except there are parts that do not translate. Specificly when selecting text the "B"  "I"  "U"  (bold italics and underline) icons should be changable . For instance "B" in Spanish should be "N"  and  "I" is "C" , etc

I tried adding"  'B': 'N' "to the translation list, it did not change.

**Comment by junghwan-park** [comment]
@markosjal Sorry, Icons are not translated. These icons are SVG image not a text.

**Comment by markosjal** [comment]
Not changable too easily from what I see .  My suggestion is these should be translatable text!

**Comment by junghwan-park** [comment]
Thank you for your suggestions, and I will bring it up during the next meeting with my team!
