### ISSUE TITLE
Compilation error with webpack 4.30, reactjs 16.8

### ISSUE THREAD

**Issue by RudiX** [nhn/tui.image-editor#190]
## Version
3.5.2

## Development Environment
VS Code, Windows 10 + MaxOSX, ReactJS, 
[...]
devDependencies:
    "@types/react": "^16.8.13",
    "awesome-typescript-loader": "^5.2.1", || "ts-loader": "^5.3.3",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "typescript": "3.2.2",
    "webpack": "^4.30.0",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": "^3.3.1",
[...]
dependencies:
[...]
    "tui-image-editor": "^3.5.2",
[...]

## Current Behavior
index.d.ts line 136 - 155 causing error

```js
interface IGraphicObjectProps {
        id?: number;
        type?: string;
        text?: string;
        left?: string | number;
        top?: string | number;
        width?: string | number;
        height?: string | number;
        fill?: string;
        stroke?: string;
        strokeWidth?: string | number;
        fontFamily?: string;
        fontSize?: number;
        fontStyle?: string;
        fontWeight?: string;
        textAlign?: string;
        textDecoration?: string;
        opacity?: number;
        [propName: string]: number | string | boolean;
 }
```
Error: 
TS2411: Property 'id' of type 'number | undefined' is not assignable to string index type 'string | number | boolean'.
TS2411: Property 'type' of type 'string | undefined' is not assignable to string index type 'string | number | boolean'.
[...] For all interface props

## Expected Behavior
no compilation error, maybe by chaning the last line to:

```js
        [propName: string]: number | string | boolean | undefined;
```

**Comment by jinwoo-kim-nhn** [comment]
수고하셨습니다.
