### ISSUE TITLE
Prevent user to move and resize objects

### ISSUE THREAD

**Issue by Allakazan** [nhn/tui.image-editor#193]
## Version
tui-image-editor@3.5.2 

## Development Environment
Mozilla/5.0 (Linux; Android 8.1.0; Redmi 5 Plus Build/OPM1.171019.019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/73.0.3683.90 Mobile Safari/537.36

## Current Behavior
The user can move and scale objects on screen 

## Expected Behavior
I don't want allow the user move and scale objects

I'm making and  app with vue and cordova for the user paint some images, and that plugin worked as well, but after draw on screen, the user can scale and move the paint objects, i want to prevent that option
I tried to use the objectMoved and objectScaled events and put a 'return false' in the end but didn't worked.

Thanks for the support :)

**Comment by junghwan-park** [comment]
@Allakazan 
How about this? Object could be selectable but scale, move, rotate.

```javascript
var imageEditor = new ImageEditor(/* ... */);

imageEditor.on('addObjectAfter', function(prop){
        imageEditor.setObjectProperties(prop.id, {
                lockMovementX: true,
                lockMovementY: true,
                lockScalingX: true,
                lockScalingY: true,
                lockRotation: true
        });
});
```

**Comment by guillaumegarcia13** [comment]
Didn't see the 'addObjectAfter' event being fired.
I tried with 'iconCreatedEnd' instead but to no avail
![image](https://user-images.githubusercontent.com/2786038/60601970-41ca6200-9db3-11e9-8da5-3cfc4e1fbb52.png)

Still possible to move, rotate, scale
Any idea?
