### ISSUE TITLE
changing the image and using the same canvas object

### ISSUE THREAD

**Issue by alijawadi** [nhn/tui.image-editor#195]
## Version

version 3.5.2
## Development Environment

Version 72.0.3626.121 (Official Build) (64-bit)
Ubuntu 18.04.2 LTS
## Current Behavior

I'm not able to use the same filters I added for an image when I load a new Image.

## Expected Behavior

Is it possible to use the same filters, added text, shapes...etc. on a new loaded picture?
What I'm expecting here is: let's say I'm editing an image then after some changes i decide to use a different image. I want to load a new image and not lose the changes I've made before.
is there a work-around to achieve this?

**Comment by junghwan-park** [comment]
@alijawadi Sorry. Currently, no way to achieve your needs. ImageEditor is built for simple image editing with not changeable single image.
Changing image feature what you wanted is needs to develop. I'll add this feature to next TODO list. Thanks.

**Comment by rChinnnn** [comment]
I modified the tui-image-editor.js, currently I could get all canvas(klass) objects in my Vue project.
Please check the [gif demo](https://i.imgur.com/u1agAAc.gifv).
Could we input these objects into lower-canvas or upper-canvas by any possibility method?
Please give me some directions and suggestions, thanks!
Maybe I can try to develop this needs.
