### ISSUE TITLE
Unable to initialize the image editor with vanilla javascript

### ISSUE THREAD

**Issue by meeshh** [nhn/tui.image-editor#196]
## Version
* tui-image-editor.min.js
* @version 3.5.2

## Development Environment
Chrome, MacOS

## Current Behavior
I am serving the dist files myself and loading them in my dom. Along with the dependencies
I cannot manage to initialize the image editor. I think it is with the selector. anything i should consider? it says :
tui-image-editor.min.js:10 Uncaught TypeError: Cannot read property 'nodeName' of null

i am invoking ImageEditor as follows
```
var imageEditor = new tui.ImageEditor('#tui-image-editor canvas', {
	cssMaxWidth: 1000, // Component default value: 1000
	cssMaxHeight: 800  // Component default value: 800
});		
```

## Expected Behavior
have the editor on my screen.

**Comment by alijawadi** [comment]
### You should provide some data in the `includeUI` key:

```var instance = new ImageEditor(document.querySelector('#tui-image-editor'), {
     includeUI: {
         loadImage: {
             path: 'img/sampleImage.jpg',
             name: 'SampleImage'
         },
         locale: locale_ru_RU, // key-value object with localization
         theme: blackTheme, // or whiteTheme
         initMenu: 'filter',
         menuBarPosition: 'bottom'
     },
    cssMaxWidth: 700,
    cssMaxHeight: 500,
    selectionStyle: {
        cornerSize: 20,
        rotatingPointOffset: 70
    }
});
```
**If this didn't help check the [example](https://github.com/nhn/tui.image-editor/blob/master/docs/Basic-Tutorial.md).**

**Comment by dewshare** [comment]
I am on same issue, my error console showing this 'TypeError: tui.component is undefined' 

Kindly reply

**Comment by 297179121** [comment]
No good example :thumbsdown:
