### ISSUE TITLE
I would love to incorporate this into my project , but 

### ISSUE THREAD

**Issue by markosjal** [nhn/tui.image-editor#197]
I have a project that provides network scanning access on Linux and would love to incorporate this into my project however it seems there are many bugs and they do not get fixed too quickly. 

My project is AirScan http://airscan.teknogeekz.com

This is a scanner app compatible with a half a dozen or so scanners that have poor software support. 

I am just about ready to release Version 10 of Airscan and reallty want to make this work however I am concerned for the following:

No easy method to get image from Canvas to server

Rotate function is unusable.

Bug that does not allow menu to be at top (page loads and you see an image and user may think there is nothing more if they do not scroll down).

Just FYI 

Mark

**Comment by junghwan-park** [comment]
@markosjal 
It will be great to use Image Editor. I'm resolving rotate issue now. But, transfer image to server issue is need discussion with my team. Thanks.

**Comment by aignatov-bio** [comment]
@markosjal you can make save to server in this way:
```
$('.file-save-link').click(function(ev) {
      var imageBlob;
      var imageDataURL;
      var imageParams;
      var dataUpload = new FormData();
      var blobArray;
      var bytePosition;

      imageParams = { format: 'jpeg', quality: 0.9 };
      // ImageEditor variable
      imageDataURL = imageEditor.toDataURL(imageParams);
      imageDataURL = atob(imageDataURL.split(',')[1]);

      blobArray = new Uint8Array(imageDataURL.length);

      for (bytePosition = 0; bytePosition < imageDataURL.length; bytePosition += 1) {
        blobArray[bytePosition] = imageDataURL.charCodeAt(bytePosition);
      }

      imageBlob = new Blob([blobArray]);
      dataUpload.append('image', imageBlob);

      $.ajax({
         type: 'POST',
         url: saveUrl,
         data: dataUpload,
         contentType: false,
         processData: false,
         success: function(res) {
           // Some code
         }
     })
});
```
