### ISSUE TITLE
Cannot add Korean Text in IE11

### ISSUE THREAD

**Issue by MilenaLee** [nhn/tui.image-editor#202]
## Version

version 3.5.1

## Development Environment

IE11 browser / IIS 8.5 server / Django 2.1.4

## Current Behavior

Adding Korean text does not work correctly on IE11.
ex) add "추가", "안녕하세요" but displayed like  "축가", "안녕핫셍요"
I checked http://nhn.github.io/tui.image-editor/latest/tutorial-example01-includeUi on IE11 but same problem appeared. 
I checked X-UA-Compatible(IE=edge -> IE7, 5) and "display: inline-block;" problem(https://www.xpressengine.com/qna/23083326) but it didn't solve the problem.

## Expected Behavior

It shoud run

**Comment by jinwoo-kim-nhn** [comment]
It seems to be fixed in version 3.7.0.
