### ISSUE TITLE
How to handle Crop Event?

### ISSUE THREAD

**Issue by rChinnnn** [nhn/tui.image-editor#204]
## Version
  * @toast-ui/vue-image-editor@1.0.2
  * tui-image-editor@3.5.2

## Development Environment
  * Chrome/74.0.3729.131
  * Vue-Cli3
  * MacOS

## Current Behavior
  * All API methods/events could be achieved in my Vue page.
  * Currently, there is no way for handling Crop event down.
  * I tried to modify vue-image-editor.js about CropAction function, but it isn't worked. It couldn't pass variable or vue-methods to Vue page.

## Expected Behavior
  * I want to do something to server after Cropping image, how to handle Crop Event?

**Comment by junghwan-park** [comment]
@rChinnnn Currently no way to handle crop event. I'll add this to issue #136. Thanks.

**Comment by zhangran25** [comment]
> * All API methods/events could be achieved in my Vue page.

All API methods/events could be achieved in “my Vue page”. Hello, Do u know how to or where to save that , and save in where? What is "my Vue page"? Or where can I find this , which Class which method? Thank u!
