### ISSUE TITLE
TypeError: tui.component is undefined 

### ISSUE THREAD

**Issue by dewshare** [nhn/tui.image-editor#206]
## Version
    tui-image-editor.min.js
    @Version 3.2.0

## Development Environment
Windows 7, Firefox

## Current Behavior
I follow the tutorial, https://github.com/nhn/tui.image-editor/wiki/Basic-Tutorial 

Use following files as well as dependencies

fabric.js >=1.6.7
tui.code-snippet >=1.3.0
tui.color-picker >=2.2.0

When I run on browser, it shows Blank screen, I checked in Error Console, and its giving 'TypeError: tui.component is undefined '

Here is my code
```js
<script src="http://localhost/imageEditor/dist/tui-code-snippet.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="http://localhost/imageEditor/dist/fabric.min.js"></script>
<script src="http://localhost/imageEditor/dist/tui-image-editor.min.js"></script>
<link rel="stylesheet" href="http://localhost/imageEditor/dist/tui-image-editor.min.css">
<script>
 var imageEditor = new tui.component.ImageEditor('#my-image-editor canvas', {
    cssMaxWidth: 1000, // Component default value: 1000
    cssMaxHeight: 800  // Component default value: 800
});
// Load image
imageEditor.loadImageFromURL('jp.jpg', 'My sample image');
</script>
 
<div id="my-image-editor" style="height: 800px">
    <canvas></canvas>
</div>
```

## Expected Behavior
It should run

**Comment by junghwan-park** [comment]
@dewshare 
Sorry, There is outdated API `tui.component.ImageEditor`. It is `tui.ImageEditor` now. And I'm already modified the doc. Thanks.

**Comment by catalin560** [comment]
Met the same error... the docs still aren't updated... the library still doesn't work even after apply the alleged fix... now I get `Uncaught TypeError: (0 , i.sendHostname) is not a function` ...
such a shitty experience even before installing this library...
