### ISSUE TITLE
total canvas memory use exceeds the maximum limit

### ISSUE THREAD

**Issue by huantu284** [nhn/tui.image-editor#208]
## Version

"tui-image-editor": "^3.5.2",
## Development Environment

Ionic3 build iOS APP
## Current Behavior

When I use editor.loadImageFromURL in the iPhone app,the photo loaded at first time,but it didn't loaded another photo next time;
I got the warning "total canvas memory use exceeds the maximum limit"
```js
// Write example code
```

**Comment by junghwan-park** [comment]
I think previous image not destroyed properly. I'll debugging canvas & fabric object in the time when clearing canvas.
