### ISSUE TITLE
Doesn't show menu images

### ISSUE THREAD

**Issue by matthewstidham** [nhn/tui.image-editor#209]
## Version

3.5.2
## Development Environment

Firefox 67.0 on Ubuntu 19.04
## Current Behavior

The buttons on the bottom of the page work, but the images are not found, so they are invisible. It does it if I download it correctly or fetch the example page via wget it still doesn't have the buttons work correctly.

**Comment by junghwan-park** [comment]
@matthewstidham You installed ImageEditor with NPM? Or cloned by Git CLI? Then you should run `npm install`command and, after that, run `npm run bundle:svg` command.

**Comment by matthewstidham** [comment]
I've tried it both ways, and it has the same error using either method. I tried running the command you recommended in the file I downloaded and now the html files under examples show nothing.

**Comment by matthewstidham** [comment]
OK, I cleared all of my previous attempts at getting it to work, and removed my node-modules from my home folder. I then got this error: I ran the npm command using sudo.
`<pre><span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> core-js@2.4.1: core-js@&lt;2.6.6 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.

&gt; tui-image-editor@3.5.2 postinstall /home/matthew/Documents/hieroflux/node_modules/tui-image-editor
&gt; npm install --no-save --no-optional fabric@^1.6.7

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">checkPermissions</font> Missing write access to /home/matthew/Documents/hieroflux/node_modules/tui-image-editor
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">path</font> /home/matthew/Documents/hieroflux/node_modules/tui-image-editor
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> EACCES
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">errno</font> -13
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">syscall</font> access
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Error: EACCES: permission denied, access &apos;/home/matthew/Documents/hieroflux/node_modules/tui-image-editor&apos;
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>  { [Error: EACCES: permission denied, access &apos;/home/matthew/Documents/hieroflux/node_modules/tui-image-editor&apos;]
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>   stack:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>    &apos;Error: EACCES: permission denied, access \&apos;/home/matthew/Documents/hieroflux/node_modules/tui-image-editor\&apos;&apos;,
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>   errno: -13,
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>   code: &apos;EACCES&apos;,
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>   syscall: &apos;access&apos;,
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>   path:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>    &apos;/home/matthew/Documents/hieroflux/node_modules/tui-image-editor&apos; }
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> The operation was rejected by your operating system.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> It is likely you do not have the permissions to access this file as the current user
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> If you believe this might be a permissions issue, please double-check the
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> permissions of the file and its containing directories, or try running
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> the command again as root/Administrator (though this is not recommended).

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>     /home/matthew/.npm/_logs/2019-05-30T17_36_19_671Z-debug.log
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">enoent</font> ENOENT: no such file or directory, open &apos;/home/matthew/Documents/hieroflux/package.json&apos;
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> hieroflux No description
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> hieroflux No repository field.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> hieroflux No README data
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> hieroflux No license field.

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> ELIFECYCLE
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">errno</font> 243
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> tui-image-editor@3.5.2 postinstall: `npm install --no-save --no-optional fabric@^1.6.7`
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Exit status 243
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Failed at the tui-image-editor@3.5.2 postinstall script.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> This is probably not a problem with npm. There is likely additional logging output above.

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>     /home/matthew/.npm/_logs/2019-05-30T17_36_19_802Z-debug.log
</pre>`

**Comment by matthewstidham** [comment]
OK, I downgraded NPM to version 5.3.0, hoping that makes it better. I then ran `npm install` and `npmrun bundle:svg` in the folder where I just forked this repository after removing all my previous attempts. I didn't get any error codes, but when I try to view example01 in the examples folder the page is blank.

**Comment by coderfin** [comment]
I was able to get ToastUI Image Editor working including styles and icons using npm. In a couple of steps here is how I did it within an Angular app using npm, typescript, scss, etc.

https://gist.github.com/coderfin/103d75152f12dad8b0bda3df73189ca9
