### ISSUE TITLE
Id clash in UI - when using multiple editor instances

### ISSUE THREAD

**Issue by henrikekblad** [nhn/tui.image-editor#210]
## Version
3.6.0

## Development Environment
Linux, Vue.js

## Current Behavior
When having multiple instances of the editor open simultaneously, I've noticed the checkboxes uses a none-unique id's (between instances). When I.e. clicking "grayscale" in one instance the grayscale is checked/applied in the other.
 
Screenshot from 2019-05-31 16.33.43
![image](https://user-images.githubusercontent.com/5717075/58713065-20e0ac80-83c2-11e9-96e5-6fe125ffaf61.png)

These hard coded ids:
https://github.com/nhn/tui.image-editor/blob/master/src/js/ui/template/submenu/filter.js#L10

Gets tied up here:
https://github.com/nhn/tui.image-editor/blob/master/src/js/ui/filter.js#L86

Using this document query selector:
https://github.com/nhn/tui.image-editor/blob/master/src/js/ui/submenuBase.js#L16

## Expected Behavior
The correct checkbox to be checked.

**Comment by jinwoo-kim-nhn** [comment]
resolved at 3.7.1
