### ISSUE TITLE
When crop picture the shadow is not correct

### ISSUE THREAD

**Issue by sj279811799** [nhn/tui.image-editor#211]
When crop picture the shadow is not correct.

![image](https://user-images.githubusercontent.com/12233760/58933817-0aa86700-879b-11e9-9b21-2d607879ab1b.png)

**Comment by DaveM2011** [comment]
i am also having the same issue

**Comment by dimakovalevskyi** [comment]
Guys, try to use fabric.js 1.6.7. It helps me

**Comment by VasiliyRusin** [comment]
You really should pay attention to this problem

**Comment by jinwoo-kim-nhn** [comment]
This has been fixed with the release of 3.7.0.
