### ISSUE TITLE
Who uses TOAST UI ImageEditor??

### ISSUE THREAD

**Issue by junghwan-park** [nhn/tui.image-editor#212]
### Do you use TOAST UI ImageEditor in production?
 **Please let us know so we can add you to the [Used By](https://github.com/nhn/tui.image-editor#-used-by) section of the README!**
 
 ![Screen Shot 2019-06-07 at 3 19 04 PM](https://user-images.githubusercontent.com/12269489/59085183-c357dd00-8938-11e9-9054-31b506ea5d6e.png)

 * If you want, feel free to edit the [README.md](https://github.com/nhn/tui.image-editor/blob/master/README.md) file directly and send a PR.
 * Otherwise, Please provide
   
   * The official name of your company/brand/service
   * The link to your official website
   * (optional) The logo image

**Comment by dongsik-yoo** [comment]
[TOAST Dooray! - Collaboration Service (Project, Messenger, Mail, Calendar, Drive, Wiki, Contacts)](https://dooray.com)

**Comment by Fauxil-Fox** [comment]
Very soon, https://catalystapp.co/ will!  We go by just "Catalyst" and our logo is findable at: https://catalystapp.co/img/logo/solid/logo.png

Let me know if you need more information!  As a site centered around art, I'm really loving TOAST's image editor

**Comment by brendon** [comment]
Froala does: https://froala.com/wysiwyg-editor/examples/tui-advanced-image-editor/

:)
