### ISSUE TITLE
Add GitHub release for v3.6.0?

### ISSUE THREAD

**Issue by Fauxil-Fox** [nhn/tui.image-editor#217]
## Version
Latest (GH)

## Development Environment
N/A

## Current Behavior
There is a commit where package.json is updated to 3.6.0, however, the latest tagged commit (GH release) is 3.5.2.

## Expected Behavior
The GitHub and package.json version numbers are up to date

**Comment by junghwan-park** [comment]
@Fauxil-Fox 
Actually, I've tried to release TOAST UI ImageEditor-v3.6.0. And it contains uptate fabric.js to `fabric.js-v2.7.0`.
However, `fabric.js-v2.7.0` has an [issue](https://github.com/fabricjs/fabric.js/issues/5677) with IE10. 
I've already [fixed](https://github.com/fabricjs/fabric.js/issues/5677) that issue but, That change included `fabric.js-v3.1.0`. I'll re-update fabric.js to `fabric.js-v3.2.0 ` and release `ImageEditor-v3.7.0 or higher`.
