### ISSUE TITLE
Propagete usageStatistics flag to colorPicker

### ISSUE THREAD

**Issue by xasx** [nhn/tui.image-editor#220]
## Version
v3.5.2

## Development Environment
various: Windows, Linux, MacOS
Chrome, Firefox

## Current Behavior
The colorPicker component trigger GA calls despite of the image-editor's flag `usageStatistics` has been set to `false`.

This induces a privacy issue

```js
// Probably some more options should be in src/js/ui/tools/colorpicker.js

this.picker = tuiColorPicker.create({
            container: this.pickerElement,
            preset: PICKER_COLOR,
            color: defaultColor
        });

```

## Expected Behavior
If the very top component's `usageStatistics` flag is set to a certain value, especially `false`, sub-components should take that into account by also setting their `usageStatistics` flag to the same value.

**Comment by junghwan-park** [comment]
@xasx Thank you for your report.
