### ISSUE TITLE
Editor saves the Crop handles as part of the new image

### ISSUE THREAD

**Issue by gdespoulain** [nhn/tui.image-editor#224]
Hi!
I noticed something...

## Version
3.5.2

## Development Environment
Linux (Ubuntu), Firefox/Chrome

## Current Behavior
When Crop is used but not applied and you retrieve the result image, the Image Editor saves the Crop handles with the new image, as a part of it:

![unapplied-crop](https://user-images.githubusercontent.com/16285524/60906843-696c6f00-a278-11e9-8530-9cdf7f65792f.png)

FYI I used the function **toDataURL()** from the Editor to ask for the result image:

```js
imageEditor = new tui.ImageEditor('#tui-image-editor-container'. {...})
...
let resultImage = imageEditor.toDataURL();
```

## Expected Behavior
Retrieving the image should either cancel or automatically apply the Crop before saving. Or am I doing something wrong here and should I use another function to obtain the edited binary?

Thanks a lot!

**Comment by GraemeFulton** [comment]
same issue here, pressing save feels like you're saving the crop, but you have to press 'apply' first. I wonder if there's a way to move the apply button, or trigger apply when the save button is clicked
