### ISSUE TITLE
Custom icon

### ISSUE THREAD

**Issue by KrisMerckx** [nhn/tui.image-editor#227]
I can add an SVG-image file via the "custom icon"-button, but it always becomes a black square.

**Comment by pfinkbeiner** [comment]
Any news on this?

**Comment by haiduong87** [comment]
Hello all,
Can you tell me the purpose of:
- Custom Icon
- Mask

Please see this
![image](https://user-images.githubusercontent.com/22165935/114374798-504acd80-9b84-11eb-9bca-4820fb0292c5.png)
- 1 and 2 are marks (add and don't press "Apply")
- 3 is the custom icon

I'm looking for "add a small image into the main image"
- I think it must be "Custom icon", but with this feature the small icon isn't showed as expected
- "Mask": this works perfectly with out pressing "Apply"



Thank you!

Duong Nguyen

**Comment by berejznoy** [comment]
Any news on this?
