### ISSUE TITLE
Draw tool issue #2 - stroke don't applied properly

### ISSUE THREAD

**Issue by onadein** [nhn/tui.image-editor#229]
## Version
3.5.3 and 3.6.0

## Development Environment
Chrome, Windows

## Current Behavior
1. Go to http://nhn.github.io/tui.image-editor/latest/tutorial-example01-includeUi/
2. Select Draw tool.
3. Draw one long stroke (in my example I'm trying to draw one of picture's corner).
4. Press Download.
5. No any changes on the picture!

See screen capture attached.
![draw_tool_issue_2](https://user-images.githubusercontent.com/4040019/61640166-86a43300-aca5-11e9-974e-e4e5dd6eb958.gif)
[draw_tool_issue_2.zip](https://github.com/nhn/tui.image-editor/files/3417853/draw_tool_issue_2.zip)

## Expected Behavior
Changes could be seen on downloaded picture.

**Comment by aldrashan** [comment]
Is the same issue as https://github.com/nhn/tui.image-editor/issues/228 .
Drawn lines in the corner get moved outside of the canvas.
You can see this by drawing something in the center and downloading the image.

**Comment by jinwoo-kim-nhn** [comment]
resolved at 3.7.1
