### ISSUE TITLE
Menu icons do not show

### ISSUE THREAD

**Issue by jesusdelrio** [nhn/tui.image-editor#230]
## Version
tui-image-editor#3.6.1
fabric#1.6.7
tui-code-snippet#1.5.1
tui-color-picker#2.2.3

## Development Environment
Windows 10
node#12.4.0
angular#1.5.8
FF#68.0.1
Chrome#75.0.3770.142

## Current Behavior
It is *impossible* to show the menu icons. Not even with the black-theme.js file modified with the absolute path of the SVG files. 

I think the reason is because the SVG is not properly scanned, because the inner <g> that should show after the <svg> element is missing in ALL of the items from the menu.

This thing is not happening in the demo you have in the website:

`<li id="tie-btn-crop" class="tui-image-editor-item normal" title="Crop">`
`    <svg class="svg_ic-menu">`
`    <use xlink:href="/static/icon-d-4ef3abbd14fbe85ceebf36d900d2c9ad.svg#icon-d-ic-crop" class="normal"></use>`
`#shadow-root (closed)`
**--MISSING--**
`<svg id="icon-d-ic-crop" viewBox="0 0 24 24">`
`<g fill="none" fill-rule="evenodd">`
`<path d="M0 0h24v24H0z"></path>`
`<path fill="#8a8a8a" d="M4 0h1v20a1 1 0 0 1-1-1V0zM20 17h-1V5h1v12zm0 2v5h-1v-5h1z"></path>`
`<path fill="#8a8a8a" d="M5 19h19v1H5zM4.762 4v1H0V4h4.762zM7 4h12a1 1 0 0 1 1 1H7V4z"></path>`
`</g>`
**--MISSING--**
`</svg>
`<use xlink:href="/static/icon-b-d70663d06bd44437c178f522047470cc.svg#icon-b-ic-crop" class="active"></use>`
`<use xlink:href="/static/icon-c-6f440c0d2fa852de523edfd5383ad682.svg#icon-c-ic-crop" class="hover"></use>`
`</svg>`
`</li>`

## Expected Behavior
To show properly the icons.

**Comment by junghwan-park** [comment]
@jesusdelrio 
Have you install ImageEditor via `npm`?
Then, You should add SVGs into your bundle file list. And modify `menu` and `subMenu` properties in `black-theme.js`.

```js
var blackTheme = {
  //...
    // main icons
    'menu.normalIcon.path': '../dist/svg/icon-d.svg', 
    'menu.normalIcon.name': 'icon-d',
    'menu.activeIcon.path': '../dist/svg/icon-b.svg',
    'menu.activeIcon.name': 'icon-b',
    'menu.disabledIcon.path': '../dist/svg/icon-a.svg',
    'menu.disabledIcon.name': 'icon-a',
    'menu.hoverIcon.path': '../dist/svg/icon-c.svg',
    'menu.hoverIcon.name': 'icon-c',
    'menu.iconSize.width': '24px',
    'menu.iconSize.height': '24px',

    // submenu primary color
    'submenu.backgroundColor': '#1e1e1e',
    'submenu.partition.color': '#3c3c3c',

    // submenu icons
    'submenu.normalIcon.path': '../dist/svg/icon-d.svg',
    'submenu.normalIcon.name': 'icon-d',
    'submenu.activeIcon.path': '../dist/svg/icon-c.svg',
    'submenu.activeIcon.name': 'icon-c',
    'submenu.iconSize.width': '32px',
    'submenu.iconSize.height': '32px',
  //...
}
```

ex) `menu.normalIcon.path` should be matched with your environment path `{application server or bundler's static files directory}/icon-d.svg` SVG path.

**Comment by jesusdelrio** [comment]
Hi @junghwan-park !!

Yes, I did modify black-theme.js even with the absolute filepath of the svg icons with no luck.
I installed ImageEditor with bower, because I want to use it in angular.

**Comment by junghwan-park** [comment]
@jesusdelrio
It worked? 
FYI, The `menu.normalIcon.path` is URL path for web browser, not a OS file system's file path.
And you should add these `icon-a.svg`, `icon-b.svg`, `icon-c.svg`, `icon-d.svg` images into your bundler configuration.

**Comment by jesusdelrio** [comment]
Hi!
No, i did not install imageEditor with npm, but with bower. How I am suppossed to add those icons to the bundler configuration? I tried "npm run bundle:svg" but throws an error of "missing script"
I know that menu.normalIcon.path is URL path, but is the desperation of three days stuck with this problem xDDD

**Comment by Super404** [comment]
When the dependency is placed on the react project, the blace theme cannot request. What's the reason that the icon cannot be loaded?

**Comment by coderfin** [comment]
I was able to get ToastUI Image Editor working including styles and icons using npm. In a couple of steps here is how I did it within an Angular app using npm, typescript, scss, etc.

https://gist.github.com/coderfin/103d75152f12dad8b0bda3df73189ca9

**Comment by heroandtn3** [comment]
@coderfin it works! Thanks so much!
