### ISSUE TITLE
Editor 수정내역 디비 연동

### ISSUE THREAD

**Issue by Sanhosa** [nhn/tui.image-editor#232]
1. 에디터에 저장된 내용을 DBMS에 연동하는 방법을 간단히라도 가이드 받고 싶습니다.
   (DB에 저장된 내용을 불러와 에디터에 출력해 주는것 포함)

2. JavaScript 코드 위치는 어디쯤이 기입하는 것이 가장 좋은가요?
   (예 : <body> 하단부 or <head>아래 or 페이지 로딩 후..)

**Comment by junghwan-park** [comment]
1. 서버 및 DBMS쪽 질문이군요. 프론트 엔드 개발에 대한 질문이 아니어서 저희가 가이드 드릴 내용이 없을 것 같습니다.

2. 질문의 배경이 되는 실행 환경은 웹 브라우저이고, JavaScript 코드는 `<script>` 태그, 그리고 HTML 문서에서의 `<script>` 태그의 물리적 위치는 어디가 좋은지를 물어보시는 거라고 이해하고 답변 드리겠습니다. 

- 많은 브라우저에서 사용 가능한 로딩 성능의 최적화를 위해 `<script>`태그는 `<body>` 태그의 하단에 작성하는걸 권장합니다. 
- 자세한 설명은 저희 랩에서 작성한 [코딩 컨벤션 / `CSS는 상단, 자바스크립트는 하단에서 불러온다.`](https://ui.toast.com/fe-guide/ko_HTMLCSS) 및 [안티패턴 / `<script>는 문서 하단에서 포함한다`](https://ui.toast.com/fe-guide/ko_ANTI-PATTERN/)에서 이유를 확인하실 수 있습니다.
