### ISSUE TITLE
Hyperlink to an image

### ISSUE THREAD

**Issue by wnmunhoz** [nhn/tui.image-editor#233]
I created a button to add a PNG image through imageEditor.addImageObject.

I would like to add a link to this image and have not found it as in the documentation at http://nhn.github.io/tui.image-editor/latest/.

Is there a possibility to insert a hyperlink to the image? I want to develop a virtual card app so such functionality is very important.

**Comment by junghwan-park** [comment]
@wnmunhoz 
ImageEditor only for editing image or picture, like composing, filterizing, drawing.
I think adding a hyperlink to image is not a feature of ImageEditor's.

**Comment by wnmunhoz** [comment]
It is not!
But the developers could put this functionality.
It would help a lot.
