### ISSUE TITLE
Saving and loading template

### ISSUE THREAD

**Issue by dilovar-91** [nhn/tui.image-editor#235]
It is possible saving & loading process of editing like photoshop psd file?

**Comment by junghwan-park** [comment]
@dilovar-91 
No, that's impossible.

**Comment by dilovar-91** [comment]
@junghwan-park 
Thank you

**Comment by junghwan-park** [comment]
@dilovar-91 
But, It's feature is under internal review. :)
I'll add that feature to next feature list what you said. Thanks.
