### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by rlinhart** [nhn/tui.image-editor#236]
## Version

Using Version 3.3.2, downloaded today from github (8-6-2019)

## Development Environment

Windows 10 Pro 64-bit, Firefox v68.0.1, Chrome v. 76.0.3809.87

## Current Behavior

Initially, it gave the "tui.ImageEditor is not a constructor" error.

After replacing these:

```
<link type="text/css" href="https://uicdn.toast.com/tui-color-picker/v2.2.3/tui-color-picker.css" rel="stylesheet">
<link type="text/css" href="../dist/tui-image-editor.css" rel="stylesheet">
<script type="text/javascript" src="../dist/tui-image-editor.js"></script>
<script type="text/javascript" src="https://uicdn.toast.com/tui-color-picker/v2.2.3/tui-color-picker.js"></script>
```

with these from the https://ui.toast.com website

```
<link rel="stylesheet" type="text/css" href="https://uicdn.toast.com/tui-color-picker/latest/tui-color-picker.css">
<link rel="stylesheet" href="https://uicdn.toast.com/tui-image-editor/latest/tui-image-editor.css">
<script src="https://uicdn.toast.com/tui-image-editor/latest/tui-image-editor.js"></script>
<script src="https://uicdn.toast.com/tui-color-picker/latest/tui-color-picker.js"></script>
```

I got the editor to come up and I was able to load a file.  Now I get the following errors:

1. When I click on the Tint, Multiply, or Blend checkboxes, I get "Unhandled promise rejection Invalid parameters"
2. When I click on any of the filter checkboxes (Brightness, Noise, Pixelate, COlor, Grayscale, Blur, etc), I get "filters.filter is not a function"

Also, none of the icons at the bottom are showing:

![image](https://user-images.githubusercontent.com/2652904/62542355-9edd8b80-b829-11e9-8b52-b2a5d7164e83.png)

## Expected Behavior

The expected behavior is that an example should work!

**Comment by adem-mekacher** [comment]
I've experienced the same issue today ! 1st example doesn't show at all, the 2nd and 3rd example show but do not work

**Comment by junghwan-park** [comment]
@rlinhart 
Are you downloaded a zip file or cloned?

If you literally "downloaded" a zip from github, You should download `production` [branch](https://github.com/nhn/tui.image-editor/tree/production). The `/dist` directory is only exists where `production` branch.

Or you cloned sources from github repository, You should install dependencies with npm. Run `npm install` and, `npm serve` for development environment. With `npm serve`, You can run current ImageEditor sources to the example page. When menu icons are invisible, run `npm bundle:svg` for menu icon bundling. Refreshing example page required.

And if you want to bundle whole image editor sources, run `npm bundle` command. Then `/dist` directory will be generated.

**Comment by adem-mekacher** [comment]
Hello,

I've cloned the project, I found out that the version before the last one
works fine, so I'll go with that.. Thank you for your help.

My best regards

**Comment by zuacubd** [comment]
Thanks.
Production branch is working perfectly.
