### ISSUE TITLE
Save image after editing in MySQL database and server

### ISSUE THREAD

**Issue by TMWolters** [nhn/tui.image-editor#238]
Hello,
Is there a possibility after the image has been edited via a PHP script to save the image path into the MySQL database and then save the image in a folder on the server?

**Comment by TMWolters** [comment]
Hello, I describe my problem again. Maybe it was not understandable enough.
I would like to say that the image is edited by a TUI Image Editor via a Save button to a PHP script and the script saves the image both in the MySQL database and on the server. Is there a possibility? What I have only found so far is that the picture can only be saved on the server. Can someone please help me with the problem?

**Comment by junghwan-park** [comment]
@TMWolters 
First of all, I think this part of development(MySQL, server development things) is not a Front-End development. And I can't guide you right answer to way what you want. 

As far as I know, MySQL is a database, You should NOT to save file or image file to database. File should stored to file server's storage. And the path of the file and some metadata will be saved into database.

And **TOAST UI ImageEditor** is written by Javascript. You should write some Javascript codes for get Image data from **ImageEditor**. Then using PHP is your choice.

**Comment by TMWolters** [comment]
Hello,
I think you misunderstood that. I just want to write the file path to the database and not the image file. I would like to save the image file on the server. I have only the problem that I do not know exactly how I abrreife the picture to save it on the server and the file path then in the database.
