### ISSUE TITLE
[CDN] Publish new version

### ISSUE THREAD

**Issue by guillaumegarcia13** [nhn/tui.image-editor#240]
Would it be possible to publish the latest versions on the CDN?
As far as I can see, the latest one is v3.5.2

Many thanks in advance.

**Comment by junghwan-park** [comment]
@guillaumegarcia13 Latest version published. Thanks.

**Comment by nao-pon** [comment]
@junghwan-park "https://uicdn.toast.com/tui-image-editor/v3.7.0/tui-image-editor.min.js"is not found on the CDN.

Thanks!

**Comment by junghwan-park** [comment]
@nao-pon How about now?

**Comment by nao-pon** [comment]
@junghwan-park I confirmed that it was accessible without problems. Thank you!
