### ISSUE TITLE
Editor without options and menu, only draw, possible? 

### ISSUE THREAD

**Issue by s5m4** [nhn/tui.image-editor#242]
#180  Version
3.4.0

## Development Environment
Windows 10, Angular 8, Firefox/Chrome/Edge

## Current Behavior
I use tui image editor in my project and it's great! On one part of the page I use it with all the features but in another part I need to use it without any features. I need to open an image and the user should only be able to draw black, freestyle lines with predefined width on the image and then save it. How can I completly remove the menu (except save-button)? When I try to remove the menu items (see code below) I get the error: 

ERROR TypeError: "this.icon is undefined"
    _makeSubMenu         tui-image-editor.js:5333
    Ui                               tui-image-editor.js:5084
    ImageEditor               tui-image-editor.js:715
    initImageEditor          dialog.component.ts:156
    ngOnInit                    dialog.component.ts:132

This is what works: 
```js
initImageEditor() {
        const options = {
          includeUI: {
            loadImage: {
              path: './assets/img/whiteBg_800x600.png',
              name: 'Unterschrift'
            },
            menuBarPosition: 'bottom',
            menu: ['draw', 'icon', 'text', 'filter'],
            initMenu: 'draw',
            locale: this.tui_locale_de
          },
          cssMaxWidth: 800,
          cssMaxHeight: 600,
          usageStatistics: false
        };
    
        const imageEditorInstance = new ImageEditor(document.querySelector('#image-editor-container-signature'), options, this);
```

This is what breaks it:
```js
initImageEditor() {
        const options = {
          includeUI: {
            loadImage: {
              path: './assets/img/whiteBg_800x600.png',
              name: 'Unterschrift'
            },
            menuBarPosition: 'bottom',
            **menu: ['draw'],**
            initMenu: 'draw',
            locale: this.tui_locale_de
          },
          cssMaxWidth: 800,
          cssMaxHeight: 600,
          usageStatistics: false
        };
    
        const imageEditorInstance = new ImageEditor(document.querySelector('#image-editor-container-signature'), options, this);
```

## Expected Behavior
Open image in editor, let user only draw with predefined setting (free draw line, some fixed color) on image, then save. 

Thank you very much for your help! 
Kind regards, 
Stefan

**Comment by junghwan-park** [comment]
@s5m4
Currently, Detailed optioning feature is not supported. 

If you want to use only drawing feature, Build your UI like [Example02-Use API Direct.html](https://github.com/nhn/tui.image-editor/blob/master/examples/example02-useApiDirect.html) page.
And develop JS middle layer for your own UI like [examples/js/service-basic.js](https://github.com/nhn/tui.image-editor/blob/master/examples/js/service-basic.js).
This demo is [examples/Use API Direct(Basic)](http://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect).

I'll discuss detailed featuring options to default UI with my team. Thanks!

**Comment by s5m4** [comment]
@junghwan-park thank you for your response. I solved this in my project like you described and it works. 

have a great day,
stefan
