### ISSUE TITLE
How to get the name of icon using getObjectProperties method?

### ISSUE THREAD

**Issue by gaga0202** [nhn/tui.image-editor#243]
## Version
3.7.0

## Development Environment
macOS Mojave, Firefox/Chrome/Edge

## Current Behavior
How to get the name of the icon? 
using 
``` imageEditor.getObjectProperties(id, 'type'); ```
It always returns 'icon'. How do i get the name of the icon?

## Expected Behavior
get the name of the icon example Arrow or Arrow-2 etc.

**Comment by junghwan-park** [comment]
@gaga0202 
Okay, I'll consider adding icon name to icon object. Thanks.

**Comment by gaga0202** [comment]
> @gaga0202
> Okay, I'll consider adding icon name to icon object. Thanks.

I fixed it for my project. It happens while creating the icon the type is hardcoded to "icon" instead of inheriting the value of type.
