### ISSUE TITLE
이미지를 입력 할때 파일용량을 체크하고 싶습니다.

### ISSUE THREAD

**Issue by nokomoko** [nhn/tui.image-editor#245]
예제와 문서를 찾아봐도 안보여서요.
알려주시면 감사하겠습니다.

**Comment by junghwan-park** [comment]
@nokomoko 
이슈 등록시 본문에 채워져 있는 이슈 템플릿을 다 지우지 마시고, 각 섹션에 대한 내용을 채워주시면 감사하겠습니다.

현재는 불러올 이미지 파일의 용량을 확인하고 있지않습니다.
단, 불러올 이미지 파일이 올바르지 않은 경우(삭제된, 혹은 없는 파일인 경우)에만 에러를 반환하고 있습니다.

**Comment by gy0857478** [comment]
In English please
