### ISSUE TITLE
Issues in Chrome Version 76.0.3809.132 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by sh7dow** [nhn/tui.image-editor#246]
## Version
Latest in site demo : https://ui.toast.com/tui-image-editor/

## Development Environment
MacOs 10.14.6 + Chrome Version 76.0.3809.132 (Official Build)

## Current Behavior
Hi team, 

I have these issues with tui image editor when using latest version of Chrome 
76.0.3809.132 (Official Build) (64-bit)
- Drawing a line to a position, after out focus mouse, the line that I draw moving to another position 
![image](https://user-images.githubusercontent.com/1639657/64577305-7d614980-d36b-11e9-87f7-fe5523d0d568.png)
![image](https://user-images.githubusercontent.com/1639657/64577327-8b16cf00-d36b-11e9-9632-716c2ee9c060.png)

- Can't do anything when in MenuBar Position Top  mode 
![image](https://user-images.githubusercontent.com/1639657/64577404-c6b19900-d36b-11e9-939c-cbfccb24f801.png)

**Comment by syjstc** [comment]
just found `.tui-image-editor-container.top .tui-image-editor-submenu` has `bottom: inherit`, which means 0 (from parent element).

**Comment by sh7dow** [comment]
Thanks @syjstc . That's issue. I've done a workaround for this 
```
 .tui-image-editor-container.top .tui-image-editor-submenu {
        bottom: unset;
    }
```
and It works. thanks for your help!
