### ISSUE TITLE
css issue - angular 8 project

### ISSUE THREAD

**Issue by sergiocalero** [nhn/tui.image-editor#247]
## Development Environment

Windows 10 Enterprise, 64bits. Chrome 76.

It seems I have a css issue when using the component on a angular project.
Here you have a link on github with the project I am using.

https://github.com/sergiocalero/ng-tui-image-editor

I have also uploaded the directory dist generated when building. (npm build)

Maybe the error has to do with the theme I am using.
![image](https://user-images.githubusercontent.com/35838517/65239002-4236e700-dade-11e9-83ee-431f05b42f70.png)

The strange thing is that no error appears on the console (Chrome),

I would appreciate if you could you please tell me what is possible wrong.

Thank you people.

**Comment by sergiocalero** [comment]
I have uploaded into stackblitz, so you can try it.

https://angular-image-editor.stackblitz.io

**Comment by junghwan-park** [comment]
@sergiocalero Did you added ImageEditor CSS?

**Comment by sergiocalero** [comment]
Yes, I finally got it. I move the styles to the main css instead and it worked! thank you anyway.
