### ISSUE TITLE
Example - Use API direct (basic) doesn't work partially.

### ISSUE THREAD

**Issue by seungil-j-park** [nhn/tui.image-editor#250]
## Version

http://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect

## Development Environment

Windows 10, Chrome 77.0.3865.90 (64bit)

## Current Behavior

1. DrawLine - Free Drawing 
Multiple free drawing line don't work correctly.
Previous drawed line is moved wrong point.
![1](https://user-images.githubusercontent.com/12150632/66284048-05058e00-e901-11e9-8be2-e9e8b51d3149.gif)

2. Filter - Sepia2
**runtime error**
service-basic.js:911 Object
example02-useApiDirect.html:1 Uncaught (in promise) Invalid parameters.
Promise.then (async)
applyOrRemoveFilter @ service-basic.js:277
(anonymous) @ service-basic.js:774
dispatch @ jquery.min.js:2
u @ jquery.min.js:2

3. Filter - Remove White
**runtime error**
nhn.github.io/:1 A cookie associated with a cross-site resource at http://toast.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
nhn.github.io/:1 A cookie associated with a cross-site resource at http://cloudflare.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
fabric.js:2156 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
fabric.util.addListener @ fabric.js:2156
addOrRemove @ fabric.js:10940
_initEventListeners @ fabric.js:10921
_initInteractive @ fabric.js:9480
initialize @ fabric.js:9205
klass @ fabric.js:2118
_setCanvasElement @ tui-image-editor.js:11833
Graphics @ tui-image-editor.js:11026
ImageEditor @ tui-image-editor.js:734
(anonymous) @ service-basic.js:100
service-basic.js:911 {oldWidth: 0, oldHeight: 0, newWidth: 1600, newHeight: 1066}
favicon.ico:1 GET http://nhn.github.io/favicon.ico 404 (Not Found)
example02-useApiDirect.html:1 Uncaught (in promise) Invalid parameters.
Promise.then (async)
applyOrRemoveFilter @ service-basic.js:277
(anonymous) @ service-basic.js:790
dispatch @ jquery.min.js:2
u @ jquery.min.js:2

4. Filter - Remove White
it is incorrectly works. Result is black or white all the time.

5. Filter - ColorFilter
it is not working functionally. (Not runtime error)

6. Filter - Tint
**runtime error**
nhn.github.io/:1 A cookie associated with a cross-site resource at http://cloudflare.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
nhn.github.io/:1 A cookie associated with a cross-site resource at http://toast.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
fabric.js:2156 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
fabric.util.addListener @ fabric.js:2156
addOrRemove @ fabric.js:10940
_initEventListeners @ fabric.js:10921
_initInteractive @ fabric.js:9480
initialize @ fabric.js:9205
klass @ fabric.js:2118
_setCanvasElement @ tui-image-editor.js:11833
Graphics @ tui-image-editor.js:11026
ImageEditor @ tui-image-editor.js:734
(anonymous) @ service-basic.js:100
service-basic.js:911 {oldWidth: 0, oldHeight: 0, newWidth: 1600, newHeight: 1066}
favicon.ico:1 GET http://nhn.github.io/favicon.ico 404 (Not Found)
example02-useApiDirect.html:1 Uncaught (in promise) Invalid parameters.
Promise.then (async)
applyOrRemoveFilter @ service-basic.js:277
(anonymous) @ service-basic.js:845
dispatch @ jquery.min.js:2
u @ jquery.min.js:2

7. Filter - Multiply
**runtime error**
nhn.github.io/:1 A cookie associated with a cross-site resource at http://toast.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
tutorial-example02-useApiDirect:1 A cookie associated with a cross-site resource at http://cloudflare.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
fabric.js:2156 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
fabric.util.addListener @ fabric.js:2156
addOrRemove @ fabric.js:10940
_initEventListeners @ fabric.js:10921
_initInteractive @ fabric.js:9480
initialize @ fabric.js:9205
klass @ fabric.js:2118
_setCanvasElement @ tui-image-editor.js:11833
Graphics @ tui-image-editor.js:11026
ImageEditor @ tui-image-editor.js:734
(anonymous) @ service-basic.js:100
service-basic.js:911 {oldWidth: 0, oldHeight: 0, newWidth: 1600, newHeight: 1066}
favicon.ico:1 GET http://nhn.github.io/favicon.ico 404 (Not Found)
example02-useApiDirect.html:1 Uncaught (in promise) Invalid parameters.
Promise.then (async)
applyOrRemoveFilter @ service-basic.js:277
(anonymous) @ service-basic.js:864
dispatch @ jquery.min.js:2
u @ jquery.min.js:2

8. Filter - Blend
**runtime error**
nhn.github.io/:1 A cookie associated with a cross-site resource at http://toast.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
nhn.github.io/:1 A cookie associated with a cross-site resource at http://cloudflare.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
fabric.js:2156 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
fabric.util.addListener @ fabric.js:2156
addOrRemove @ fabric.js:10940
_initEventListeners @ fabric.js:10921
_initInteractive @ fabric.js:9480
initialize @ fabric.js:9205
klass @ fabric.js:2118
_setCanvasElement @ tui-image-editor.js:11833
Graphics @ tui-image-editor.js:11026
ImageEditor @ tui-image-editor.js:734
(anonymous) @ service-basic.js:100
service-basic.js:911 {oldWidth: 0, oldHeight: 0, newWidth: 1600, newHeight: 1066}
favicon.ico:1 GET http://nhn.github.io/favicon.ico 404 (Not Found)
example02-useApiDirect.html:1 Uncaught (in promise) Invalid parameters.
Promise.then (async)
applyOrRemoveFilter @ service-basic.js:277
(anonymous) @ service-basic.js:876
dispatch @ jquery.min.js:2
u @ jquery.min.js:2

Thanks!

**Comment by AlexanderYoo** [comment]
Pretty much most of your mentioned problems happened to me, so I changed the fabric.js version to 1.6.7 and pretty much solved the problems but I think this is just a temporary fix tho.

**Comment by jinwoo-kim-nhn** [comment]
I solved this in version 3.7.0.
