### ISSUE TITLE
IE browser -Unhandled promise rejection Invalid image loaded

### ISSUE THREAD

**Issue by sathishvikkas** [nhn/tui.image-editor#251]
Hi,
I am facing call abort issue while loading image from the service URL in IE browser .Please anyone help to resolve

## Current Behavior

```js
// Write example code
```

**Comment by junghwan-park** [comment]
@sathishvikkas Could you describe the issue more details?
And please follow the issue template guide.

**Comment by sathishvikkas** [comment]
> @sathishvikkas Could you describe the issue more details?
> And please follow the issue template guide.

Hi @junghwan-park ,
Actually i am having service url to load an image inside an editor instead of local folder path
like as http://aaa.com?documentOid=111.

> var imageURL =http://aaa.com?documentOid=111.
> loadImage: {
> 											path: imageURL ,
> 											name: 'SampleImage.png'
> },

While i am calling this service ,getting call abort in IE browser only .Due to this ,the image not loading .Finally got an error 'Invalid Image Loaded' error 

For this issue , let me tried one more solution .It is working fine
i.e, By using $http injector with blob url

> $http.get(imageURL , config).then(function onSuccess(response) {
>     						var blob = response.data;
> 						var fileURL = URL.createObjectURL(blob);
> loadImage: {
> 		path: fileURL ,
>  	    name: 'SampleImage.png'
> },
> 
> });


Thanks for the help:)
