### ISSUE TITLE
TIFF Format not support

### ISSUE THREAD

**Issue by sathishvikkas** [nhn/tui.image-editor#255]
Hi All,
While trying to use TIFF format image for editing , it returns below error

**(index):1 Uncaught (in promise) Invalid image loaded.**

## Current Behavior

```js
// Write example code
```

**Comment by naveenkumarmark** [comment]
HI @sathishvikkas just check if you are able to load and edit the file with specified format in the demo editor.
https://ui.toast.com/tui-image-editor/
