### ISSUE TITLE
Could not draw Icons using icon menu

### ISSUE THREAD

**Issue by naveenkumarmark** [nhn/tui.image-editor#256]
## Version
"@toast-ui/vue-image-editor": "^1.0.2"

## Development Environment
Chrome Version 76.0, Windows 10

## Current Behavior
I am not able to draw icons from icon menu.
![icon](https://user-images.githubusercontent.com/47104086/67080361-b4205000-f1b2-11e9-94bb-0dae3e28bb0a.jpg)

```js
import 'tui-image-editor/dist/tui-image-editor.css'
import ImageEditor from '@toast-ui/vue-image-editor/src/ImageEditor.vue'
export default {
name: 'ToastUI',
components: {
	'image-editor': ImageEditor
},
data () {
const icona = require('tui-image-editor/dist/svg/icon-a.svg')
const iconb = require('tui-image-editor/dist/svg/icon-b.svg')
const iconc = require('tui-image-editor/dist/svg/icon-c.svg')
const icond = require('tui-image-editor/dist/svg/icon-d.svg')
var whiteTheme = {
'menu.normalIcon.path': icond,
'menu.activeIcon.path': iconb,
'menu.disabledIcon.path': icona,
'menu.hoverIcon.path': iconc,
'submenu.normalIcon.path': icond,
'submenu.activeIcon.path': iconb,
'common.bi.image': 'https://uicdn.toast.com/toastui/img/tui-image-editor-bi.png',
'common.bisize.width': '251px',
'common.bisize.height': '21px',
'common.backgroundImage': './img/bg.png',
'common.backgroundColor': '#fff',
'common.border': '1px solid #c1c1c1'
}
return {
useDefaultUI: true,
options: {
includeUI: {
  loadImage: {
	path: '',
	name: ''
  },
  theme: whiteTheme,
  initMenu: '',
  menuBarPosition: 'bottom',
  menu: ['crop', 'flip', 'rotate', 'draw', 'shape', 'icon', 'text', 'mask','filter'] //, 'filter',
},
cssMaxWidth: document.documentElement.clientWidth,
cssMaxHeight: document.documentElement.clientHeight,
}
}
}
}
```

## Expected Behavior
Able to draw icons from icon menu list

**Comment by nguyenleminhdev** [comment]
same issues

**Comment by naveenkumarmark** [comment]
Hi @nguyenleminhdev,
If you set `initMenu: 'icon'` able to draw icons.
But this will not solve the problem

**Comment by junghwan-park** [comment]
@naveenkumarmark 
Your question is related with drawing icon into canvas area?
Then, you should draw icon with mouse click & drag.
![icon-draw](https://user-images.githubusercontent.com/7088720/68447392-21a82500-0223-11ea-9fc0-527d7f5b4f46.gif)

If not, I'm not understand what you want.
Could you describe more details with what you want?

PS. 
Are you using webpack? The code what you wrote above.
```js
const icona = require('tui-image-editor/dist/svg/icon-a.svg')
```
With webpack, webpack transform the code `icona` variable's value with path string of your file system's directory `./node_modules/tui-image-editor/dist/svg/icon-a.svg`.
And you should notice that is equal to your web server that runs your Vue application.
After you deploy your app to your own web server. Your application request image file with that relative path `https://your.app.com/node_modules/tui-image-editor/dist/svg/icon-a.svg`.
