### ISSUE TITLE
이미지 수정시 에대한 CSS 질문

### ISSUE THREAD

**Issue by AlexanderYoo** [nhn/tui.image-editor#259]
수고하십니다. 
다름이 아니라 이미지 수정시에 도형등을 클릭하면 수정할 수 있는 점이 
흰색이라 보기 힘들어 색을 바꾸고 싶은데요 이것저것 바꿔봐도 변화가 
없어서 무엇을 건드려야 하는지 알수 있을까요?

**Comment by junghwan-park** [comment]
@AlexanderYoo  

You can define `options.selectionStyle` Javascript object into constructor's second argument [`options` object](http://nhn.github.io/tui.image-editor/latest/ImageEditor). Not a CSS.

![image](https://user-images.githubusercontent.com/7088720/67533814-4ae69280-f706-11e9-83fe-70202cda10e7.png)

```js
var ImageEditor = require('tui-image-editor');
var instance = new ImageEditor(document.querySelector('#tui-image-editor'), {
  includeUI: {
    loadImage: {
      path: 'img/sampleImage.jpg',
      name: 'SampleImage'
    },
  selectionStyle: {
    cornerSize: 9,
    cornerColor: 'red',
    cornerStrokeColor: 'white', // or hex-color like "#ffffff" or "#555555"
    borderColor: '#125de6'
    rotatingPointOffset: 70,

  }
});
```

**Comment by AlexanderYoo** [comment]
Thank you!!!
