### ISSUE TITLE
 Text changes position after adding mark image

### ISSUE THREAD

**Issue by nguyenleminhdev** [nhn/tui.image-editor#260]
## Version

latest
## Development Environment

on https://ui.toast.com/tui-image-editor/
## Current Behavior

Please watch my screen record
https://youtu.be/RIRcwibiZGY
```js
// Write example code
```

## Expected Behavior

When i add image mark, after text, my text has been changed position

**Comment by ngodongdacc** [comment]
Same issue

**Comment by tungtouch** [comment]
@hiaux0 bro pls check it ! thanks

**Comment by hiaux0** [comment]
I tested previous versions:

### 3.6.1 
Bug got introduced
![out](https://user-images.githubusercontent.com/30693990/68210969-efa28300-ffd6-11e9-80e8-a5eeb0eed0bf.gif)


### 3.5.2
Works as expected
![out](https://user-images.githubusercontent.com/30693990/68210890-cda90080-ffd6-11e9-892c-b91876ef00b0.gif)

**Comment by jinwoo-kim-nhn** [comment]
resolved at 3.7.1
