### ISSUE TITLE
Text edit mode in mobile

### ISSUE THREAD

**Issue by joseduin** [nhn/tui.image-editor#262]
##  Version
3.7.0

## Development Environment
Mobile

## Current Behavior
When I finish editing a text, the text does not exit the editing mode when I click outside the text
<img width="455" alt="Captura de Pantalla 2019-10-31 a la(s) 13 53 08" src="https://user-images.githubusercontent.com/19161796/67968268-d3bd6c80-fbe5-11e9-84cd-2085dda34a09.png">

## Expected Behavior
The text should leave the edit mode, it seems an error with the click event

## Alternative solution

We must force the 'blur' event of textarea when we detect that we enter the edit mode

```js
imageEditor.on({
      textEditing: () => { this._editing = true; },
      mousedown: (event, originPointer) => {
      if (this._editing) {
        var textarea = document.querySelector('textarea.tui-image-eidtor-textarea');
        this.renderer.invokeElementMethod(textarea, 'blur', []); // force 'blur'
        this._editing = false;
      }
       },
    });
```

**Comment by junghwan-park** [comment]
@joseduin  Thank you for reporting. I'll fix this next release.

**Comment by av-k** [comment]
Hi @junghwan-park!
Any updates?
What the priority of that issue?
