### ISSUE TITLE
Undo does not clear marker and redo adds another mark

### ISSUE THREAD

**Issue by hiaux0** [nhn/tui.image-editor#264]
## Version

Current demo: https://ui.toast.com/tui-image-editor/

## Development Environment

MacOS 10.13.6
Firefox 70
Online demo: https://ui.toast.com/tui-image-editor/

## Current Behavior

![out](https://user-images.githubusercontent.com/30693990/68035558-2f5e2780-fcc4-11e9-88d4-583277e1f388.gif)
- Undo does not clear marker
- and redo adds another mark
Maybe related to #260 

## Expected Behavior

- undo clears mark
- redo readds the mark

**Comment by tungtouch** [comment]
many bugs ^^

**Comment by hiaux0** [comment]
I tested previous versions:

### 3.6.1 
Has bug, but no second marker
![out](https://user-images.githubusercontent.com/30693990/68210495-f41a6c00-ffd5-11e9-928c-eb5cc30a99d6.gif)

### 3.5.2
Works as expected
![out](https://user-images.githubusercontent.com/30693990/68210689-596e5d00-ffd6-11e9-9171-200cc880c6af.gif)

**Comment by jinwoo-kim-nhn** [comment]
This bug was corrected in version 3.7.0.
