### ISSUE TITLE
Trying to change menu name(Locale)

### ISSUE THREAD

**Issue by AlexanderYoo** [nhn/tui.image-editor#266]
## Version

Current
## Development Environment

Chrome, Win10, Spring(egovernment)
## Current Behavior

```js
// Write example code
```
var locale_kor_KOR = {
            		'Redo': '다시 실행',
            		'Undo': '취소',
            		'Delete': '삭제',
            		'Delete-all': '모두 삭제',
            		'Draw': '그리기',
            		'Shape': '도형 삽입',
            		'Icon': '아이콘 삽입',
            		'Text': '글자 입력'
## Expected Behavior

'Redo': '다시 실행',
'Undo': '취소',
'Delete': '삭제',
'Delete-all': '모두 삭제',

Wouldn't show up tool tip like Draw, Shape and etc.

Also how do I change menu names in the detail menu?

Your API document didn't clearly show any examples of it nor 
any clear explanations, so it would be great to know

Thank you.

**Comment by sathishvikkas** [comment]
@AlexanderYoo : I believe that currently there is no option to show tooltip for all icons with localized data . For that let me provided customized solution using jquery while rendering an image editor

### **Solution :**

`var locale_kor_KOR = '{ "undo":"다시 실행", "redo":"취소", "delete":"삭제", "delete-all" :"모두 삭제","draw": "그리기","shape": "도형 삽입","icon": "아이콘 삽입","text": "글자 입력"}';
						JSON.parse(locale_kor_KOR, function (key, value) {
							var buttonKey = '#tie-btn-' + key;							
							if($(buttonKey).length > 0) {
								$(buttonKey).attr('tooltip-content',value);
							}
						});`

**I hope this will help you
Thank You**

**Comment by junghwan-park** [comment]
@AlexanderYoo
I found these button's tooltip is missing. I'll add the button's tooltip next release. Thx.

**Comment by sathishvikkas** [comment]
Thank you @junghwan-park
