### ISSUE TITLE
Dragging a cropzone to the edge of an image not handled correctly by objectMoved event or the getCropzoneRect() method

### ISSUE THREAD

**Issue by stringfold** [nhn/tui.image-editor#269]
## Version

3.7.0
## Development Environment

Chrome Version 77.0.3865.120 (Official Build) (64-bit) on Windows 10

## Current Behavior

I am using the image editor in a WordPress theme creation tool, and was adding a widget to my UI to display the current cropzone position and size to assist the user in cropping the image to the size they want, but neither the **objectMoved** event nor the **getCropzoneRect()** report the correct position for the cropzone.

To reproduce:

Enter cropping mode in the editor and drag the cropzone to the top or left edge of the image, then keep dragging.

The cropzone cannot be visibly dragged beyond the top or left edge of the image, so the entire cropzone remains inside the bounds of the image. This is the correct behavior.

But if you have an event listener listening to the **objectMoved** event, the **left** and **top** properties of the event are inconsistent with the visible position of the cropzone if you keep dragging after reaching any of the edges, and thus report the wrong position of the object. For example, if you drag the cropzone to the left edge, the **left** event property will go negative.

Worse, if you call **getCropzoneRect()** as the user is dragging against the top or left edges, **Cropzone.isValid()** method returns false, because **top** and/or **left** are negative, and **getCropzoneRect()** returns **null**.

This is especially problematic because the user can be sliding the cropzone along the top or left edge of the image, changing it's position, and you cannot use **getCropzoneRect()** to get the true position of the cropzone.

The same problem occurs when you're resizing the cropzone with the top or left side and you drag to the edge of the image.

## Expected Behavior

The correct behavior is for the **objectMoved** event properties to report the true position of the cropzone object at all times. The adjustments that prevent the user from dragging the cropzone outsize the image should be applied to the event's property values **left** and **top**. The event should not be fired at all if the adjusted position of the cropzone doesn't change.

Fixing the **objectMoved** event for the cropzone should also fix the **getCropzoneRect()** method, since top and left will never be less than zero.

**Comment by jinwoo-kim-nhn** [comment]
ok #270

**Comment by stringfold** [comment]
Not really. 
#269 is a bug, #270 is a suggestion for an enhancement. Of course, if you want to handle both issues at the same time, that's fine with me :)
