### ISSUE TITLE
Add support for setCropzoneRect to take a rectangle as a parameter

### ISSUE THREAD

**Issue by stringfold** [nhn/tui.image-editor#270]
## Version

3.7.0
## Development Environment

Latest Chrome version on Windows 10
## Current Behavior

Currently the API setCropzoneRect only takes a single number -- a ratio -- as a parameter, which both limits the API's usefulness and doesn't match the functionality of getCropzoneRect which actually returns the cropzone rectangle.

## Expected Behavior

It would be very useful to be able to pass in a rectangle object { left, top, width, height } as an alternative to the ratio. Not only would it allow the editor to specify an exact custom cropzone, but it would allow the possibility of adding numeric input controls to the UI to change the size and position of the cropzone with greater accuracy.

An example usecase is when cropping a set of images to the same size for use in a slideshow or as rotating images in a website header. For example, if I want the image to be exactly 300px high, it's hard to do that when dragging the cropzone with a mouse. Keyboard operated input controls provide greater accuracy, but cannot be provided unless there is a way to set the cropzone easily.

Thanks for all the work you have put into this project.

**Comment by jinwoo-kim-nhn** [comment]
Good idea. We'll consider adding features as we improve.
