### ISSUE TITLE
Black background 

### ISSUE THREAD

**Issue by Hugol4ever** [nhn/tui.image-editor#271]
## Version

3.7.0
## Development Environment

JavaScript
## Current Behavior

When I try to get the edited image I got an image that has black background (not edited image)
```js
// Write example code
imageEditor.toDataURL();
```

## Expected Behavior

I want to get the edited image insted of a black background image.

**Comment by jinwoo-kim-nhn** [comment]
Sorry, I don't know exactly what the situation is.

You can use 'codepen.io' or write a more specific example.
