### ISSUE TITLE
File size increased as huge

### ISSUE THREAD

**Issue by sathishvikkas** [nhn/tui.image-editor#278]
Hi,
I found one observation after edit an image as mentioned in the below.

At initially the selected image file size is **"123 KB"**. After applied any changes or with out any changes then click download button means the file size will be increased upto **"510KB"**.  Please assist me on this.

Thanks in advance.
Sathish 

## Current Behavior

```js
// Write example code
```

**Comment by jinwoo-kim-nhn** [comment]
The download function was implemented using the 'toDataURL API' of the web library library 'fabricjs'.

While the image is being saved, the file size may change slightly when new image information is added or updated in the image file header.

The file size increase after editing the image appears to naturally increase as new visual information is added to the image.

If you need to optimize the file size, you can use a tool like Photoshop to save the file size on the web to reduce the file size.

**Comment by ijunaid8989** [comment]
There is still no way of decreasing size of Editor side?
