### ISSUE TITLE
Icon color

### ISSUE THREAD

**Issue by enigma969** [nhn/tui.image-editor#279]
Hi, 

I integrated the image editor using via npm and everything works fine, except the icon colors at the bottom of the editor. 

How can I change the color of the icons? Why is the entire menu just black? 

![image](https://user-images.githubusercontent.com/10528385/69808301-7c5feb80-11e7-11ea-9513-340534ca5f73.png)

`self.editor = new ImageEditor(document.querySelector('#tui-image-editor'), {
                includeUI: {
                    loadImage: {
                        path: self.documentUrl,
                        name: 'SampleImage'
                    },
                    menuBarPosition: 'bottom'
                },
                cssMaxHeight: 800
            });`

**Comment by jinwoo-kim-nhn** [comment]
The theme file in the example code uses a built icon file.

Run `npm build` once and the build file will be in your `dist`  directory.
![스크린샷 2019-11-29 오전 10 38 18](https://user-images.githubusercontent.com/35218826/69837932-868bf380-1294-11ea-98ad-ce2be47aae13.png)

**Comment by enigma969** [comment]
Sorry but there is no change after running `npm build`. 

I installed the library using `npm`. It's available in `node_modules`. 

I really can't follow.

**Comment by jinwoo-kim-nhn** [comment]
Have you tested with your local development server with `npm serve`?

**Comment by jinwoo-kim-nhn** [comment]
Sorry. There was a mistake in the description.

~~`npm build`~~ -> `npm bundle`

**Comment by enigma969** [comment]
Hi, unfortunately I don't have `npm build` and cannot upgrade. Is there a way to get just the svg-files where I can change the color and include static?

**Comment by jinwoo-kim-nhn** [comment]
@engma969

Sorry I'm wrong again. It's not ~~`npm bundle`~~ but `npm run bundle`.

**Comment by enigma969** [comment]
I'll take a try, thanks.
 
But I don't understand why the **default** styling/theme is so bad? 

I would be happy if I get a styling/theme like here: 

https://user-images.githubusercontent.com/35218826/41647896-7b218ae0-74b2-11e8-90db-d7805cc23e8c.gif

But the icons are the same color as the background, so you can't see them.

**Comment by junghwan-park** [comment]
@enigma969 
The gif image that you linked is ImageEditor's **default** theme. Icons of ImageEditor are `SVG image` that bundled via `npm run bundle` command.  I think you doesn't run `npm run bundle`. You should run that command in your repository.

**Comment by coderfin** [comment]
I am also experiencing this issue.  Did anyone find a solution?

**Comment by coderfin** [comment]
I was able to get ToastUI Image Editor working including styles and icons using npm. In a couple of steps here is how I did it within an Angular app using npm, typescript, scss, etc.

https://gist.github.com/coderfin/103d75152f12dad8b0bda3df73189ca9
