### ISSUE TITLE
¿How to clear the canvas?

### ISSUE THREAD

**Issue by PabloRoldanCRM** [nhn/tui.image-editor#283]
Hi, please I ask for help it's not an issue but how to clear(all data, objects, the image loaded) from canvas? like press a button.
first, I thought to  use something like this 

imageEditor.loadImageFromURL("NULL", "SampleImage").then(() => {
        imageEditor.clearUndoStack();
    });

so it would not find the path and erase all.. but it messes the canvas...
so then there is a method .destroy(). should I use that and then instantiate again the object imageEditor? Thanks :)

**Comment by junghwan-park** [comment]
@PabloRoldanCRM 
Use [imageEditor.clearObjects() API](http://nhn.github.io/tui.image-editor/latest/ImageEditor#clearObjects) with `imageEditor.clearUndoStack()`.
As you can see, `clearUndoStack()` API is clearing undoStack to empty array. If you want to Initiate and clear canvas, call `clearObjects()` , `clearUndoStack()` and `clearRedoStack()` all.

**Comment by PabloRoldanCRM** [comment]
Hi, Thanks Mr. @junghwan-park . I wrapped this in a function and call it with button click.
imageEditor.clearObjects();
imageEditor.clearUndoStack();
imageEditor.clearRedoStack();
but the loaded image remains. I mean when you click this button.
![image](https://user-images.githubusercontent.com/23132861/70737937-489dbf00-1cd9-11ea-8625-b4e11e3b52aa.png)

**Comment by eomttt** [comment]
how to clear image??
