### ISSUE TITLE
Rotation Event

### ISSUE THREAD

**Issue by rajaunleashed** [nhn/tui.image-editor#285]
## Version
/*!
 * tui-image-editor.js
 * @version 3.7.2
 * @author NHN FE Development Lab <dl_javascript@nhn.com>
 * @license MIT
 */

## Development Environment
Chrome, Windows 10

What is the event for rotate text? I want to get angle when rotate text. Can someone help me in this regard.

Thanks in advance.

**Comment by jinwoo-kim-nhn** [comment]
There is currently no way.
I think this part will be useful. Let's take a closer look at the fabric's capabilities and see if we can improve it.
