### ISSUE TITLE
TUI image editor doesn't work in OSX El Capitan 

### ISSUE THREAD

**Issue by dejansabados** [nhn/tui.image-editor#289]
#180  Version
3.7.2
## Development Environment
OSX El Capitan Safari 
## Current Behavior
The editor doesn't work in OSX El Capitan - shows a white screen.
Tested in Safari 9.1 , also in Safari 11.1.2
https://www.browserstack.com/screenshots/eb11a46c69baeb878ea8fa05eb1fd705d2c80a79

**Comment by jinwoo-kim-nhn** [comment]
We have confirmed this to be a problem in safari9. But in safari11 it works fine.
First of all, safari9 is too old, so I think you should update it.
In earlier versions, testing and debugging are currently very difficult and will be done at a lower priority.

**Comment by jinwoo-kim-nhn** [comment]
We decided not to support safari9. I will close the issue.

Browsers except IE support only the latest version.
