### ISSUE TITLE
Mosaic and Zoom

### ISSUE THREAD

**Issue by Dolov** [nhn/tui.image-editor#290]
## Current Behavior

hello, this is a great imageEditor, i use it in my project,  but my boss want Mosaic and Zoom feature, i try but fail. so i want to ask if you have plan to add these feature.

**Comment by jinwoo-kim-nhn** [comment]
I'm not sure what the mosaic feature is. A little explanation would help you decide.

**Comment by Nomia** [comment]
How about the zoom feature @jinwoo-kim-nhn ? Will the zoom feature on repo's feature list?

**Comment by cocoroise** [comment]
> How about the zoom feature @jinwoo-kim-nhn ? Will the zoom feature on repo's feature list?

well,you can add this code in 'graphics.js'
but in other tools like `crop`,you may need to use `canvas.setZoom(1)` to reset the zoom ratio.
````javascript
_onMouseWheel(fEvent) {
        const delta = fEvent.e.deltaY / 1000;
        let zoom = this._canvas.getZoom();

        zoom = zoom - delta;
        if (zoom >= 5) {
            zoom = 5;
        }
        if (zoom <= 1) {
            zoom = 1;
        }
        this._canvas.setZoom(zoom);

        this._canvas.calcViewportBoundaries();
        fEvent.e.preventDefault();
        fEvent.e.stopPropagation();
    }
````

**Comment by Nomia** [comment]
@cocoroise thanks for the guide code and file. 

here is a demo of fabric canvas that demonstrate `zoom in` `zoom out` on `mousewheel`
http://fabricjs.com/fabric-intro-part-5

by combining the `hammer.js` touch gesture library, you might implement `zoom in` `zoom out` on `pinch` on mobile device
http://hammerjs.github.io/

hope it helps

**Comment by mokraemer** [comment]
would be nice to have two buttons integrated for zoom in/out

**Comment by sabinayakc** [comment]
I created a [Fork](https://github.com/sabinayakc/tui.image-editor) to address Zoom and Pan issue for myself .

**Comment by hututuhu** [comment]
> @cocoroise thanks for the guide code and file.
> 
> here is a demo of fabric canvas that demonstrate `zoom in` `zoom out` on `mousewheel` http://fabricjs.com/fabric-intro-part-5
> 
> by combining the `hammer.js` touch gesture library, you might implement `zoom in` `zoom out` on `pinch` on mobile device http://hammerjs.github.io/
> 
> hope it helps

thanks, it works for me!
