### ISSUE TITLE
Can't able to create a Custom Download button.

### ISSUE THREAD

**Issue by Navin-vis** [nhn/tui.image-editor#302]
Hi, 
Can you help me with the save image after editing from the editor. and how can i replace the download btn with customise  btn in angular 8. 
I am using this.
 "ngx-tui-image-editor": "^7.0.2",
I attached the screenshot for detail.
![scheduly](https://user-images.githubusercontent.com/58224142/72541072-e3288980-38a7-11ea-8e65-3ccb7458372b.jpg)

Thanks.

**Comment by jinwoo-kim-nhn** [comment]
`ngx-tui-image-editor` is an external code that we don't officially support, so I don't know exactly. As far as I know there are two ways to change this.

1. You can change the style by changing the theme.
  * https://github.com/nhn/tui.image-editor/blob/master/examples/example01-includeUi.html
  * https://github.com/nhn/tui.image-editor/blob/master/examples/js/theme/black-theme.js

2. Alternatively, you can create your own using the `toDataURL api` of the imageEditor instance.
  * https://nhn.github.io/tui.image-editor/latest/ImageEditor#toDataURL

**Comment by Navin-vis** [comment]
Hi,
Yes I find the toDataURL api but i am not able to change the text of "download" to save and also i am not able to find the event when i am clicking the download button.

Thanks.
