### ISSUE TITLE
How to undo all the changes in single click.

### ISSUE THREAD

**Issue by shadabahmad11** [nhn/tui.image-editor#303]
## Version 
v3.6.0

## Development Environment 
chrome

## Current Behavior
http://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect
Multiple click requires to undo all the changes.
How to undo all the changes in a single click.

```js
// Write example code
```

## Expected Behavior
Undo all the changes in a single click.

**Comment by junghwan-park** [comment]
@shadabahmad11 
This example not support clear state button. I think you should add 'Clear state button' to extends this example.
