### ISSUE TITLE
Is installing file-saver needed to enable download button?

### ISSUE THREAD

**Issue by ryuckel** [nhn/tui.image-editor#318]
## Version
tui-image-editor@3.3.1

## Development Environment
macOS/chrome/vue.js 2.5.10

## Current Behavior
when i click Download Button, image displays other tab.
After added file-saver by npm install command and import this module to component using tui-image-editor,
I can download image to local as I expected.

Is it correct way to enable download feature?
If my understanding is not right, please give me a procedure of import file-saver

**Comment by jinwoo-kim-nhn** [comment]
hi @ryuckel 
I'm sorry that this part is not documented.
Need to improve in a more general way. But before that like below:

To download as a file, you can use [fileSaver] (https://www.npmjs.com/package/file-saver/v/1.3.2) together or implement `window.saveAs`.

**Comment by ryuckel** [comment]
@jinwoo-kim-nhn 
Thank you for your reply.
I got it. And I will make PR about this.

**Comment by jinwoo-kim-nhn** [comment]
@ryuckel thanks. good i like you
