### ISSUE TITLE
Saved image contains grid lines

### ISSUE THREAD

**Issue by dejanmartinovic** [nhn/tui.image-editor#321]
## Version
3.2.2

## Development Environment
Windows 10, Chrome 79, Froala Editor 3.1.0

## Current Behavior
When I crop an image and press the Save button without pressing the Apply, the image contains grid lines. Maybe this screen recording could help:
![73686659-b4dce380-46c8-11ea-90d7-811cfa70ad5d](https://user-images.githubusercontent.com/51322189/73731767-5ef45400-4739-11ea-8f7a-0cb6035bff7b.gif)

 
```js
https://jsfiddle.net/dejan_m/71be3Ltu/16/
```

## Expected Behavior
After pressing the Save button, the image should be restored. Thanks

**Comment by jinwoo-kim-nhn** [comment]
@dejanmartinovic 
Please check it has been fixed in 2.7.3.

**Comment by dejanmartinovic** [comment]
My apologies for the delay. I cannot integrate 3.7.3 in Froala Editor. Maybe I did something wrong. Please take a look at this fiddle: https://jsfiddle.net/dejan_m/71be3Ltu/24/. Thanks in advance!

**Comment by dejanmartinovic** [comment]
Hi guys. Any update on this? :)
