### ISSUE TITLE
Unknown erorr coming up every time i load the page  

### ISSUE THREAD

**Issue by Navin-vis** [nhn/tui.image-editor#324]
Hi, 
I am using "ngx-tui-image-editor": "^7.0.2", and every thing is working good except when i reload the page or start the app it shows can not read foreach of undefined can you help me with this.
I attached a screenshot.
![schedule_issue](https://user-images.githubusercontent.com/58224142/73912735-46bc3a80-48db-11ea-84a6-52fee0565c8e.jpg)

Thanks.

**Comment by jinwoo-kim-nhn** [comment]
hi @Navin-vis 
The image editor uses [`tui.code-snippet`](https://github.com/nhn/tui.code-snippet) together as a dependency module.

Working with the example will help.
* https://github.com/nhn/tui.image-editor/blob/master/examples/example01-includeUi.html#L20

**Comment by Navin-vis** [comment]
Hi,
It worked.
Now i am closing the issue.
Thanks.
