### ISSUE TITLE
Unmaintained dependency: core-js@2 needs updating to @3+

### ISSUE THREAD

**Issue by sigma-technology** [nhn/tui.image-editor#328]
## Version

3.7.3

## Development Environment

Windows 10 x64 / npm 6.9 / yarn 1.22.0

## Current Behavior

When adding this package using npm/yarn, the following warning is displayed:

`warning tui-image-editor > core-js@2.4.1: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.`

## Expected Behavior

Use core-js@3+ instead of 2.4.1, which is no longer maintained.

Thank you for creating and maintaining this excellent project.

**Comment by jinwoo-kim-nhn** [comment]
I'll check and update.
