### ISSUE TITLE
How do I upload multiple files?

### ISSUE THREAD

**Issue by Flare-k** [nhn/tui.image-editor#329]
### I'd like to upload and edit more than one file. What should I do?
안녕하세요! 오픈소스 정말 잘 이용하고 있습니다^^ 
다름이 아니라 제가 파일을 2개 이상으로 업로드하여 작업을 하고 싶은데, 해당 에디터는 단일 파일만 업로드 되고있습니다. 혹시 코드 수정을 통해 2개 이상으로 업로드가 가능하다면 어느 부분을 수정하면 좋을 지 알고싶습니다.
감사합니다.

**Comment by jinwoo-kim-nhn** [comment]
hi, @Flare-k 

The implementation principle is implemented by specifying the upload image as the background image of the canvas.

Currently it doesn't work because I don't have the ability to specify two backgrounds in one instance (canvas).

In conclusion, we do not currently support this feature.
