### ISSUE TITLE
Make Icon Arrow to narrow

### ISSUE THREAD

**Issue by Anjali-Bansal** [nhn/tui.image-editor#33]
Hi,

When I add default Arrow icon , its size is quite huge. I've tried multiple methods to reduce its height and width , including the height/width of brush. But its not impacting. As fas as I could see it is plotted via a pathMap:

Arrow: 'M 0 90 H 105 V 120 L 160 60 L 105 0 V 30 H 0 Z',

I am not able to understand its structure in terms of height..Can you please manipulate it with a narrow icon ,I mean that may look like thinner arrow.

Thanks!
Anjali Bansal

**Comment by junghwan-park** [comment]
@Anjali-Bansal 
As you know, Icon is a svg path. Just scaling the icon's dimension(width, height) only.

But, You can add custom icon by [registerIcon() API](https://nhnent.github.io/tui.image-editor/latest/ImageEditor.html#registerIcons).
```js
imageEditorInstance.registerIcon({
  yourArrow: 'Here comes the paths.'
});
```

And add that icon by [addIcon() API](https://nhnent.github.io/tui.image-editor/latest/ImageEditor.html#addIcon)

```js
imageEditorInstance.addIcon('yourIcon', {
  fill: '#000000',
  top: 100,
  left: 100
});
```

**Comment by PabloRoldanCRM** [comment]
Or you can play with the scale... 👌
imageEditor.addIcon('cancel2',{scaleX:[number],scaleY:[number]})
