### ISSUE TITLE
export import error(commonjs and es6)

### ISSUE THREAD

**Issue by pjw9195** [nhn/tui.image-editor#336]
tui-image-editor 커스텀하고싶어서 변경하려는 데
commonJs 랑 es6문법이랑 겹쳐서 export import에서 문제가 생기는데 이를 해결하려면 어떻게 해야하나요??
하나하나 다 바꿔줘야 하는건가요??

이 글도 보고왔습니다.
https://ui.toast.com/weekly-pick/ko_20190418/

**Comment by junghwan-park** [comment]
@pjw9195 
어떤 개발 환경에서(Typescript? Javascript?) export import 문제가 생기고, 어떤 코드를 쓸 때 문제가 생기는지 알려주셔야 답변이 가능할 것 같습니다.

**Comment by pjw9195** [comment]
javascript 입니다. 현재 react 에다가 사용중이구요.
src 폴더를 그대로 가지고와서 imageEditor를 import 하려하니 commojs 와 es6를 혼용해서 사용해서 그런지
module.exports 로 export 하고 import from 으로 import 하는 모든 부분이 컴파일 에러가 납니다.

**Comment by junghwan-park** [comment]
@pjw9195 
번들된 `tui-image-editor.js`를 사용하시는게 아니라, ImageEditor의 `src` 폴더를 복사해서 사용하신다는거군요.
React에서도 Webpack을 사용해서 번들링 하므로 복사해오신 ImageEditor 소스에서 상대경로로 파일을 impor하는 데는 문제가 없을 것으로 예상 됩니다.

ImageEditor`core-js`나 `tui-code-snippet`과 같은 dependency들도 설치 하셨는지요?
그렇지 않다면, ImageEditor에서 필요로하는 package들이 올바르게 설치해 주시고,
ImageEditor에서 external library로 불러오는 패키지들을 위한 `webpack.config.js` 설정이 올바른지 확인 하셔야 할 것 같습니다.

하지만, React 애플리케이션과 연관이 적은 소스코드를 React 애플리케이션 소스와 같이 관리하려면 프로젝트의 설정 및 복잡도가 증가하므로, 별도의 ImageEditor를 커스터마이징 프로젝트를 구성하고 그 프로젝트에서 번들링 한 ImageEditor를 사용하시길 추천드립니다.

**Comment by pjw9195** [comment]
Failed to compile.

./src/components/products/etc/TuiImageEditor/js/ui/tools/range.js
Attempted import error: 'clamp' is not exported from '../../util'.

es6와 commonJs 를 혼합한 모든 곳에서 이런 에러가 나오고있습니다..

원인은 제가 더 찾아보겠습니다.

아마 커스터마이징은 imageEditor.js에서 할것같아요. 감사합니다.
