### ISSUE TITLE
Download image as jpg format

### ISSUE THREAD

**Issue by huqiye79** [nhn/tui.image-editor#341]
The PNG format have a huge size. Can I download the image as jpg format?

**Comment by jinwoo-kim-nhn** [comment]
* There is no way yet with the includeUI option, but you can implement it yourself using the `imageEditor.toDataURL` api. See the api doc below.
* http://nhn.github.io/tui.image-editor/latest/ImageEditor#toDataURL

**Comment by ijunaid8989** [comment]
@huqiye79 you can check here https://github.com/evercam/evercam-dashboardv2/pull/594

```
      var file = this.$refs.tuiImageEditor.invoke("toDataURL", {
        format: "jpeg"
      })
```
this is how I did it.
