### ISSUE TITLE
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by vishnudifferential** [nhn/tui.image-editor#344]
Hello

Thanks in advance. I am using this editor. I want to load image from s3 bucket. The images loaded sometimes and some time CROS Origin Error coming.
And sometimes it's working properly when I had open inspect element.

I already set CROS Origin permission in my S3 Bucket.

**Comment by jinwoo-kim-nhn** [comment]
@vishnudifferential Since this is the same issue as #68, we will close it and manage it in one issue.
