### ISSUE TITLE
How to upload picture to own server?

### ISSUE THREAD

**Issue by javaCR7** [nhn/tui.image-editor#346]
I use the 'example01-includeUi.html'.  Now ,I want to upload the picture to own server after edited.
It only  be  downloaded to local computer.I can't find the 'function( )' of clicking 'Download' button .

**Comment by jinwoo-kim-nhn** [comment]
I think it can be implemented directly using api. `imageEditor.toDataURL`
* http://nhn.github.io/tui.image-editor/latest/ImageEditor#toDataURL

Although this part of the implementation is going to improve. In the current version, you can implement `window.saveAS` yourself.

* https://github.com/nhn/tui.image-editor/blob/master/src/js/action.js#L119

**Comment by javaCR7** [comment]
your first  method , I  don't think it's right.It looks like a api method where to load picture.  I have a tried and it don't work.
The second method,I use "example01-includeUi.html". 'action.js' file is not used.It can still download to local.I can't trace the 'saveAs' function. and I don't know how to trigger 'downlaod' function in the “action.js”

**Comment by cocoroise** [comment]
> your first method , I don't think it's right.It looks like a api method where to load picture. I have a tried and it don't work.
> The second method,I use "example01-includeUi.html". 'action.js' file is not used.It can still download to local.I can't trace the 'saveAs' function. and I don't know how to trigger 'downlaod' function in the “action.js”

the first method:
````javascript
document.getElementById("#download").addEventListener('click', function (e) {
       const imageUrl = imageEditor.toDataURL();
       console.log('database64-->', imageUrl)
    })
````
you can upload this base64 image data to your server.
and the second method means,you can write like this
````javascript
window.saveAs=funtion(blob, imageName){
// you can access blob image in there and upload to your server
}
````
