### ISSUE TITLE
Example API Direct not working in latest version

### ISSUE THREAD

**Issue by sabinayakc** [nhn/tui.image-editor#351]
## Version
Latest 3.8.0

## Development Environment
Live Site

## Current Behavior
When I go to [https://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect](url) the Image Editor doesn't load. The console has a bunch of errors. 
![image](https://user-images.githubusercontent.com/13154166/75821485-fd3cff00-5d63-11ea-8f20-f53e555f3a3c.png)

## Expected Behavior
The Example should work locally and in demo site.

**Comment by jinwoo-kim-nhn** [comment]
hi @sabinayakc 
There is a problem with the cdn server we use, so it seems that we have been missing some libraries  for a while. Currently it seems to work fine at the time I checked.
Do you see the same phenomenon now? Please make sure the link below loads well.

* https://uicdn.toast.com/tui.code-snippet/v1.5.0/tui-code-snippet.min.js

**Comment by sabinayakc** [comment]
@jinwoo-kim-nhn 

Looks like the examples are loading now however I think the controls need to be updated. For example the brightness value is currently in the range of 255 to -255 and I think with the latest version it was updated to 1 to -1. So the brightness and other filters are working unexpectedly.

Thank you for your response.

**Comment by jinwoo-kim-nhn** [comment]
We made the issue again with #367
