### ISSUE TITLE
Reflect undo stack for object movement and resize.

### ISSUE THREAD

**Issue by jinwoo-kim-nhn** [nhn/tui.image-editor#358]
## Version
3.8.0

## Development Environment
Mac, Chrome

## Expected Behavior
Reflect undo stack for object movement and resize.

**Comment by julitillo** [comment]
I am very interested in this feature. Do you have any time estimatation?

**Comment by lja1018** [comment]
@julitillo 
This feature was added in v3.11.0. Thank you!
