### ISSUE TITLE
Prevent Cropping Before Crop Area Is Placed

### ISSUE THREAD

**Issue by bulentAkgul** [nhn/tui.image-editor#359]
If you hit Apply button whiteout cropping, all image is cropped out. It's normal behavior since all image is dark at that time but it would be nice if doesn't do anything if cropping area is 100% of real image.

**Comment by jinwoo-kim-nhn** [comment]
Thanks for the good comments.

**Comment by lja1018** [comment]
@bulentAkgul 
Thanks for the report. Resolved in [v3.12.0](https://github.com/nhn/tui.image-editor/releases/tag/v3.12.0).
