### ISSUE TITLE
Editable Section on Image

### ISSUE THREAD

**Issue by thachphamw2** [nhn/tui.image-editor#370]
Hello,

Thank you for creating such an amazing editor, especially it has the VueJS wrapper.

I have 2 questions, can you please let me know if T.I.E can do or your idea to achieve it?

1/ Can I define the editable section on the images after loading.

I can see we have the API to load Image from the file path.

For each file, it will have the limited editable part, instead of all over the image?

If so, what's the keyword I should follow or the API that I can extend to add my limited definition along with the file path?

2/ Can I disable/hide the tools on UI?

As I might need some, not all the tools on the editor, can I hide it?

Any suggestion would be great, hope you have a nice day too!

Thank you very much!

**Comment by jinwoo-kim-nhn** [comment]
1. There is currently no way to define an editable section. In fact, I don't know exactly why it is needed or what it is.
2. `includeUI.menu` I think it will work as an option and check out the documentation below.
* http://nhn.github.io/tui.image-editor/latest/ImageEditor

```js
         var imageEditor = new tui.ImageEditor('#tui-image-editor-container', {
             includeUI: {
                 ...
                 menu: ['crop', 'flip', 'rotate', 'draw', 'shape', 'icon', 'text', 'mask', 'filter']
             }
        ...
```

**Comment by thachphamw2** [comment]
> 1. There is currently no way to define an editable section. In fact, I don't know exactly why it is needed or what it is.
> 2. `includeUI.menu` I think it will work as an option and check out the documentation below.
> 
> * http://nhn.github.io/tui.image-editor/latest/ImageEditor
> 
> ```js
>          var imageEditor = new tui.ImageEditor('#tui-image-editor-container', {
>              includeUI: {
>                  ...
>                  menu: ['crop', 'flip', 'rotate', 'draw', 'shape', 'icon', 'text', 'mask', 'filter']
>              }
>         ...
> ```

Hi @jinwoo-kim-nhn 

Thank you for your answer!

1/ I needed it because we will allow the user to draw the area, then they will put the text into that area only. In the real world, I'm selling a T-shirt, I upload the shirt image only, then define the editable area so that the customer will not put the text or images out of the printable area.

2/ Can I develop the custom UI and from there load the external UI options?

3/ Can I develop and add the layers, like you're calling "Mask", but we couldn't reorder the layer so the newer images upload always on the top of the older one.

4/ You're using fabrics as the wrapper, so if we use Fabric functions/API inside Toast, can we just use it or import the Fabric library again?

Thank you for your attention!
