### ISSUE TITLE
How to load multiple Image Objects with same image file?

### ISSUE THREAD

**Issue by piecemakerz** [nhn/tui.image-editor#377]
I'm building custom web image editing application using this open source, and I'm stuck with loading same image as image object multiple times.

On _registerIconHAndler() function in **[icon.js](https://github.com/nhn/tui.image-editor/blob/master/src/js/ui/icon.js#L151)**, instead of calling registCustomIcon() function I call loadImage() function like below.

```
_registerIconHandler(event) {
    let imgUrl;

    if (!isSupportFileApi) {
        alert('This browser does not support file-api');
    }

    const [file] = event.target.files;

    if (file) {
        imgUrl = URL.createObjectURL(file);
        this.actions.loadImage(imgUrl);
    }
}
```
And **actions.loadImage()** is function that I added which simply call **[ImageEditor.addImageObject()](https://github.com/nhn/tui.image-editor/blob/master/src/js/imageEditor.js#L649)**.

The problem is, when I try to create multiple image objects with same image file, _registerIconHandler() is not being called at all except the first request of adding new image object.

Which part of code should I change to enable adding multiple image objects with same image file?

**current status**

![currentStatus](https://user-images.githubusercontent.com/22445243/78465336-66cb7700-772f-11ea-9002-d54ca14d7187.PNG)

**what I want**

![desiredStatus](https://user-images.githubusercontent.com/22445243/78465345-73e86600-772f-11ea-857f-15b97e7d9b7d.png)

**Comment by junghwan-park** [comment]
@piecemakerz 
Currently, ImageEditor not support loading multiple image to canvas. 
But, We planning to add Image object via #293.
