### ISSUE TITLE
Slider value becomes on first load NaN

### ISSUE THREAD

**Issue by GEMI** [nhn/tui.image-editor#381]
**Describe the bug**
When loading image for the first time and trying to use paint tool the range slider is not usable. It becomes NaN on click and cannot be dragged.

I am loading the image by using the infamous `.loadImageFromURL`method. I think this might be causing this bug. Because the second time I open the image editor the slider works fine.

**To Reproduce**
1. Open image editor
2. Open Draw tool
3. Click and draw the slider
4. Slider does not work and value becomes NaN

**Expected behavior**
After loading the image editor second time the value is correct and slider works.

**Screenshots**
![NaN](https://user-images.githubusercontent.com/769500/79109209-8f332100-7d80-11ea-990a-842b61d42322.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.3
 - Browser Chrome 80
 - Version TUI image editor 3.9.0

**Comment by jinwoo-kim-nhn** [comment]
It doesn't reappearance well. Use a tool like codepen to tell me more.

**Comment by nikhil2802Vishwakarma** [comment]
when I add Editor in Modal I run into an issue, on changing the value from slider it is changing to NaN, But if the modal is placed on a page without modal. This is working fine
