### ISSUE TITLE
Clear canvas and UI

### ISSUE THREAD

**Issue by superstar1128** [nhn/tui.image-editor#383]
How can I clear all objects from canvas and UI?
When load img, menu is activated automatically.
I want to add "Clear" button, so when click "clear", clear canvas and hide menu.
How can I do it?
I called imageEditor.clearObjects(), but loaded image is remained on the canvas.

**Comment by junghwan-park** [comment]
@superstar1128
Sorry for late reply.

The only way to remove loaded image is destroy and create new ImageEditor instance for now.

As you know, `imageEditor.clearObjects()` clear only objects on the canvas(shape, line, text, icon). And ImageEditor treats the loaded image as background image. 
So currently, loaded image remains until replacing another image.

I'll discuss adding API for clear ImageEditor with initial instance state with my team. Thanks.

**Comment by Geetanjali2029** [comment]
How to clear image on canvas? Please help

Thank you in advance

**Comment by Geetanjali2029** [comment]
I have tried many ways sir but still no success.

 imageEditorInst.loadImageFromURL("null", "image").then(() => {
        imageEditorInst.clearObjects();
        imageEditorInst.clearUndoStack();
        imageEditorInst.clearRedoStack();
      }).catch((e)=>{console.log(e)  });

OR

        imageEditorInst.clearObjects();
        imageEditorInst.clearUndoStack();
        imageEditorInst.clearRedoStack();

**Comment by eomttt** [comment]
i have same problem can i claer image?

**Comment by dano1066** [comment]
Also wondering how to clear an image from the canvas. UI can get laggy when a large image is there, I want to get rid of it once the user has saved the result without destroying the entire canvas

**Comment by lja1018** [comment]
@dano1066 
There is no way to erase the background image yet. I'll consider it.
