### ISSUE TITLE
[Question] How to change submenu options?

### ISSUE THREAD

**Issue by sunnyfork** [nhn/tui.image-editor#384]
## Version
3.9.0

## Development Environment
Chrome, Windows 10

## Current Behavior
I only need the rectangle shape function in my project. I have already use the menu option to show only Shape menu. I tried to change the code in ui/submenu/shape.js to show only the rectangle button but it seems not working. Could you please suggest the correct way to do it? Thank you.

**Comment by junghwan-park** [comment]
@sunnyfork 
Currently no way to configure submenu items.
I'll discuss new option for that with my team.

**Comment by valentinoPereira** [comment]
any update on this?
