### ISSUE TITLE
'resizeCanvasDimension' is unavailable

### ISSUE THREAD

**Issue by kopair** [nhn/tui.image-editor#386]
please give some examples,Thanks!

**Comment by kopair** [comment]
return undefined
![微信图片_20200514193913](https://user-images.githubusercontent.com/32586709/81930076-9e74eb00-961a-11ea-80d2-55731ec802bc.png)
![微信图片_20200514193921](https://user-images.githubusercontent.com/32586709/81930080-a03eae80-961a-11ea-8513-19f27a5bb908.png)

**Comment by kopair** [comment]
sometime can be used, if the photo is too small,it is unavailable,can you help me?

**Comment by junghwan-park** [comment]
@kopair
I think you're using that API correctly. 
The `imageEditorInstance.resizeCanvasDimension()` promise resolved with `undefined` is normal.

And that dimension is not a actual image's dimension but `cssMaxWidth` and `cssMaxHeight`. 
![image](https://user-images.githubusercontent.com/7088720/82639207-3db16800-9c43-11ea-96c6-edf5d3afd7a4.png)
[API Link](https://nhn.github.io/tui.image-editor/latest/ImageEditor)

ex) When image original dimension is `{width: 100, height: 200}`, If you set `resizeCanvasDimension({width: 400, height: 100})` then image size will be changed by `{width: 50, height: 100}`.
