### ISSUE TITLE
`npm run test` hangs

### ISSUE THREAD

**Issue by murtyjones** [nhn/tui.image-editor#389]
**Describe the bug**
`npm run test` hangs after running HeadlessChrome tests

**To Reproduce**
1. Clone the repo
2. `npm i`
3. `npm run test`

**Expected behavior**
The test suite should run and exit when done.

**Screenshots**
![image](https://user-images.githubusercontent.com/708562/80536001-b1779200-896f-11ea-8b55-da61bb6d7c76.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser n/a
 - Version 3.9.0

**Comment by junghwan-park** [comment]
@murtyjones Because, `npm run test` script runs `karma` with `--no-single-run` option.

![image](https://user-images.githubusercontent.com/7088720/81374579-885abc80-913a-11ea-9d27-7ae20e48208d.png)

If you want single run karma testing, exec `npx karma start` command in your project root directory.
