### ISSUE TITLE
the lmage is disappearing when clicking reset button

### ISSUE THREAD

**Issue by mahi25s** [nhn/tui.image-editor#391]
**Describe the bug**
the lmage is disappearing when clicking reset button

**To Reproduce**
1. take image editor with a default image
2. Click on the reset button

**Expected behavior**
when clicking reset button the image should be there

**Comment by junghwan-park** [comment]
@mahi25s 
Where is `reset button` what you said?

![22222](https://user-images.githubusercontent.com/7088720/81370957-6d377f00-9131-11ea-8dbc-0bfb44aa8766.png)
The red circled button is that button?

I think `reset button` not remove image.
