### ISSUE TITLE
When Scale image object didn't get updated height width

### ISSUE THREAD

**Issue by lochawala** [nhn/tui.image-editor#393]
When i add image object and scale it didn't get updated height width of that object in objectScaled listener

**Comment by lochawala** [comment]
refuse

**Comment by lochawala** [comment]
refuse 

> Thank you for raising an issue.
> We will try and get back to you as soon as possible.
> 
> Please make sure you have filled out issue respecting our form **in English** and given us as much context as possible. **If not, the issue will be closed or not replied.**

**Comment by geosmart** [comment]
this bug is exist, how can I get the scaled image object's current width and height!
