### ISSUE TITLE
Javascript error on startup

### ISSUE THREAD

**Issue by JupitorGeorge** [nhn/tui.image-editor#396]
After installing with npm and running first test the "forEach" is failing in util.js

Uncaught TypeError: Cannot read property 'forEach' of undefined
    at keyMirror (util.js:47)
    at eval (errorMessage.js:15)
    at Object../src/js/factory/errorMessage.js (tui-image-editor.js:1362)
    at __webpack_require__ (tui-image-editor.js:36)
    at eval (command.js:13)
    at Object../src/js/interface/command.js (tui-image-editor.js:1422)
    at __webpack_require__ (tui-image-editor.js:36)
    at eval (command.js:3)
    at Object../src/js/factory/command.js (tui-image-editor.js:1350)
    at __webpack_require__ (tui-image-editor.js:36)
keyMirror @ util.js:47
eval @ errorMessage.js:15
./src/js/factory/errorMessage.js @ tui-image-editor.js:1362
__webpack_require__ @ tui-image-editor.js:36
eval @ command.js:13
./src/js/interface/command.js @ tui-image-editor.js:1422
__webpack_require__ @ tui-image-editor.js:36
eval @ command.js:3
./src/js/factory/command.js @ tui-image-editor.js:1350
__webpack_require__ @ tui-image-editor.js:36
eval @ invoker.js:17
./src/js/invoker.js @ tui-image-editor.js:1458
__webpack_require__ @ tui-image-editor.js:36
eval @ imageEditor.js:17
./src/js/imageEditor.js @ tui-image-editor.js:1410
__webpack_require__ @ tui-image-editor.js:36
eval @ index.js:5
./src/index.js @ tui-image-editor.js:834
__webpack_require__ @ tui-image-editor.js:36
(anonymous) @ tui-image-editor.js:100
(anonymous) @ tui-image-editor.js:103
webpackUniversalModuleDefinition @ tui-image-editor.js:15
(anonymous) @ tui-image-editor.js:16

Also, the external connection fails to load the map program

<link rel="stylesheet" href="https://uicdn.toast.com/tui-image-editor/latest/tui-image-editor.css">
<script src="https://uicdn.toast.com/tui-image-editor/latest/tui-image-editor.js"></script>

**Comment by junghwan-park** [comment]
@JupitorGeorge
Which version did you use?

**Comment by JupitorGeorge** [comment]
Hello,

 

This was the latest version by npm


1. ImageEditor installation

$ npm install --save tui-image-editor # Latest version

**Comment by mystery-man** [comment]
Any update on this bug. I am facing the same issues as well. @junghwan-park

**Comment by jinwoo-kim-nhn** [comment]
Make sure that the dependency modules are loaded ahead of time.

![스크린샷 2020-06-08 오전 10 46 26](https://user-images.githubusercontent.com/35218826/83985799-7b1d3180-a975-11ea-956b-b04eda6ee5dd.png)
