### ISSUE TITLE
How to remove sub menu

### ISSUE THREAD

**Issue by EABangalore** [nhn/tui.image-editor#399]
Hi all, my question is how can i remove some sub menu similar to the option we include for `menu`

for including any specific menu we do like this

```
includeUI: {
     menu: ['icon']
}
```

Now  my ui will have only `icon` menu, further i want to filter out some submenu from `icon` menu.

![image](https://user-images.githubusercontent.com/21359377/82724069-fb466480-9cf0-11ea-9dcc-2e9d5c829d27.png)

From the above shown image i want to remove

1. polygon
2. map
3. heart

How can i achieve that?

please help me thanks in advance

**Comment by junghwan-park** [comment]
@EABangalore 
Currently no way to handle submenu items. 
It will be developed by #398.

**Comment by EABangalore** [comment]
@junghwan-park  thanks for the reply. thanks you took it.
