### ISSUE TITLE
Rotated text label shifts when crating new shape/icon

### ISSUE THREAD

**Issue by josephqin** [nhn/tui.image-editor#401]
**Describe the bug**
In the demo page [http://nhn.github.io/tui.image-editor/latest/tutorial-example01-includeUi](url) The previous added rotated text label will be shifted when add new shape/icon

**To Reproduce**
1. add a text label to an image and then rotate it like 45 degrees
2. Click on shapes then add rectangular icon. Notice the text drops down upon clicking the rectangle shape.  

**Expected behavior**
Text label should stay same

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: Chrome

**Additional context**

**Comment by junghwan-park** [comment]
@josephqin Thank you for reporting issue.


## Screen capture
![text](https://user-images.githubusercontent.com/7088720/83834939-787acc00-a72a-11ea-90e7-5e61362445b2.gif)

**Comment by josephqin** [comment]
@junghwan-park  which release this bug will get fix?
