### ISSUE TITLE
How to position the image object? I am using the latest version

### ISSUE THREAD

**Issue by HamzaAbubakar** [nhn/tui.image-editor#406]
**Summary**
A clear and concise description of what the question is.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the imageEditor you are currently using.

**Additional context**

**Comment by HamzaAbubakar** [comment]
The solution has been founded:

 			imageEditor.addImageObject('image.png').then(objectProps => {
 				imageEditor.setObjectPosition(objectProps.id, {
 					x: 530,
 					y: 0,
 					originX: 'left',
 					originY: 'top'
 				});
                         });

**Comment by ahsannajam** [comment]
> The solution has been founded:
> 
> ```
> 		imageEditor.addImageObject('image.png').then(objectProps => {
> 			imageEditor.setObjectPosition(objectProps.id, {
> 				x: 530,
> 				y: 0,
> 				originX: 'left',
> 				originY: 'top'
> 			});
>                      });
> ```

Hi,
I am trying to add an image like we call an icon or shape in TUI image editor Mobile. So for this, I added the following code in service-mobile.js

`var $btnAddImageShade = $('#btn-add-image-shade');`

```
$btnAddImageShade.on('click', function() {
    imageEditor.addImageObject('img/shade1.png').then(objectProps => {
            imageEditor.setObjectPosition(objectProps.id, {
                x: 530,
                y: 0,
                originX: 'left',
                originY: 'top'
            });
                     });
});
```
and on the main page

`<button class="submenu-button" id="btn-add-image-shade">Image 1</button>`

is it a correct code to call an image on button click?
