### ISSUE TITLE
Brightness filter (using API) does not seem to work

### ISSUE THREAD

**Issue by haukurhaf** [nhn/tui.image-editor#408]
Changing the brightness of an image results in a completely black image or completely white image, nothing in between.

Also broken in the example here: http://nhn.github.io/tui.image-editor/latest/tutorial-example01-includeUi 

This used to work fine some weeks/months ago.

Tested in the latest version of Chrome and Edge.

NOTE:  Seems to work fine using the included UI in the editor, but not when doing this via the API.

**Comment by jinwoo-kim-nhn** [comment]
Thanks for the tip. I will correct it after checking
