### ISSUE TITLE
Undo and Reset buttons hiding

### ISSUE THREAD

**Issue by yshkvarok** [nhn/tui.image-editor#415]
**Describe the bug**
Undo and reset buttons are both hiding after drawing. They become visible on hover.

**To Reproduce**
1. Go to tui-image-editor demo [https://ui.toast.com/tui-image-editor/](https://ui.toast.com/tui-image-editor/)
2. Click on 'draw' button and start drawing
3. As soon as you release the mouse button to stop drawing, the reset and undo buttons disappear.

**Expected behavior**
These buttons should stay visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/19601773/85573428-e0bf1e00-b603-11ea-89a9-d79a11e927ad.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.4
 - Browser: Chrome
 - Version: 83.0.4103.106

**Comment by OculusMode** [comment]
@kyuwoo-choi I tried to generate this in master branch(linux OS) however this doesn't seem to be happening.
Is latest code deployed on given url?

**Comment by lja1018** [comment]
Thank you for reporting. A bug in the demo of our brand site has been fixed. Thank you.
