### ISSUE TITLE
Text postion changes when clicked on Image.

### ISSUE THREAD

**Issue by HamzaAbubakar** [nhn/tui.image-editor#416]
**Describe the bug**
I am adding Text Objects on page load with predefined position. The texts are added with correct positions but when i click on any text all of text positions are changed.

**Expected behavior**
Position of texts should not be changed.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/43183387/85982230-e7340800-b9fe-11ea-8fc0-cbadf2f299e2.png)

![image](https://user-images.githubusercontent.com/43183387/85982401-34b07500-b9ff-11ea-8593-f7bd1411a4d5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Version 68

**Comment by jinwoo-kim-nhn** [comment]
It doesn't reproduce well. Do you happen on one of our example pages?

* http://nhn.github.io/tui.image-editor/latest/tutorial-example01-includeUi
* http://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect


For example, the reproduced code needs a bit more explanation. For example codepen.
