### ISSUE TITLE
brush settings are not working for draw line [bug]

### ISSUE THREAD

**Issue by syammehar** [nhn/tui.image-editor#418]
## Version
3.9.0

## Environment
Windows 10 Chrome Version 83.0.4103.116 (Official Build) (64-bit)

## Current Behavior
Brush settings are not working for the draw straight line in use API direct, however, when we switch to free drawing and back to the straight line, applied settings work fine.
![editor bug](https://user-images.githubusercontent.com/36952618/86087144-e3ff5180-babc-11ea-8fcd-a4d246ad1638.gif)

## To Reproduce
1. Go to http://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect.
2. Select the DrawLine option from the menu.
3. Switch to Straight line.
4. Change brush settings i.e. brush color and brush width.
5. Settings do not work when you draw a line

**Comment by jinwoo-kim-nhn** [comment]
Yes thanks for letting me know. I will confirm this in a short time.

**Comment by lja1018** [comment]
@syammehar 
This issue was resolved in v3.11.0. Thank you!
