### ISSUE TITLE
Event after editing text or for each change

### ISSUE THREAD

**Issue by marioviana** [nhn/tui.image-editor#419]
## Version
Latest

## Development Environment
Electron 9.0.4 & Mac OS Catalina 10.15.4

## Current Behavior
Currently, we only have an event when the user starts editing the text. Also, this change doesn't enter on the undo stack, we cannot save the image after the user ends the text editing because we don't know when this happens.

## Expected Behavior
An event when the user end the text editing or having each change triggering the event.

**Comment by jinwoo-kim-nhn** [comment]
Thanks for the problem. We will check and improve.

**Comment by gaslit** [comment]
Hello, is there any news regarding this fix? Many thanks. This is also linked to issue #387

**Comment by lja1018** [comment]
@marioviana @gaslit 
Thanks for the report. Resolved in [v3.12.0](https://github.com/nhn/tui.image-editor/releases/tag/v3.12.0).
