### ISSUE TITLE
Editor is not much responsive with more than 5MB images, very much lagging

### ISSUE THREAD

**Issue by EABangalore** [nhn/tui.image-editor#422]
Hi, 

I'm facing huge lagg when i apply filters for images which is big in size let say more than 5MB.

is there any way to avoid those laggs?

my pluggin version are shown below

```
<script type="text/javascript" src="js/plugin/tui-image-editor/fabric.js"></script> <!-- version 1.6.7 -->
<script type="text/javascript" src="js/plugin/tui-image-editor/tui-code-snippet.js"></script> <!-- version 1.5.0 -->
<script type="text/javascript" src="js/plugin/tui-image-editor/filesaver.min.js"></script> <!-- unknown -->
<script type="text/javascript" src="js/plugin/tui-image-editor/tui-color-picker.js"></script> <!-- version 2.2.0 -->
<script type="text/javascript" src="js/plugin/tui-image-editor/tui-image-editor.js"></script> <!-- version 3.3.0-->
```

**Question:** when i select any filter it takes too much time to apply(that is what i called lagging), please help me to get rid of that

Please help me to avoid that?

**Comment by jinwoo-kim-nhn** [comment]
Sorry. Performance problems are difficult. I am currently using fabricjs as a dependency module. I have a problem with fabricjs. I am not sure if I can fix this. But I'll try.
