### ISSUE TITLE
Is it possible to add border to image?

### ISSUE THREAD

**Issue by bsde1234** [nhn/tui.image-editor#425]
**Summary**
Is it possible to add some predefined border to image that gets uploaded?

**Comment by jinwoo-kim-nhn** [comment]
I don't know exactly what you want. Can you elaborate more? Do you want to make it like a frame decoration?

**Comment by bsde1234** [comment]
> I don't know exactly what you want. Can you elaborate more? Do you want to make it like a frame decoration?

yes, I mean frame decoration.
