### ISSUE TITLE
How can i send backward/forward object like we handling layers?

### ISSUE THREAD

**Issue by pankaj-jajoria** [nhn/tui.image-editor#427]
If I create text then create a rectangle box. I just need functionality to send that rectangle behind the text.

**Comment by jinwoo-kim-nhn** [comment]
The current rule is that the last element created is on top. We will discuss the ability to change this in our team.

**Comment by jwooss** [comment]
I solved by writing the following code to move the selected object
```javascript
editor._graphics.getCanvas().on({
      'selection:updated': options => options.target.bringToFront(),
      'selection:created': options => options.target.bringToFront(),
})
```
