### ISSUE TITLE
How can I set the width of the text box automatically?

### ISSUE THREAD

**Issue by jwooss** [nhn/tui.image-editor#430]
**Summary**
Using the provided UI, I can see that the textbox width is automatically lengthened as I type TEXT.
However, the width of the text box does not automatically increase when the included ui is not used.

How can I make it set automatically without using the provided ui?

The problem can be seen in the example.
1. [Include UI](https://nhn.github.io/tui.image-editor/latest/tutorial-example01-includeUi)
2. [Use api direct](https://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect)

**Version**
v3.9.0

**Comment by jwooss** [comment]
I have one more question

When the ui provided by default is not used, double-clicking the text box changes the position and size. What is the reason?
And is there a way to change the color of the outline of the text box when the cursor is activated

**Screenshots**
![issue-sample](https://user-images.githubusercontent.com/19146978/87916257-290c1780-caae-11ea-868b-ab5ebb4bc57a.png)

**Comment by jinwoo-kim-nhn** [comment]
Solved in version 3.10.0
