### ISSUE TITLE
Question: how to personalise object "selection" styles ? 

### ISSUE THREAD

**Issue by Aarbel** [nhn/tui.image-editor#432]
I'd like to personalize the object selection styles (put circles instead of green squares, change their colors, change color of red selection rectangle.

Whta is the best way to do it ? Thanks a lot !

![image](https://user-images.githubusercontent.com/25119847/88474401-503b6c80-cf26-11ea-9aa6-3ab8016c32cb.png)

**Comment by LemuelKL** [comment]
Pass `selectionStyle: {
          cornerStyle: "circle",
          cornerSize: 10,
          cornerColor: "#000000",
          cornerStrokeColor: "#000000",
          transparentCorners: false,
          lineWidth: 1,
          borderColor: "#000000",
        },` in `options`.

**Comment by Aarbel** [comment]
Perfect thanks a lot !
