### ISSUE TITLE
Undo-redo function converts Icon to small size

### ISSUE THREAD

**Issue by jmenguito** [nhn/tui.image-editor#441]
**Version**
3.9.0

**Describe the bug**
Drawing Icon converts to small size after undo and redo is performed.

**To Reproduce**
1. Click on 'Icon'
2. Draw any shape
3. Click on 'undo', then 'redo'
4. After 'redo', the shape becomes small in size

**Comment by jinwoo-kim-nhn** [comment]
@jmenguito Thanks for letting me know, I'll fix it.

**Comment by lja1018** [comment]
@jmenguito 
This issue was resolved in v3.11.0. Thank you!

**Comment by jmenguito** [comment]
Wow! thanks!
