### ISSUE TITLE
Mobile Documentation Link is not functional

### ISSUE THREAD

**Issue by shoutershub** [nhn/tui.image-editor#442]
Hello, i am trying to utilize the mobile UI for one of my ionic apps.

But the link in the documentation is broken 
Sample Page : http://nhn.github.io/tui.image-editor/latest/tutorial-example03-mobile.html

**Comment by jinwoo-kim-nhn** [comment]
Thanks for the tip, I'll fix it.

**Comment by bernardbaker** [comment]
@jinwoo-kim-nhn I'd like to use the mobile version in a React JS app. How can I do this?

**Comment by bernardbaker** [comment]
> Hello, i am trying to utilize the mobile UI for one of my ionic apps.
> 
> But the link in the documentation is broken
> Sample Page : http://nhn.github.io/tui.image-editor/latest/tutorial-example03-mobile.html

@shoutershub were you able to implement the mobile version? How did you implement it?

**Comment by lja1018** [comment]
@bernardbaker 
Sorry for the late reply.
There is no separate API for the mobile version, so I think you can just use it. :)

**Comment by bernardbaker** [comment]
@lja1018 when I implemented it using the React component it presents the desktop UI. But I need to see the mobile version. How can I do that?

**Comment by lja1018** [comment]
@bernardbaker 
Now I understand!
The mobile UI is a separate UI created for [example page](https://github.com/nhn/tui.image-editor/blob/master/apps/image-editor/examples/example03-mobile.html). The actual UI is provided only with the so-called desktop UI.

**Comment by bernardbaker** [comment]
@lja1018 do you have a React component for mobile being developed?

**Comment by lja1018** [comment]
@bernardbaker 
I'm sorry to say this, but I don't have plans for mobile UI development.
