### ISSUE TITLE
Blur Filter not Working

### ISSUE THREAD

**Issue by Katario** [nhn/tui.image-editor#445]
**Describe the bug**
When applying filter Blur, it's not doing anything to the image.

**To Reproduce**
1. Go to 'Filter' Tab
2. Click on 'Blur'
(Can be seen in both API & UI examples)

**Expected behavior**
It should blur, I guess ?

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: All
 - Version 18.04

**Comment by jinwoo-kim-nhn** [comment]
@Katario okay. I've checked and I'll fix it soon.

**Comment by Katario** [comment]
Nice! Thank you!

**Comment by lja1018** [comment]
@Katario 
This issue is resolved. Thank you!
