### ISSUE TITLE
Question: how to put a circle in the crop tool ?

### ISSUE THREAD

**Issue by Aarbel** [nhn/tui.image-editor#446]
Is there a way to put an additional circle in the square while croping with toast ui ?

**I'm not talking about cropping to a circle, i want to keep the square**

Thanks a lot for your help !

![image](https://user-images.githubusercontent.com/25119847/92478085-f515be80-f1e1-11ea-954d-ed8bde16e481.png)

**Comment by jinwoo-kim-nhn** [comment]
@Aarbel You mean something like #363?

**Comment by Aarbel** [comment]
@jinwoo-kim-nhn yes but with a square as output (because a circle can often turn a round square in UI)
