### ISSUE TITLE
Is there any way to change anchor color, I could not find anything on theme config. Thanks.

### ISSUE THREAD

**Issue by devops8848** [nhn/tui.image-editor#447]
I was trying to change anchor color and could not found any way to change it from theme config. Is it possible? Thanks for the great package.

![Screen Shot 2020-09-08 at 18 28 00](https://user-images.githubusercontent.com/46563555/92478530-fe168800-f201-11ea-8ed9-d295bfd45e29.png)

**Comment by jinwoo-kim-nhn** [comment]
@devops8848 refer to the selectionStyle option below and change it.

![corner_style](https://user-images.githubusercontent.com/35218826/93955224-37b2cb80-fd8a-11ea-9d5c-4b52785a27da.png)
