### ISSUE TITLE
Undo-Redo command of icon color change does not work properly.

### ISSUE THREAD

**Issue by dragonsuperf** [nhn/tui.image-editor#448]
**Describe the bug**

When the color is changed after creating the icon, the Undo-Redo command does not work properly.

**To Reproduce**
1. Go to 'icon' tab
2. Click some icon to create
3. Change icon color
4. Do Redo and Undo

**Expected behavior**

Undo with the color before changing, and redo with the color after changing.

**Screenshots**
![GIF 2020-09-14 오후 6-19-42](https://user-images.githubusercontent.com/23359043/93068375-54c70a80-f6b7-11ea-9579-efffe48ce774.gif)

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser: Chrome
 - Version: 85.0.4183.102

**Comment by jinwoo-kim-nhn** [comment]
@dragonsuperf Thanks for letting me know. I'll check

**Comment by dragonsuperf** [comment]
@jinwoo-kim-nhn  I already fix this, check this pull request please

https://github.com/nhn/tui.image-editor/pull/449

**Comment by lja1018** [comment]
@dragonsuperf 
This issue is resolved. Thank you!
