### ISSUE TITLE
where is /dist  folder ? how run this html5 app?

### ISSUE THREAD

**Issue by lse123** [nhn/tui.image-editor#455]
**Describe the bug**
where is /dist  folder ? how run this html5 app?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jinwoo-kim-nhn** [comment]
Do it like below.

```js
npm run bundle
```

**Comment by mlongv** [comment]
How to modify the default text dubble click of addtext method to what you want?
