### ISSUE TITLE
support HTMLCanvasElement.toBlob()

### ISSUE THREAD

**Issue by adsee42** [nhn/tui.image-editor#457]
## Version

latest

## Development Environment

Chrome, Ubuntu

## Current Behavior

To get edited image and upload it, I have to use `imageInstance.toDataURL()`, and convert it to a blob manually.

## Expected Behavior

Since most browsers support `HTMLCanvasElement.toBlob()` now, can we have that in this package too?

**Comment by jinwoo-kim-nhn** [comment]
Please refer to it. #424
