### ISSUE TITLE
Is there a way to get the undo command when the undo button is clicked or on undoStackChanged?

### ISSUE THREAD

**Issue by kittychengyuenpui** [nhn/tui.image-editor#458]
**Summary**
As I want to record the undo command when a user clicked the undo button, is there a way to get it from existing methods when using the API? 

**Version**
version 3.10.0

**Comment by jinwoo-kim-nhn** [comment]
Sorry, there is currently no such method.

**Comment by kittychengyuenpui** [comment]
> Sorry, there is currently no such method.

I see. But is it possible to be a further  enhancement? Or was it intentionally to be set as not reachable?
