### ISSUE TITLE
Is it possible to deactivate keyboard shortcuts?

### ISSUE THREAD

**Issue by papeixoto** [nhn/tui.image-editor#459]
**Summary**
I have a react project where I include the image editor and it listens to keyboard shortcuts through the entire screen, even if another element is focused. Is there any way for me to turn off keyboard shortcuts?

**Screenshots**

**Version**
3.9.0

**Additional context**
I have the image editor and a text field bellow. When I'm tipping in the text field keyboard shortcuts like crtl+z and such are still being listened by the image editor.

**Comment by jinwoo-kim-nhn** [comment]
Sorry, there is currently no such method. I'll consider improving this. Thanks.

**Comment by mammadkoma** [comment]
Please add this option to disable keyboard shortcuts.

**Comment by RKTZ** [comment]
Had the same problem when pressing the space bar. Not recommended but you can use `imageEditorInst._graphics._detachZoomEvents()`

**Comment by wangyong991** [comment]
`document.removeEventListener("keydown", ImageEditor._handlers.keydown);` or 
`ImageEditor.on("undoStackChanged", (length) => {
    length && ImageEditor.clearUndoStack();
  });`
