### ISSUE TITLE
The Cursor Position in Text Editor

### ISSUE THREAD

**Issue by ahsannajam** [nhn/tui.image-editor#460]
**Describe the bug**
There is a bug whenever we create a long text, the editor shows the blinking cursor position few letters earlier but actually, it is not there. I have updated the editor to the version 3.10.0 but no impact, still the same. Someone else also raised the same issue but not resolved yet.
![image](https://user-images.githubusercontent.com/16335675/94608752-48e26780-02b7-11eb-977d-5ed35301f63a.png)

**Comment by jinwoo-kim-nhn** [comment]
Thanks for the tip. There is an issue originally, so we'll see it there
#325

**Comment by ahsannajam** [comment]
Issue not resolved. If I change the default NOTO fonts to Raleway and create a long text, The cursor shows this kind of behaviour.
