### ISSUE TITLE
Image Editor crop function breaks in Safari v14

### ISSUE THREAD

**Issue by parrywh** [nhn/tui.image-editor#461]
**Describe the bug**
Image disappears from display when applying crop in Safari v14

**To Reproduce**
1. Open tab in Safari v14
2. Navigate to https://ui.toast.com/tui-image-editor/
3. Click Crop and Apply Crop Area to image
4. Click Apply

**Expected behavior**
Image should be cropped according to crop area and displayed

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Safari
 - Version 14

**Comment by jinwoo-kim-nhn** [comment]
Thanks for the tip. This is critical. I'll fix it quickly.

**Comment by parrywh** [comment]
@jinwoo-kim-nhn any updates on the fix? thanks!

**Comment by GeekFreakInk** [comment]
it also happens on google chrome used on an Iphone X.

**Comment by parrywh** [comment]
@jinwoo-kim-nhn any updates at all? thank you!

**Comment by lja1018** [comment]
@parrywh 
This issue was resolved in v3.11.0. Thank you!
