### ISSUE TITLE
The line thickness slider does not work on mobile devices

### ISSUE THREAD

**Issue by vraginya** [nhn/tui.image-editor#462]
**Describe the bug**
The line thickness slider does not work on mobile devices.

**To Reproduce**
1. Use any mobile device with touch screen
2. Select the draw tool or the shape tool in the editor
3. Try to increase or reduce the line thickness by moving the dot right or left.
**Expected behavior**
The dot is moving below the finger, the thickness value is getting changed

**Screenshots**
![image](https://user-images.githubusercontent.com/31799028/95249680-be9f8380-0821-11eb-9b8a-a19f9f20c22e.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Note 8 Pro, iPhoneXS
 - OS: Android, iOS
 - Browser: Chrome, Safari
 - Version: any

**Comment by jinwoo-kim-nhn** [comment]
thanks, We already have the same issue channel, so we will deal with it there.
#418
