### ISSUE TITLE
Consistent font size irrestpective of image

### ISSUE THREAD

**Issue by binarytrance** [nhn/tui.image-editor#464]
**Summary**
I have noticed that the font size of text that is being added varies with image dimensions. An image with large width and height values seems to take a larger font size and vice versa. Seems like the text is being set from 0 - 100. Is this some kind of relative font sizing? Can we apply font sizing in pixels?

**Screenshots**
on both the images below, the text sizes are set at 50.
![image_1601287607757](https://user-images.githubusercontent.com/6273103/95688564-e0857580-0c28-11eb-8b32-eb56c9664c32.png)
![image_1601287607842](https://user-images.githubusercontent.com/6273103/95688566-e3806600-0c28-11eb-825f-10848ff76c98.png)

**Version**
1.2.0

**Additional context**
This way of adding text sizes is undesirable, in certain images, the text is too small to be readable. How can I give a consistent base/default font size to text being added to any and all kinds of images?

**Comment by jinwoo-kim-nhn** [comment]
As the canvas is displayed in a reduced form according to the `cssMaxWidth` and `cssMaxHeight` options, it seems that you can put the actual image size in `cssMaxWidth` and `cssMaxHeight`.

![스크린샷 2020-10-28 오후 12 31 21](https://user-images.githubusercontent.com/35218826/97387533-88818b00-1919-11eb-8a14-feaf9e0d8a2a.png)

**Comment by binarytrance** [comment]
Default text sizes still vary after implementing your suggestion. Would you say that text sizes would always vary because they depend on the image resolution?
