### ISSUE TITLE
I am trying to save an image as jpeg after rotating, its adding black background color

### ISSUE THREAD

**Issue by praveen-wal** [nhn/tui.image-editor#465]
**Describe the bug**
I am trying to save an image as a jpeg after rotating, it's adding a black background-color. Can you add an option to change the default rotating angle from inputs? I need it to be 90, so that way it won't add black color.

**Screenshots**
https://i.imgur.com/lGx9U3I.jpg

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 3.10.0

**Comment by jinwoo-kim-nhn** [comment]
This is not a bug. You are mistaken. The background will be transparent.

**Comment by praveen-wal** [comment]
@jinwoo-kim-nhn It's working well for `png` but this black color is coming only for `jpeg`.

![15366](https://user-images.githubusercontent.com/46365855/97412439-9807d080-1927-11eb-85e8-2ccea2d874f3.jpeg)

**Comment by yoieh** [comment]
> @jinwoo-kim-nhn It's working well for `png` but this black color is coming only for `jpeg`.
> 
> ![15366](https://user-images.githubusercontent.com/46365855/97412439-9807d080-1927-11eb-85e8-2ccea2d874f3.jpeg)

jpeg dosent support transparant colors. That's why its works with png witch dose support transparent colors.
