### ISSUE TITLE
How to modify the default text Double Click of addtext method to what you want?

### ISSUE THREAD

**Issue by mlongv** [nhn/tui.image-editor#470]

**Comment by mlongv** [comment]
@kyuwoo-choi @shiren @cybaek @brendon

**Comment by sundeepch1** [comment]
open tui-image-editor.js file=> find method addText: and change the existing text 'Double Click to your desire text. That method is =>

addText: function addText(pos) {
	                _this11.addText('Double Click', {
	                    position: pos.originPosition,
	                    styles: {
	                        fill: _this11.ui.text.textColor,
	                        fontSize: _util2.default.toInteger(_this11.ui.text.fontSize),
	                        fontFamily: 'Noto Sans'
	                    }
	                }).then(function () {
	                    _this11.changeCursor('default');
						getTextActivatedObject(getCurrentObject);
	                });
	            },
