### ISSUE TITLE
How to modify the default text Double Click of addtext method to what you want?

### ISSUE THREAD

**Issue by mlongv** [nhn/tui.image-editor#471]
**Expect**
Can double click generated by clicking the panel be customized. Whether the text generated by clicking the panel can be customized or not, and can the text generated when the click panel is disabled can be configured.

**Version**
3.10.0

@brendon @joelabair @shiren @kyuwoo-choi

**Comment by jinwoo-kim-nhn** [comment]
Have you checked the example page? I can't figure out exactly what I want.

The example page below contains almost all of the features used in the image editor.
You can refer to it and customize it.

* http://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect
* https://github.com/nhn/tui.image-editor/blob/master/examples/example02-useApiDirect.html

**Comment by mlongv** [comment]
Click the text double click in the panel. Can I customize it.
