### ISSUE TITLE
Backspace doesn't work in text fields

### ISSUE THREAD

**Issue by mojprogramista** [nhn/tui.image-editor#472]
**Describe the bug**
Sometimes, after using the lib in Chrome on Mac OS (newsiest) backspace key doesn't work. The console shows errors like in attachment.

**To Reproduce**
1. Use the library, crop an image, leave the lib and go to some textfields
2. Type something and try to remove text
3. See the error

**Expected behavior**
Using backspace shouldn't be related with the library when not using it.

**Screenshots**
<img width="888" alt="Zrzut ekranu 2020-10-26 o 11 10 14" src="https://user-images.githubusercontent.com/57940197/97163019-4ffa7980-1780-11eb-8690-4d19fbd6771d.png">
<img width="1072" alt="Zrzut ekranu 2020-10-26 o 11 10 34" src="https://user-images.githubusercontent.com/57940197/97163027-51c43d00-1780-11eb-9e55-682ae4f4dca6.png">
<img width="990" alt="Zrzut ekranu 2020-10-26 o 11 12 54" src="https://user-images.githubusercontent.com/57940197/97163031-52f56a00-1780-11eb-8ac6-06932e37a989.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser Chrome
 - Version 86.0.4240.1111

**Comment by jinwoo-kim-nhn** [comment]
It cannot be reproduced. Reproducing using a tool like codepen will help to solve it.

![Oct-28-2020 11-16-07](https://user-images.githubusercontent.com/35218826/97382590-0ab88200-190f-11eb-9cac-4e6db7dae29d.gif)
