### ISSUE TITLE
Custom menu : when I add icon it does not draw anything

### ISSUE THREAD

**Issue by mersimbakalli** [nhn/tui.image-editor#478]
I have implemented Toast Photo Editor to Filemaker and I want to create a menu with only some functions like drawing, icon, tex. 
Only the chosen menu shows but icon does not draw anything to canvas. When I use the full menu, it works well.

Any idea?

**Comment by lja1018** [comment]
I'm sorry for the late response by mistake. I'll fix this bug soon. Thanks!

**Comment by lja1018** [comment]
@mersimbakalli 
Sorry for the late reply by mistake. I can't reproduce this bug.
Can you repost this issue with detail environment? Thank!
