### ISSUE TITLE
Is there a reson for the ui.activeMenuEvent() function being ignored by the dockblocks and not in the UI interface?

### ISSUE THREAD

**Issue by yoieh** [nhn/tui.image-editor#479]
**Summary**
Had the same issue as here https://github.com/nhn/tui.image-editor/issues/477 but with the react wrapper.
If you do `loadImageFromURL` or `loadImageFromFile` you need to run `ui.activeMenuEvent()` to enabel the ui.

But its mission from the docs and missing from the UI interface.

**Version**
v.3.10.0

**Additional context**
Also using the react wrapper if its just an issue from wrappers.
Seems to be the same in Angular haven't tested in nativ js.

**Comment by lja1018** [comment]
Please write down the issue in detail and create it again.
