### ISSUE TITLE
Hide some features

### ISSUE THREAD

**Issue by PierreKoung** [nhn/tui.image-editor#480]
How to hide some features on the editor when using the wrapper ? i try this : 
`includeUI: {
            loadImage: {
                path: window.URL.createObjectURL(this.image),
                name: 'event'
            },
            menu: ['shape', 'crop'],
            menuBarPosition: 'bottom'
        },
        cssMaxWidth: 700,
        cssMaxHeight: 500,
        selectionStyle: {
            cornerSize: 20,
            rotatingPointOffset: 70
        }`

but it doesn't work

i also try this : `this.editorComponent.editorInstance.ui.options.menu = ['shape', 'crop'];`
But it doesn't work. So i don't know if it exist another way to do that.

And it's also not possible to show only the desired sub functionnalities of any buttons. per example show only Grayscale on the filter button.
![image](https://user-images.githubusercontent.com/44596656/98104147-57afd180-1e96-11eb-9b76-ae60d711fcc4.png)

**Comment by yoieh** [comment]
How do you run:

```
new ImageEditor();
```

You have to set the options there as  the second argument.

**Comment by PierreKoung** [comment]
> How do you run:
> 
> ```
> new ImageEditor();
> ```
> 
> You have to set the options there as the second argument.

I tried that but nothing. this is what i do : 

`const instance = new ImageEditor(document.querySelector('#tui-image-editor'), {
        includeUI: {
            loadImage: {
                path: window.URL.createObjectURL(this.image),
                name: 'event'
            },
            menu: ['shape', 'crop'],
            menuBarPosition: 'bottom'
        },
        cssMaxWidth: 700,
        cssMaxHeight: 500,
        selectionStyle: {
            cornerSize: 20,
            rotatingPointOffset: 70
        }`

But even with thin all the menu still appears in the editor

**Comment by PierreKoung** [comment]
I already have the same problem
