### ISSUE TITLE
is it possible to change border color of cropzone?

### ISSUE THREAD

**Issue by stevenencar** [nhn/tui.image-editor#485]
**Summary**
I want to set the line color of crop zone. 

https://nhn.github.io/tui.image-editor/latest/ImageEditor
there is an option , named 'borderColor' , in 'SelectionStyle'. 
but I can't find any changes with it.

**Screenshots**
![screenshot_border_color](https://user-images.githubusercontent.com/66937096/98634564-e1641100-2366-11eb-8408-16c424474b43.png)

**Version**
3.9.0

**Additional context**
- PR
https://github.com/nhn/tui.image-editor/pull/484

**Comment by stevenencar** [comment]
https://github.com/nhn/tui.image-editor/pull/484

**Comment by lja1018** [comment]
The cropzone is not an feature to decorate an image like a `shape` or `icon`, but an feature that helps decorate it, so it does not apply the `selectionStyle` option.

**Comment by stevenencar** [comment]
> The cropzone is not an feature to decorate an image like a `shape` or `icon`, but an feature that helps decorate it, so it does not apply the `selectionStyle` option.

![screenshotWhiteline](https://user-images.githubusercontent.com/66937096/98772260-b098e000-2429-11eb-9967-c36d0f75ac03.png)

How can I change the line color? , it offers only white...

**Comment by lja1018** [comment]
@stevenencar 
We are going to add an option to apply `selectionStyle` to cropzone's `selectionStyle`. Can I continue working on your PR (#484)?

**Comment by stevenencar** [comment]
> @stevenencar
> We are going to add an option to apply `selectionStyle` to cropzone's `selectionStyle`. Can I continue working on your PR (#484)?

@lja1018  yes,sure. and Thanks. I really need it :)

**Comment by qiphon** [comment]
hope setSelectionStyle can use in it
