### ISSUE TITLE
Issue in changing corner properties

### ISSUE THREAD

**Issue by OculusMode** [nhn/tui.image-editor#49]
## Version
Any

## Development Environment
Any
## Current Behavior
I'm trying to change corner details in your js file.
However all the other changes are working except **cornerSize** .
How can i fix it? 

I found that you are using very older version of fabric.
Will upgrading fabric will work in this situation.?

And as a feature request, can you add a method to change corner properties in next update?

Looking forward for response.

tui-image-editor.js line: 3865
```
fObjectOptions: {
	        SELECTION_STYLE: {
	            borderColor: 'red',
	            cornerColor: 'green',
	            cornerSize: 10,
	            originX: 'center',
	            originY: 'center',
	            transparentCorners: false
	        }
	    },
```

**Comment by jinwoo-kim-nhn** [comment]
@OculusMode 

Fabric version up will not have much effect right now.
I've confirmed that the `selectionStyle` option exists but does not work now.
I will fix this and include it in the next distribution.

**Comment by OculusMode** [comment]
@jinwoo-kim-nhn thanks for reply, i just found out that while creating instance, i specified cornerSize which overridden size specified in tui-image-editor.js

```
imageEditor = new ImageEditor(document.querySelector("#myImageEditor"), {
        cssMaxWidth: 700,
        cssMaxHeight: 500,
        selectionStyle: {
          cornerSize: size,
          rotatingPointOffset: 70
        }
      });
```

Still problem is, if image is larger, then the corner seems very small. 
i can figure out dynamically size of corner by calculating imageHeight and width you give after loading image but can't figure out how to set it(after instance is already created.)

**Comment by jinwoo-kim-nhn** [comment]
@OculusMode 
I already have it in mind.
We are considering a fundamental solution.
The dynamically changing options also look good.

**Comment by awwaiid** [comment]
What happened with this? It seems like the corners are still scaling with the image size.
