### ISSUE TITLE
Can not hide some features

### ISSUE THREAD

**Issue by PierreKoung** [nhn/tui.image-editor#499]
How to hide some features on the editor when using the wrapper ? i try this :
`includeUI: { loadImage: { path: window.URL.createObjectURL(this.image), name: 'event' }, menu: ['shape', 'crop'], menuBarPosition: 'bottom' }, cssMaxWidth: 700, cssMaxHeight: 500, selectionStyle: { cornerSize: 20, rotatingPointOffset: 70 }`

but it doesn't work

i also try this : `this.editorComponent.editorInstance.ui.options.menu = ['shape', 'crop'];`
But it doesn't work. So i don't know if it exist another way to do that.

And it's also not possible to show only the desired sub functionnalities of any buttons. per example show only Grayscale on the filter button.

![question](https://user-images.githubusercontent.com/44596656/101487896-1f9d2200-395f-11eb-8dca-c8b5948c2a8a.png)

**Comment by lja1018** [comment]
I applied that option in our vue-wrapper and it worked fine.

![스크린샷 2020-12-09 오전 11 50 27](https://user-images.githubusercontent.com/28647773/101567740-bc6dc700-3a14-11eb-881d-810a1c09f1d5.png)

I would appreciate if you could upload your detail environment.
In addition, there are currently no submenu options, but I'am reviewing them positively.

**Comment by lja1018** [comment]
@PierreKoung 
I applied that option in our vue-wrapper and it worked fine.

![스크린샷 2020-12-09 오전 11 50 27](https://user-images.githubusercontent.com/28647773/101567740-bc6dc700-3a14-11eb-881d-810a1c09f1d5.png)

I would appreciate if you could upload your detail environment.
In addition, there are currently no submenu options, but I'am reviewing them positively.

**Comment by PierreKoung** [comment]
> @PierreKoung
> I applied that option in our vue-wrapper and it worked fine.
> 
> ![스크린샷 2020-12-09 오전 11 50 27](https://user-images.githubusercontent.com/28647773/101567740-bc6dc700-3a14-11eb-881d-810a1c09f1d5.png)
> 
> I would appreciate if you could upload your detail environment.
> In addition, there are currently no submenu options, but I'am reviewing them positively.

I am using angular 10 with typescript.
Please can you show me how you write it in the wrapper ?
And how to also limit submenu options ?

**Comment by PierreKoung** [comment]
Because I still writing that code but it doesn't work. Note that I use Angular IO 10 with typescript so this is my way to limit options :
`this.editorComponent.editorInstance.ui.options.menu = ['shape', 'crop'];`

**Comment by lja1018** [comment]
Sorry. Our wrappers are only vue and react, and angular has no development plans yet.

**Comment by lja1018** [comment]
@PierreKoung 
Testing was done in our vue wrapper and ran with the options you wrote down. There are no sub-menu options yet.
Sorry. Our wrappers are only vue and react, and angular has no development plans yet.
