### ISSUE TITLE
Crop properties lost ? 

### ISSUE THREAD

**Issue by paulolafoudre** [nhn/tui.image-editor#501]
**Describe the bug**
Cannot read property set of null on Crop

After adding a shape => i am not able to do a crop without bugs

**To Reproduce**

1. Add a circle
2. add a crop
3.

![image](https://user-images.githubusercontent.com/47225096/101878598-23fc5180-3b90-11eb-8c6e-470b3eb24b99.png)

**Expected behavior**
Same as the basic example.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome 
- Version 87

**Additional context**
I am using library method and implementing my own interface

**Comment by lja1018** [comment]
First of all, thank you for posting the issue.

I tried to reproduce the issue, but it is impossible to reproduce as shown in the screenshot below. We would appreciate it if you post the issue again with details.

(Screenshot with cropping executed)
![스크린샷 2020-12-16 오전 11 04 41](https://user-images.githubusercontent.com/28647773/102295351-8093ae00-3f8e-11eb-8f6b-c7c4383695d4.png)

**Comment by lja1018** [comment]
@paulolafoudre 

First of all, thank you for posting the issue.

I tried to reproduce the issue, but it is impossible to reproduce as shown in the screenshot below. We would appreciate it if you post the issue again with details.

(Screenshot with cropping executed)
![스크린샷 2020-12-16 오전 11 04 41](https://user-images.githubusercontent.com/28647773/102295351-8093ae00-3f8e-11eb-8f6b-c7c4383695d4.png)

**Comment by maleSun** [comment]
Describe the bug
Cannot read property set of null on Crop

using library method  **startDrawingMode**

> `this.instance!.startDrawingMode('CROPPER');`

like  [http://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect]( Use api direct )
the code  eg.1 eg.2  It's all wrong

![捕获2](https://user-images.githubusercontent.com/35056649/119524049-dc6d2900-bdaf-11eb-9271-b1da55ae5884.PNG)
![捕获](https://user-images.githubusercontent.com/35056649/119524048-dc6d2900-bdaf-11eb-811e-a067f8031b18.PNG)
![捕获3](https://user-images.githubusercontent.com/35056649/119524057-dd9e5600-bdaf-11eb-8e9f-278fbb87f6b3.PNG)
