### ISSUE TITLE
Pressing backspace key in hex color picker deletes the selected shape instead of hex code text

### ISSUE THREAD

**Issue by miduff** [nhn/tui.image-editor#504]
**Describe the bug**
When editing the color of a shape, the color picker shows the hex code of the current color and the user is able to edit that text string to get the color they want. However, if the user presses the backspace key to delete part of the string, the shape is deleted instead.

**To Reproduce**

1. Add a shape
2. Click on Stroke to open color picker
3. Click on hex code string to edit
4. Press backspace key
5. Notice shape is deleted and hex code string remains unchanged. Pressing the backspace key again edits the string as expected.

**Expected behavior**
Backspace key would delete characters in the hex code string, where the text cursor is located. Shape should not be deleted.

**Screenshots**
![color-edit-delete-issue](https://user-images.githubusercontent.com/76134395/102418192-dda95700-3fc2-11eb-9309-3b8c50051f01.gif)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 87.0.4280.88

**Additional context**
This can be reproduced using the image editor on https://ui.toast.com/tui-image-editor

**Comment by lja1018** [comment]
@miduff 
Thanks for the bug report. I will fix it as soon as possible.
