### ISSUE TITLE
how can i change a arrowLine's or freeDrawing's color and lineWidth with ImgEditor API 

### ISSUE THREAD

**Issue by qiphon** [nhn/tui.image-editor#505]
i am using IMGEDITOR in my work now.
i want to change a line 、freeDrawing's width or color . 
i am not find a api for these. so i think you can add it at someday. thanks

**Comment by lja1018** [comment]
@qiphon 
If you have reported on the API that changes the color or width of `free_drawing`, you can use the `setBrush()` API of the image-editor ([example](https://nhn.github.io/tui.image-editor/latest/ImageEditor#setBrush)).
Thank you.
