### ISSUE TITLE
Using the Image editor in a React TS project causes bugs when initing the component

### ISSUE THREAD

**Issue by Chestly** [nhn/tui.image-editor#506]
**Summary**
When using the Toast Image editor in React Typescript initing throws the following error: 
```
TypeError: Cannot call a class as a function
    at _classCallCheck (imageEditor.js:47)
    at ImageEditor (imageEditor.js:194)rror
```
[Here](https://paste.helpch.at/aberufeguh.js) (TS not JS) is the component where i open the image editor(It is a dialogue so everything works till it is opened and the ImageEditor is inited)

I had issues importing the `ImageEditor` component initially(with the NPM installation) and no example really showed how to do it, eventually i did : `const ImageEditor = require('tui-image-editor');` which i couldn't find listed. Not sure if this is correct or will cause issues. My end question is; how to fix this or if its a bug then id like to make sure you guys know about it!

Thanks!

Btw, I would suggest creating a Discord or something along those lines for better community support and faster communication as i know most people dont check github as much as they check discord!

**Screenshots**
Screenshot of the stacktrace: https://imgur.com/hD7e3zP
Video showing the issue: https://imgur.com/TXGc7tN

**Version**
Latest(3.11.0)

**Additional context**
React Typescript Webkit

**Comment by Chestly** [comment]
Adding to this, I have tested it in multiple environments and gotten the same results.

**Comment by lja1018** [comment]
@Chestly 
Thank you for your report.
It seems to be using the image-editor application, not the react wrapper. Would you like to use the image-editor react wrapper?

**Comment by Chestly** [comment]
Huh, Ill try it out thanks! I havent been able to find a reference to that anywhere besides in the ReadME, thanks for the help anyway!

**Comment by Chestly** [comment]
Still not working, Im getting this error when creating the ImageEditor Component
```error
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Here is my component.
```ts
export default function App() {
  const editorRef = React.createRef();

  return (
    <div className="App">
      <ImageEditor 
          ref={editorRef}
        />
   </div>
  );
}

**Comment by Chestly** [comment]
@lja1018 Hey, Ive still been having issues, I went to a straight JS example, no TS, nothing fancy except importing and using the Editor as as component. Here is my code: 
```js
import React from "react";
import "./styles.css";
import "tui-image-editor/dist/tui-image-editor.css";
import ImageEditor from "@toast-ui/react-image-editor";

export default function App() {
  const myTheme = {
    // Theme object to extends default dark theme.
  };

  return (
    <div className="App">
      <ImageEditor
      includeUI={{
        loadImage: {
          path: 'img/sampleImage.jpg',
          name: 'SampleImage'
        },
        theme: myTheme,
        menu: ['shape', 'filter'],
        initMenu: 'filter',
        uiSize: {
          width: '1000px',
          height: '700px'
        },
        menuBarPosition: 'bottom'
      }}
      cssMaxHeight={500}
      cssMaxWidth={700}
      selectionStyle={{
        cornerSize: 20,
        rotatingPointOffset: 70
      }}
      usageStatistics={true}
    />
    </div>
  );
}
```
This is literally the **exact** example they shows with the Image editor and the error that is being throw has been attached as a video below.

https://user-images.githubusercontent.com/62190905/103501415-f909c400-4e02-11eb-94f7-3103b9f716bc.mov

And yes, This isnt an issue with the index as its the default one that CodeSandbox generates on creating a react-js project.
