### ISSUE TITLE
Image-Editor as ReactJS Component

### ISSUE THREAD

**Issue by hheckner** [nhn/tui.image-editor#51]
## Version
3.2.0
## Development Environment
ReactJS, HTML5

## Current Behavior
We would like to use your component in our app. But we would need it as a ReactJS Component. Are you interested in providing a basic component which basically wraps the whole thing?
```js
// Write example code
```

## Expected Behavior
Integrate the Image-Editor as a ReactJS Component in our mobile app.

**Comment by humblecoder** [comment]
I'd be interested in the same -- but as a VueJS component.

**Comment by Liklei** [comment]
I hope so , as a VueJS component

**Comment by junghwan-park** [comment]
Check this out. https://github.com/nhn/toast-ui.react-image-editor
