### ISSUE TITLE
How to modify the editor rotation default 30 degrees, I want the default rotation 90 degrees

### ISSUE THREAD

**Issue by dengzhixin** [nhn/tui.image-editor#510]
Hi~

How to modify the editor rotation default 30 degrees, I want the default rotation 90 degrees

Thanks！
**Screenshots**
https://imgur.com/jDkjpii

**Version**
Latest(3.11.0)

**Comment by lja1018** [comment]
@dengzhixin 
There is no way to specify a default 90 degrees in the tui-image-editor. Please use the input box.
Thank you!

**Comment by dengzhixin** [comment]
thank you~
