### ISSUE TITLE
Documentation missing for server side integration

### ISSUE THREAD

**Issue by nikto1** [nhn/tui.image-editor#513]
It's possible, but there's no documentation about it.
Please add it for other users.
Great thanks

**Comment by lja1018** [comment]
I'll add it later. Thanks for the report!

**Comment by lja1018** [comment]
Does this [link](https://docs.dhtmlx.com/form__server_side.html) mean the `server side integration` you're talking about?

**Comment by nikto1** [comment]
I'm talking about once the image edition is done, instead of saving the image as a blob there should be some documentation on how to save an image in a physical folder with the imagae name in a DB.
I think i'm not the only one who was searching for it.
Btw, great thanks anyway for the plugin.

**Comment by azakero** [comment]
> I'm talking about once the image edition is done, instead of saving the image as a blob there should be some documentation on how to save an image in a physical folder with the imagae name in a DB.
> I think i'm not the only one who was searching for it.
> Btw, great thanks anyway for the plugin.

Hey I'd like to know about that as well. I'm trying it out for a NodeJS/Express app.

**Comment by nikto1** [comment]
@azakero basically you need to modify the "saving blob part" of the plugin and rewrite the code so it gets send to server side e.g. convert the canvas to a base64 string, convert the latter to an image, then send it to the server. 
Cannot help you too much as i'm using an older version of the editor where a big part has been rewritten.

**Comment by azakero** [comment]
@nikto1 Thank you. I'll give it a try later today. Hope I can manage it myself with the info you have provided. Or else I'll create an issue here for the creators to help me out. But thank you mate. Big help.
