### ISSUE TITLE
Undo redo button hide after draw line 

### ISSUE THREAD

**Issue by KrishnaAgola** [nhn/tui.image-editor#516]
**Describe the bug**
Undo Redo button disappear after draw line same with delete button also hide after any shape used

it will display on load but when drawing line used undo redo button hide it display on hover

public imageEditorOptions: any = {
    usageStatistics: false,
    includeUI: {
      loadImage: {
        path: 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
        name: 'Blank'
      },
      menu: ['text', 'shape', 'draw', 'crop'],
      theme: myTheme,
    }
};

HTML:
<tui-image-editor [options]="imageEditorOptions"></tui-image-editor>

Please any one help me out on these  let mw know for solution

**Comment by lja1018** [comment]
@KrishnaAgola 
I don't understand this bug report. Could you please write a detailed step?
