### ISSUE TITLE
Undoing selection changes causes selected objects to shift in screen

### ISSUE THREAD

**Issue by fjwong** [nhn/tui.image-editor#522]
**Describe the bug**
When you select two or more objects in canvas, and either move them or scale them, then hit 'Undo', the objects shift towards the lower right corner of the canvas.

**To Reproduce**

1. Go to https://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect
2. Draw any two objects.
3. Click 'Close' to go back to selection mode.
4. Drag a square to select both objects.
5. Move or scale the object selection.
6. Click 'Undo'
7. The selected objects are shifted to the lower right, instead of going back to the previous state.

**Expected behavior**
* Objects in the selection are returned to their previous state when undoing the changes.

**Screenshots**

Two objects drawn in canvas:
![Screen Shot 2021-02-04 at 15 25 20](https://user-images.githubusercontent.com/1836719/106853667-6ad47680-66fd-11eb-8f18-88f3e0264e48.png)

After selection and scaling:
![Screen Shot 2021-02-04 at 15 25 33](https://user-images.githubusercontent.com/1836719/106853677-6f992a80-66fd-11eb-80ca-4a8597ebe16e.png)

After clicking 'Undo' (Note that the selection rectangle stays in the same position):
![Screen Shot 2021-02-04 at 15 25 48](https://user-images.githubusercontent.com/1836719/106853680-7031c100-66fd-11eb-91d8-3219f68d4c6e.png)

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Chrome
- Version: 88.0.4324.96 (Official Build) (x86_64)

**Additional context**
If you deselect the objects after step 5, and click 'Undo', the problem does not happen.

**Comment by lja1018** [comment]
@fjwong 
I understand this issue. Thank you for your detailed report. I'll handle it.

**Comment by lja1018** [comment]
@fjwong 
Thanks for the report. Resolved in [v3.13.0](https://github.com/nhn/tui.image-editor/releases/tag/v3.13.0).
