### ISSUE TITLE
Hand and eraser tools in menu

### ISSUE THREAD

**Issue by mbasirati** [nhn/tui.image-editor#550]
I need hand tool for drag image after zoom in.
And also I need eraser tool for erase some drawing line on image.
Are there these facilities in tui image editor?
Thanks in advance.

**Comment by lja1018** [comment]
@mbasirati 
Thanks for the feature suggestions.
The `hand` feature was added along with the `zoom` function in [v3.14.0](https://github.com/nhn/tui.image-editor/releases/tag/v3.14.0).
The `eraser` feature seems to be a really nice feature. After discussion, I will register it as a to-do later.
Thank you.
