### ISSUE TITLE
Distribution files for 3.13.0 and 3.12.0 incorrect

### ISSUE THREAD

**Issue by JohntheFish** [nhn/tui.image-editor#551]
Downloading tui.image-editor-3.13.0.zip (or 3.12.0) contains /dist/ files for version 3.11.0.

**Comment by lja1018** [comment]
@JohntheFish 
Thanks for the report. The file has been deleted from the current latest version([v3.14.0](https://github.com/nhn/tui.image-editor/releases/tag/v3.14.0)).

**Comment by JohntheFish** [comment]
While it is consistent, 3.14.0 does not resolve the problem. There is no no built editor in the distribution such as tui-image-editor.js

**Comment by lja1018** [comment]
@JohntheFish 
Distribution file is located in `/apps/image-editor/dist/`.
