### ISSUE TITLE
Filters check boxes are still checked on Reset

### ISSUE THREAD

**Issue by vladsovetov** [nhn/tui.image-editor#552]
**Describe the bug**
Reset action only resets the filters on the preview, but filters' check boxes are still checked. So to apply the same filter you should uncheck it and then check it again

**To Reproduce**

1. Go to http://nhn.github.io/tui.image-editor/latest/tutorial-example01-includeUi
2. Click on the Grayscale filter checkbox
3. Click on Reset action

**Expected behavior**
The Grayscale filter checkbox is unchecked

**Screenshots**
The Grayscale filter checkbox is still checked, while the filter itself was cleared on the preview

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser Chrome
- Version 88.0.4324.96 (Official Build) (64-bit)

**Comment by lja1018** [comment]
@vladsovetov 
Thanks for the bug report. I will resolve it ASAP.
