### ISSUE TITLE
Text control exits when space key pressed

### ISSUE THREAD

**Issue by JohntheFish** [nhn/tui.image-editor#555]
**Describe the bug**
In the text control, when a space character is entered the text tool exits. In 3.11.0 the text tool worked as expected. In 3.14.0, this bug happens.

**To Reproduce**
1. Go to http://nhn.github.io/tui.image-editor/latest/tutorial-example01-includeUi and use the example editor
2. Click on the 'T' Text tool
3. Enter "Any Text"
4. The text "Any" is entered correctly. When the space key is pressed the control exits (new bug in 3.14.0)

**Expected behavior**
4. Expect "Any Text" to enter correctly. When the space key is pressed, a space is entered (works in 3.11.0)

**Screenshots**

**Desktop (please complete the following information):**

- Chrome 
- 89

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lja1018** [comment]
@JohntheFish 
Thanks for the report. I have confirmed the bug and will resolve it ASAP.

**Comment by lja1018** [comment]
@JohntheFish 
Resolved in [v3.14.1](https://github.com/nhn/tui.image-editor/releases/tag/v3.14.1). Thank you.
