### ISSUE TITLE
toDataURL get zoomed image but I need entire image

### ISSUE THREAD

**Issue by mbasirati** [nhn/tui.image-editor#562]
I wrote below code to send edited image to server:
```
$('#btn-save-image').on('click', function (e) {
	
	var blob = imageEditor.toDataURL();
	var formData = new FormData();
	formData.append('base64Image', blob);
	$.ajax({
		url: '@Url.Action("SaveEditedImage")', // upload url
		type: "POST",
		data: formData,
		processData: false,
		contentType:false,
		success: function (data) {
			showmessage(data);
		},
		error: function () {
			alert('UPLOAD FAILED, PLEASE TRY AGAIN...');
		},
		complete: function () {
			showLoading(false);
		}
	});

	return false;
});
```
But this code send image with zoom, in the other word `toDataUrl` cropped my image to zoomed area. But I need to send entire image to server.
Is this a bug or there is something that I don't know?

**Comment by Al-hamed-Mohammed** [comment]
todataurl only send 150 * 300 image I also want to send entire image

**Comment by lja1018** [comment]
@mbasirati @Al-hamed-Mohammed 
Do you want to try the 'resetZoom' API?

**Comment by mbasirati** [comment]
> @mbasirati @Al-hamed-Mohammed
> Do you want to try the 'resetZoom' API?

Thank you. I used `restZoom` before saving and my problem solved. :)

**Comment by lja1018** [comment]
The issue has been resolved and closed.

**Comment by mo-shaz** [comment]
> > @mbasirati @Al-hamed-Mohammed
> > Do you want to try the 'resetZoom' API?
> 
> Thank you. I used `resetZoom` before saving and my problem solved. :)

Hey there, I'm facing the same issue and used the resetZoom but it seems to be not working.
