### ISSUE TITLE
Click Download, Prevent Download, do something and reinitiate Download with edited image

### ISSUE THREAD

**Issue by privyreza** [nhn/tui.image-editor#565]
**Summary**
I am failing to stop the download and retrigger it after image watermark is complete. When i click download I want to watermark and download the image. The following is the route i took ( Feel free to suggest a better ):

1. Stop the download
2. Save the image on server and watermark it
3. Load watermarked image into canvas
4. Re-trigger Download after watermark is done. Below is the code but it seem to download the un-watermarked image right away.

```$(document).ready (function () {
          $('.tui-image-editor-download-btn').click(function(e) {
            e.preventDefault();
            var watermarked = false;

            // Save to folder
            // Watermark
            // Add Load the to canvas 
            // Then trigger download
            var blob = dataURLtoBlob(imageEditor.toDataURL());
            var formData = new FormData();
            formData.append('croppedImage', blob, 'testwatermark.png');
            /**
             * Uploading to folder
             */
            if (! watermarked) {
              $.ajax({
                type: 'POST',
                url: 'post_image1',
                enctype: 'multipart/form-data',
                processData: false,
                contentType: false, 
                data: formData,
                success: function (data) {
                    // Now watermark
                    // watermark by local path
                    watermark(['uploads/testwatermark.png', 'assets/front/img/logo.png'])
                      .image(watermark.image.upperLeft(0.5))
                      .then(img => {
                        // Reload watermarked image
                        imageEditor.loadImageFromURL(img.src, 'My Image');
                      });

                      watermarked = true; // Now watermarked
                },
                error: function (data) {
                    console.log('An error occurred.');
                    console.log(data);
                },
            });
            } else {
              // Download Image
              // e.trigger();
            }
        }) 
      })```

**Comment by haiduong87** [comment]
@privyreza 
Where did you put that code block?
I ask because I want to do the same thing.

And with your code requirement. I have some concerns
- Are you sure you can do "e.preventDefault()". If we can't we always get the un-watermarked image
- And I think "watermarked" variable is always false each time you click download.

While don't you try modify the library to add your custom download logic.

I need this behavior too, actually I have a local version that apply "custom download logic" and it seems fine.
I may submit a PR, I saw other issues about this behavior

Duong Nguyen

**Comment by lja1018** [comment]
@privyreza @haiduong87 
Thank you for the question. I think the problem is that the `watermarked` variable is always false.

**Comment by lja1018** [comment]
@haiduong87 
I'm sorry for the late reply.
I'll review the PR.
