### ISSUE TITLE
Custom crop presets

### ISSUE THREAD

**Issue by ziga-miklic** [nhn/tui.image-editor#567]
## Version

3.14.2

## Development Environment

**Browser:** Chrome (89.0.4389.90)
**OS:** Windows 10 (Version 10.0.19041 Build 19041)

## Current Behavior

Currently, the crop functionality inside the image editor has the following presets: Square, 3:2, 4:3, 5:4, 7:5, and 16:9. The current API does not allow changing these presets.

## Expected Behavior

An ability to change the presets on the UI options object.

## Making the change

We are using the Toast UI Image Editor in our app and it is fantastic! Thank you for all the work you have done.

If we create a PR with the ability to change the crop presets, would you consider merging it into the project? Do you think the feature is something other users would find useful?

Thank you!

**Comment by lja1018** [comment]
@ziga-miklic 
Sorry for the late reply. This proposal looks similar to #125 and #350. This option is currently being prepared and will be updated to complete. Thank you!

**Comment by ziga-miklic** [comment]
Thank you for responding @lja1018 That is great news!

I look forward to checking out the changes once they are available. Keep up the great work!

**Comment by wenjing-pure** [comment]
Any updates？

**Comment by lja1018** [comment]
@wenjing-pure 
Sorry. There's no update.
