### ISSUE TITLE
Disable added text field

### ISSUE THREAD

**Issue by shubhwebkul** [nhn/tui.image-editor#571]
How to disable the text field to be changed for the user? How can I make that string static?

Also, the width under style is not working while adding the text.

```
this.$refs.editor.invoke('addText', 'Static String', {
    styles: {
        fill            : '#FFF',
        fontSize        : 30,
        fontWeight      : 'bold',
        width           : '100px',
        backgroundColor : '#000',
    },
    position: {
        x: 95,
        y: 90
    }
});
```

**Comment by lja1018** [comment]
@shubhwebkul 
Thank you for the information.
First, for non-editable text, you can implement it using the option `editable: false`.
```js
styles: {
  ...
  editable: false,
}
```
Second, I will resolve the `width` option after checking.

**Comment by shubhwebkul** [comment]
@lja1018 Thanks for the update, editable key is working fine.

I've one more query. In the current scenario, the height is fixed on the canvas. How can I make that according to the height of the image?

**Comment by shubhwebkul** [comment]
Hi

any update ?

**Comment by lja1018** [comment]
@shubhwebkul 
Sorry for the late reply.
Do you mean to match the height of the canvas to the height of the image?

**Comment by shubhwebkul** [comment]
@lja1018 yes.

**Comment by lja1018** [comment]
@shubhwebkul 
I'm sorry for the late reply.
In the current image, the data does not show the size of the image as it is, but has the maximum size depending on the `cssMaxWidth` and `cssMaxHeight` options.

**Comment by AaravShah042** [comment]
editable: false is not working
