### ISSUE TITLE
Support for these filters Hue, Saturation, Ink, Denoice

### ISSUE THREAD

**Issue by privyreza** [nhn/tui.image-editor#573]
**Summary**
Support for these filters Hue, Saturation, Ink, Denoise, or the possibility to use a third party library like https://evanw.github.io/glfx.js/demo/

**Additional context**
Hi guys, thanks for the wonderful image editing tool. 
1. I was wondering if there is a way to activate these filters : 

- Hue
- Saturation
- Ink
- Denoise

2. If not, is there a possibility that I can integrate a third party library like https://evanw.github.io/glfx.js/demo/ to add additional filters?

Kindly assist, thank you!

**Comment by lja1018** [comment]
@privyreza 
Thank you for the feature proposal.
There is currently no way to activate these filters and no way to add them...
However, we will review the proposal positively.

**Comment by privyreza** [comment]
Thank you for the feedback! Do you have some pointers on how I can activate these filters?

I also saw that the library uses some filters from fabrics.js, and was wondering how I can activate Saturate as this is already on the library, at least I will worry about adding the remaining 3

**Comment by lja1018** [comment]
@privyreza 
I'm sorry for the late reply.
Currently, there is no way to add or activate filters externally.
