### ISSUE TITLE
React JS mobile version

### ISSUE THREAD

**Issue by bernardbaker** [nhn/tui.image-editor#577]
Hi @kyuwoo-choi

**Summary**
I'd like to use this library in a React JS app on a mobile device. Is this possible?

**Comment by lja1018** [comment]
@bernardbaker 
Thank you for your question.
`tui-image-editor` supports mobile. ([Mobile example page](https://nhn.github.io/tui.image-editor/latest/tutorial-example03-mobile))

**Comment by bernardbaker** [comment]
> @bernardbaker 
> Thank you for your question.
> `tui-image-editor` supports mobile. ([Mobile example page](https://nhn.github.io/tui.image-editor/latest/tutorial-example03-mobile))

@lja1018 but how do I implement it? I couldn't find any instructions.

**Comment by lja1018** [comment]
@bernardbaker 
I'm sorry for the late reply.
I think you can use [`React Wrapper`](https://github.com/nhn/tui.image-editor/tree/master/apps/react-image-editor).

**Comment by bernardbaker** [comment]
@lja1018 where is React Wrapper. The link goes to the source code.

**Comment by adhrinae** [comment]
@bernardbaker You can see the README file when you click the link above.
Please check out [this section](https://github.com/nhn/tui.image-editor/tree/master/apps/react-image-editor#-install) again.
