### ISSUE TITLE
Disable double click on Text Menu.

### ISSUE THREAD

**Issue by 1shivsharma1** [nhn/tui.image-editor#579]
**Summary**
Is there any way to disable adding 'Double Click' text on the image editor on the text menu?

**Screenshots**
![image](https://user-images.githubusercontent.com/82382088/114547837-92573a80-9c7c-11eb-9dda-68faa10cc84f.png)

**Version**
3.12.0

**Comment by lja1018** [comment]
@1shivsharma1 
Thank you for your question.
There is currently no way to prevent the addition of 'double click' text objects without closing the `text` menu.

**Comment by 1shivsharma1** [comment]
Hi @lja1018 ,
Can you add some way to disable this, as the addText method is already available in the package.
or is there any way to override this method
Thanks

**Comment by lja1018** [comment]
@1shivsharma1 
I don't understand the question. Would you explain in detail?

**Comment by 1shivsharma1** [comment]
@lja1018 ,
Can we disable "Double Click" text on the mouse double click on the text menu?
I am using AddText method to adding text in canvas, so not needed double click on it.

**Comment by lja1018** [comment]
@1shivsharma1 
Are you using the `includeUI` option?
With the UI provided, text `drawingMode` will work when the text menu is opened, adding text.
You can turn off `drawingMode` after opening the text menu.

**Comment by 1shivsharma1** [comment]
@lja1018 
Thank you for your response.
This works for me.

Thanks

**Comment by AaravShah042** [comment]
@1shivsharma1  Will you please provide a example?
