### ISSUE TITLE
How do we manually edit currently active text object?

### ISSUE THREAD

**Issue by humblecoder** [nhn/tui.image-editor#58]
What is the current mechanism by which we set the currently active text object to `edit`?  In the example we can double-click and make the object editable.  How do we do this in practice? 

I get that we "catch" the active object via `objectActivated`, but I see nowhere in the documentation anything regarding a text cursor or otherwise.  I've also looked at the source of the sample projects, but I see nothing that stands out.  Clearly I've overlooked something.  🤔

**Comment by humblecoder** [comment]
When attempting to double-click and "activate" the text object, I receive the following error in the console.

![screen shot 2018-09-21 at 6 33 07 pm](https://user-images.githubusercontent.com/913539/45908897-f408de00-bdcc-11e8-87d0-ef6b2d8208fd.png)

I've installed all relevant dependencies.  Surely I'm simply missing something.  Unfortunately, I have **NO** idea what.  🙁

**Comment by humblecoder** [comment]
@OculusMode any insights here?  🤔

**Comment by junghwan-park** [comment]
@humblecoder 
I think you misunderstood about difference between `imageEditor.addText()`API and `imageEditor.on({addText: function() {}})`.

You said [this listener](https://github.com/nhnent/tui.image-editor/blob/master/examples/js/service-basic.js#L314)?
That listener function is added for internal `addText` custom event, not a `imageEditor.addText()`API.

**Comment by humblecoder** [comment]
Hrm, so after a "vanilla" `addText`, how do I go back and edit the text?  What would make `double-click` not respond?
