### ISSUE TITLE
How to get the current active object ?

### ISSUE THREAD

**Issue by darkcris1** [nhn/tui.image-editor#582]
I'm reading all the documentation , I tried to keep track of active object objectActivated event but If I remove my focus to that , the last current active is still there.

**Comment by lja1018** [comment]
@darkcris1 
Thank you for your question. Currently, there are no API available at the `imageEditor` level to obtain active objects. Alternatively, `imageEditor._graphics.getActiveObject()` can be used. I will consider adding it to the imageEditor level.

**Comment by darkcris1** [comment]
Great, but unfortunately the alternative will not work in Typescript.

**Comment by lja1018** [comment]
@darkcris1 
Sorry for the late reply.
Could you upload a TypeScript example?

**Comment by eomttt** [comment]
I think in type definition `imageEditor` has no `_graphics` method
so `Property '_graphics' does not exist on type 'ImageEditor'` error like this

**Comment by ThWelte** [comment]
For everyone who lands here:
imageEditor.on('objectActivated', (element) => {
   console.log('Selected element: ', element.id)
}
