### ISSUE TITLE
How to save edited image to variable instead of downloading it

### ISSUE THREAD

**Issue by TimurAztec** [nhn/tui.image-editor#588]
**Summary**
So basically how do I change "Download" button to "Save"? And how to save edited image to a file variable instead of disc?

**Version**
v3.14.3

**Comment by lja1018** [comment]
@TimurAztec 
Thank you for your question.
First of all, there is no way to change the `Download` text to `Save` text, but I think you can use the `download` API by processing the existing `download` button `display: none;` and adding a custom button.
The second question is, I think you can use the `imageEditor.toDataURL()` API.

**Comment by bmarotta** [comment]
Actual one can change the text to Save, but setting the locale['Download'].

       includeUI: {          
                          (...)
			  locale: {Download: 'Save'},
			},

**Comment by lja1018** [comment]
@bmarotta 
I'm sorry for the late reply.
I will add a way to change the `download` text.
