### ISSUE TITLE
Is it possible to save the state of the editor?

### ISSUE THREAD

**Issue by mbrochh** [nhn/tui.image-editor#592]
This project looks amazing! 

However, in our usecase, we need our users to load a previously manipulated image and continue working on it (ie still be able to move all the shapes around and change colors etc). Just downloading a fully rendered JPG is not very useful.

I'm surprised that this hasn't been a feature right from the beginning as it seems like a very common usecase to me. Is this a hard problem to solve? If it can be solved, are there any plans to implement this in the near future? I might be willing to pay money if this could speed up the implementation of such a feature.

**Comment by lja1018** [comment]
@mbrochh 
Thank you for your question. This feature is similar to #294.
Currently, this feature is in our todolist, but it's a low-priority, demanding feature. We will consider increasing the priority. Thank you.

**Comment by mbrochh** [comment]
OK, I shall close this and observe the other issue. If you would be willing to work on this for a fee, please email me and let me know your hourly rate.
