### ISSUE TITLE
crop 후 이미지 해상도 유지할 수 있나요? 특정영역에만 블러, 모자이크 처리 가능한가요?

### ISSUE THREAD

**Issue by sunny724** [nhn/tui.image-editor#593]
**Summary**
A clear and concise description of what the question is.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the imageEditor you are currently using.

**Additional context**

해상도 높은 이미지를 Crop하고 저장하면 해상도가 낮게 저장됩니다. 
원본의 해상도를 유지하면서 저장하는 옵션이 있는지 궁금합니다. 

또한 사진의 특정 영역 선택 후 블러나 모자이크 처리 하는 기능이 제공되는지 궁금합니다.

**Comment by lja1018** [comment]
@sunny724 
Thank you for the question.
It is a rule to post the issue of `image-editor` in English, so I would appreciate it if you could post it in English next time.
1. We are currently checking the issue of changing the size of the image when saving the image. (#566)
2. The blur feature in certain areas is registered as `Good First Issue` and has not yet been worked on. (#249)
