### ISSUE TITLE
custom like  [http://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect]( Use api direct )

### ISSUE THREAD

**Issue by maleSun** [nhn/tui.image-editor#598]
custom like  [http://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect]( Use api direct )

- Cannot read property set of null on Crop

using library method  **startDrawingMode**,  when I crop by mousemove event
> `this.instance!.startDrawingMode('CROPPER');`
![捕获2](https://user-images.githubusercontent.com/35056649/119525575-328e9c00-bdb1-11eb-80de-83a1fb5eab83.PNG)
![捕获4](https://user-images.githubusercontent.com/35056649/119525576-328e9c00-bdb1-11eb-9f93-07fa952d4164.PNG)
![捕获](https://user-images.githubusercontent.com/35056649/119525577-328e9c00-bdb1-11eb-8585-1f4506eb178d.PNG)
![捕获3](https://user-images.githubusercontent.com/35056649/119525586-33bfc900-bdb1-11eb-8cfc-046b38cc4d82.PNG)

- I try stopDrawingMode before startDrawingMode， and add setCropzoneRect is ok， but I want mouse select area to crop, like menu crop button active

![3](https://user-images.githubusercontent.com/35056649/119527899-5521b480-bdb3-11eb-932e-14b476c620ea.PNG)
![4](https://user-images.githubusercontent.com/35056649/119527928-59e66880-bdb3-11eb-8e92-834a4e2e05ac.PNG)

_Originally posted by @maleSun in https://github.com/nhn/tui.image-editor/issues/501#issuecomment-847965516_

 and  then  apply method crop() is TypeError:  _set of null  from fabric.js  line  9194
![IMG_20210526_103420](https://user-images.githubusercontent.com/35056649/119594380-4df1ab00-bda1-11eb-91e0-1833883a71fa.jpg)

![IMG_20210526_104112](https://user-images.githubusercontent.com/35056649/119594723-f142c000-bda1-11eb-8840-cc8b999312b0.jpg)

**Comment by lja1018** [comment]
@maleSun 
Thank you for your report.
The cause is that cropzone becomes null when removing cropzone from canvas on [Line 270(cropper.js)](https://github.com/nhn/tui.image-editor/blob/master/apps/image-editor/src/js/component/cropper.js#L270).
I will resolve it. If you are in a hurry, please refer to [example02 js](https://github.com/nhn/tui.image-editor/blob/master/apps/image-editor/examples/js/service-basic.js).

**Comment by odex21** [comment]
https://github.com/nhn/tui.image-editor/blob/c53ad079241402f6ac49479ff10a139943979ced/apps/image-editor/src/js/action.js#L650-L657

The submenu is detected here, resulting in the early execution of this.stopDrawingMode.

Emmm, a workaround  is to manually set the `subemenu` to `crop`.

**Comment by Toflyer** [comment]
> 
This problem seems to still exist
