### ISSUE TITLE
How to let setting bar can't cover the image?

### ISSUE THREAD

**Issue by coolman200** [nhn/tui.image-editor#604]
![image](https://user-images.githubusercontent.com/52725981/120594417-7f3e3b00-c473-11eb-8147-3a867bb87eab.png)

How can I let setting can not cover my image ?
can anyone help me ?

Thanks.

**Comment by lja1018** [comment]
@coolman200 
Thank you for your question.
It's the same issue as #205, #338.
We are planning to improve considering usability.

**Comment by Icc-thang** [comment]
Is there any way to fix this?

**Comment by lja1018** [comment]
@Icc-thang 
It hasn't been fixed yet.

**Comment by Breezewrf** [comment]
It hasn't been fixed yet.
