### ISSUE TITLE
Install from NPM not the latest version of plain javascript

### ISSUE THREAD

**Issue by mastercrys** [nhn/tui.image-editor#605]
**Summary**
When install from npm https://github.com/nhn/tui.image-editor/tree/master/apps/image-editor like docs said the latest version is not the real latest version but stuck on wrong commit
This is the content of package.json in node_modules folder
```
...
"gitHead": "497ae682029a9794f1dedd985cf41b2cd898761b"
...
```
**Version**
v3.14.3

**Additional context**
Command executed: ```npm install --save tui-image-editor```

**Comment by lja1018** [comment]
@mastercrys 
Thank you for your question.
I don't quite understand that you don't install the 'latest version'.
Can you explain it in detail?

**Comment by mastercrys** [comment]
When I run npm install --save tui-image-editor in my project I cannot see the resize functionality that has been implemented in this [commit](https://github.com/nhn/tui.image-editor/commit/f627ed27d4e58336cb1b2dc6ef44d6737af89619)

Can you please update the [NPM](https://www.npmjs.com/package/tui-image-editor) repository?

**Comment by lja1018** [comment]
@mastercrys 
Oh, the resize feature is currently being prepared for v3.15.0. Hold on a minute, please. :)
