### ISSUE TITLE
Click zoom out function, mouse icon can not change to zoom out icon.

### ISSUE THREAD

**Issue by coolman200** [nhn/tui.image-editor#608]
![image](https://user-images.githubusercontent.com/52725981/123746784-ae19c680-d8e4-11eb-99a2-241945cfb405.png)

Excuse me , when I using zoom in/out function, zoom in function is working, but when I want to use zoom out,
mouse icon can not change to zoom out icon then I have to click zoom out icon continuously then it's working(can not use mouse to zoom out).

Any one help?
Thanks.

**Comment by lja1018** [comment]
@coolman200 
Thank you for the report.
`Zoom-Out` is designed to return to the previous zoom level when clicked.
