### ISSUE TITLE
Include with NPM

### ISSUE THREAD

**Issue by o1webdawg** [nhn/tui.image-editor#61]
## Version

v3.02

## Development Environment

Firefox, Windows 10

## Current Behavior

_fabric2.default.util is undefined

```js
// Write example code
```

## Expected Behavior

I expected to include with NPM, copy the sample code, and it would work. However, I keep getting this fabric error. I've tried to include fabric with NPM and I've tried manually adding all the dependencies, but it doesn't work.  Can you add an example project created with NPM.  I have my doubts the NPM package works with the latest version.

**Comment by kidonchu** [comment]
I'm getting this same error. Looks like it's accessing fabric util functions in a wrong way when it's supposed to be `_fabric2.default.fabric.util.XXX`

**Comment by jinwoo-kim-nhn** [comment]
Please check dependency.
- https://github.com/nhnent/tui.image-editor#-dependency

It is helpful to refer to the example page.
- http://nhnent.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect.html
- https://github.com/nhnent/tui.image-editor/blob/master/examples/example02-useApiDirect.html

**Comment by cgrafton** [comment]
I am having the same issue as @kidonchu , after following the example page as well.

The fabric dependency with the tui-image-editor library is installed upon npm install: http://screen.ac/2391be3689ce

I also installed fabric standalone in the application and it is available on page load, so it is looking like `__webpack_require__(105);` is not defined: http://screen.ac/e7416df35904. is the problem but I am unsure of how to proceed. 

Please let me know if any additional information can be helpful.

**Comment by junghwan-park** [comment]
@cgrafton 
Are you load `fabric.js` pirior to `image-editor.js` loaded?

You should load fabric independently [like this](https://github.com/nhnent/tui.image-editor/blob/master/examples/example02-useApiDirect.html#L225) on examples page.
