### ISSUE TITLE
Image URL is not loading

### ISSUE THREAD

**Issue by GoutamSamal9** [nhn/tui.image-editor#610]
Uncaught (in promise) Invalid image loaded.
Error loading https://lecturenotes.in/uploads/upload/5c62/5c62cf/5c62cf157c1dcc0306373cc9/cjs1tu6v807l00pqumn11jbvj.jpg

**Comment by lja1018** [comment]
@GoutamSamal9 
I can't figure it out because there's no picture. Could you please open the issue again?

**Comment by GoutamSamal9** [comment]
When I use that package I faced "Uncaught (in promise) Invalid image loaded." but other images were working properly except this  https://lecturenotes.in/uploads/upload/5c62/5c62cf/5c62cf157c1dcc0306373cc9/cjs1tu6v807l00pqumn11jbvj.jpg

**Comment by lja1018** [comment]
@GoutamSamal9 
The image link is broken and does not appear... Can you give me another image link?

**Comment by awaisjavaid930** [comment]
https://www.admin.qslearning.co.uk/public/storage/work/fEqvftAZYXF5tm1DYnJNYvvYQjXR8R3FmpYGJkgE.jpg
i have same issue and i am unable to fix please help if someone can
