### ISSUE TITLE
React error message:You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

### ISSUE THREAD

**Issue by coolman200** [nhn/tui.image-editor#611]
![image](https://user-images.githubusercontent.com/52725981/123941390-b0575000-d9cc-11eb-916b-c37c40bd8966.png)

Can anyone explane what's the error message?

Thanks.

**Comment by lja1018** [comment]
@coolman200 
Thank you for your question.
I don't know the exact cause, but I think I need to use `babel-loader` to transpile the file.
