### ISSUE TITLE
Can i change text color only with selection text?

### ISSUE THREAD

**Issue by a9261020** [nhn/tui.image-editor#614]
For example, 
The Text is "Double Click" and default color is #ffa.
Then I Double click and select "Double" then change color.
It will change this object "Double Click" to another color.
But i just want change "Double" that i selected.

Is it possible to do that for now?

**Version**
3.14.2

**Comment by lja1018** [comment]
@a9261020 
Thank you for your question.
The only way to change a text object's text color is to change all of its text color.
To replace only some text, you must divide the text object.
