### ISSUE TITLE
How to change the brightness through api method.

### ISSUE THREAD

**Issue by yugo-ibuki** [nhn/tui.image-editor#616]
Hi, I have a question about `index.d.ts`.
I tried to change the brightness for the image through `applyFilter()` method
like as bellow:
```
imageEditor.applyFilter('brightness', {'brightness': parseInt(value, 10) / 255})
```
but ts compiler says
`TS2345: Argument of type '{ brightness: number; }' is not assignable to parameter of type '{ maskObjId: number; }'.`

I just commented out `maskObjId: number;` in index.d.ts, then it works fine.
I know it's not good idea in the way.

so, my question is
Is there any way to change the brightness other than commenting out the object content?

Thanks in advance.

**Comment by lja1018** [comment]
@yugo-ibuki 
Sorry for the late reply.
The `index.d` file seems to be missing a type.
I'll fix it.
