### ISSUE TITLE
How to add custom menus and submenus

### ISSUE THREAD

**Issue by vijaykuamrparelli** [nhn/tui.image-editor#618]
![git](https://user-images.githubusercontent.com/50367043/128980096-69a9848f-e603-45bc-a614-a7e9eb324d58.PNG)
how can I add more menus and submenus into list.

**Comment by vijaykuamrparelli** [comment]
Please let me now the answer

**Comment by vijaykuamrparelli** [comment]
any update on this

**Comment by vpsidar** [comment]
To achieve this you need to implement it manually. You can see the [examples](https://github.com/nhn/tui.image-editor/tree/master/apps/image-editor/examples) there are files named example02-useApiDirect.html and example03-mobile.html in these files you can get the idea.
