### ISSUE TITLE
Copy and paste of Items on canvas not working

### ISSUE THREAD

**Issue by dharampandya** [nhn/tui.image-editor#63]
## Version
3.2.0

## Development Environment

 Windows 8 and chrome
## Current Behavior
In windows 8 and chrome if I try to Copy and paste of Items on canvas it's not working that is if I want to copy same text on an image multiple time I have to write every time

```js
// Write example code
```

## Expected Behavior
Please give copy paste option and also  Add some font families in text menu as requested in #62

**Comment by jinwoo-kim-nhn** [comment]
@dharampandya 
I will give priority to improvement of the part that you pointed out. thank you
