### ISSUE TITLE
Eraser tool status

### ISSUE THREAD

**Issue by lsukharn** [nhn/tui.image-editor#635]
Could you please tell me what's the status of the following issue:
https://github.com/nhn/tui.image-editor/issues/550
(it mentions eraser tool which I need)

Maybe eraser was already developed? I couldn't find it anywhere though.
Are you working on the eraser tool? Maybe you have some dev code I can include in my project. It's ok if it's not stable, I can fine-tune the code later.

Thanks!

**Comment by adeptflax** [comment]
It has not been implemented yet. I built the main branch. It is not there.
