### ISSUE TITLE
Losing aspect ratio on mobile view

### ISSUE THREAD

**Issue by Crwd** [nhn/tui.image-editor#641]
**Summary**
Hello guys. I started implementing on my mobile app based on angular the image editor.
I fixed most of the design and import issues. But im still hanging on the image preview area.
The editor is resizing and squashing the image if the keyboard is open for example or the 
width and height is not suitable for the device seizure. 

Do you have any suggestions on what options or what css styles i could apply to fix that behaviour?
You can see the issues on the screenshots.

**Screenshots**
![0E6E2B0D-2020-4979-96BA-3F8EF2EB1054](https://user-images.githubusercontent.com/16522648/132984730-e12803a8-b53d-43cb-a8a0-11da70837be3.png)

![95413C50-1203-4FAE-8096-FE6890B28627](https://user-images.githubusercontent.com/16522648/132984740-ba0c46e3-48fe-4631-955e-39257fa06098.png)

![C81C6EE1-73A1-450F-8BBD-972C2E4B47EB](https://user-images.githubusercontent.com/16522648/132984746-acbb28ad-fb4a-4c27-92d7-a4914145c31a.png)

**Version**
Newest

**Comment by lja1018** [comment]
@Crwd 
Thank you for the question.
I have to look for more details, but maybe I can solve it `min-height`.
Maybe it's because the keyboard changed the size of the viewport.

**Comment by Crwd** [comment]
@lja1018 Thank you very much this was as easy as helpful. Worked fine, the keyboard is no longer
squashing the editor container. But still im trying to figure out how to prevent losing the aspect ratio on some pictures that dont fit in the container. Some images with different dimension look quite wierd inside the editor..

**Comment by lja1018** [comment]
@Crwd 
Since mobile usability is not considered, `image-editor` cannot expect full feature support on mobile.
