### ISSUE TITLE
 Rotate the small dot of the font, how to modify the cursor

### ISSUE THREAD

**Issue by abigcivet** [nhn/tui.image-editor#647]
hello, Excuse me Rotate the small dot of the font, how to modify the cursor

**Comment by lja1018** [comment]
@abigcivet 
I don't understand the question.
Can you explain it in detail?

**Comment by abigcivet** [comment]
http://r084mbb2y.bkt.clouddn.com/456.png
I can’t upload pictures in my area, I used a CDN to store the pictures。As shown in the figure, when the mouse passes over the arrow position element, the cursor is crosshair。As shown in the figure, when the mouse passes over the arrow position element, the cursor is crosshair。How to modify? Please help me！Thank you very much！

**Comment by abigcivet** [comment]
The default cursor of the current project is crosshair，I want to change to other cursor styles，for example: 'move', 'wait' or Or use url('')

**Comment by lja1018** [comment]
@abigcivet 
If you want to change the cursor when hover, you can use the following code.
```
object.set({ hoverCursor: 'cursor type' });
```
