### ISSUE TITLE
Whether the default value of double-click to add text can be modified

### ISSUE THREAD

**Issue by abigcivet** [nhn/tui.image-editor#660]
http://r084mbb2y.bkt.clouddn.com/jj.png
GitHub Failed to upload attachment，I use CDN to display pictures，
as the picture shows，Whether the default value of double-click to add text can be modified，The default value is Double Click

**Comment by lja1018** [comment]
@abigcivet 
Thank you for asking.
Currently, there is no way to modify the basic action of adding text.
