### ISSUE TITLE
Using tui editor for image manipulation preview but work on server side instead of canvas?

### ISSUE THREAD

**Issue by aloksharma1** [nhn/tui.image-editor#669]
Hello,

I am working on a server side connector project for image manipulation where i want to use tui editor as front facing but instead of using functionality of canvas & saving image from there, i want to send image co-ordinates & specific commands like crop, filter, blur etc to server side to work on image & and render the copy server side. reason of doing so is simple, i want to preserve original image quality as much as possible.
Please let me know what is possible and what is not, also if i have to change things which documentations and files i should start with.
currently i am working on image manipulation with Skiasharp and thinking of moving with Imagsharp with this project.
regards

**Comment by aloksharma1** [comment]
@lja1018 any suggestions on how this is possible?

**Comment by lja1018** [comment]
@aloksharma1 
I think you should make an API that wraps the API of the `image-editor` yourself.
