### ISSUE TITLE
Source Code for Examples?

### ISSUE THREAD

**Issue by bpasham** [nhn/tui.image-editor#675]
Thanks for this amazing component. somehow the source code for examples published on GitHub docs is not accessible. 
http://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect
Can you suggest the new location of the examples please?
Thanks..

**Comment by PuneetGopinath** [comment]
It's here: https://github.com/nhn/tui.image-editor/blob/gh-pages/3.9.0/examples/example02-useApiDirect.html

_FYI: I am not a contributor/maintainer for this repository, I just came searching for a image editor package and I found this, I also wanted the source code of the examples, and I saw this issue, so I shared the link_

**Comment by lja1018** [comment]
@bpasham 
The link that @PuneetGopinath posted is correct!
The latest example code is https://github.com/nhn/tui.image-editor/blob/master/apps/image-editor/examples/example02-useApiDirect.html.

**Comment by bpasham** [comment]
Thank you both. @lja1018 and @PuneetGopinath
