### ISSUE TITLE
Lighter custom builds

### ISSUE THREAD

**Issue by CodeWithOz** [nhn/tui.image-editor#676]
**Summary**
What would be a good way to get a custom build of the library that only contains features I want to use? For instance out of all the integration functions, I only want to start with Text, Icon, Draw and Crop. Is there a way to neatly exclude them from a custom build without changing much code?

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
3.15.2

**Additional context**
I plan on using this in a cordova hybrid app that doesn't use js frameworks, so I want to only get the functionality I need.

**Comment by lja1018** [comment]
@CodeWithOz 
Thank you for the question.
Are you talking about [tree shaking](https://webpack.js.org/guides/tree-shaking/)?
This is a feature that the image-editor does not support yet.
