### ISSUE TITLE
How to add custom function buttons, such as Mosaic function

### ISSUE THREAD

**Issue by malinxiaM** [nhn/tui.image-editor#685]
**Summary**
A clear and concise description of what the question is.

**Screenshots**
If applicable, add screenshots to help explain your question.

**Version**
Write the version of the imageEditor you are currently using.

**Additional context**

**Comment by lja1018** [comment]
@malinxiaM 
The feature of adding custom features is not yet in the `image-editor`.
I'll consider it.
