### ISSUE TITLE
How do I get object IDs?

### ISSUE THREAD

**Issue by ZuupahGeek** [nhn/tui.image-editor#686]
**Summary**
I am trying to learn about this program, and make a few changes for this project I'm working on at school. Right now, I'm trying to change the font on the text tool. I know the API tells me how to manually change things like Font-family and such, but I really can't wrap my head around how to actually do it! Where do i get the correct ID for changeTextStyle(id)? I'm guessing it has something to do with the activeObjectId or something, but I don't know how to find it!

**Version**
react image editor 3.15.2

**Additional context**
I'm working in React

**Comment by lja1018** [comment]
@ZuupahGeek 
Thank you for the question.
If you use the `addText` API, you must save the id in the returned Promise.

**Comment by ZuupahGeek** [comment]
> 

Oh, I get it now! Thank you for the response!
A follow-up question, if I may! The way I call the addText, I have to make my own instance on a button, for example! Is there a way I can "adjust" the original addText, that is in the node modules, rather than making another one?

**Comment by lja1018** [comment]
@ZuupahGeek 
React requires access to the instance and use the API.
I think you can bring an instance to the `getInstance` API and use it.
