### ISSUE TITLE
Saving file with `toDataUrl` makes the canvas skew the image.

### ISSUE THREAD

**Issue by humblecoder** [nhn/tui.image-editor#69]
**Version**
3.2.0

**Development Environment**
MacOS 10.12.6
Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Current Behavior**
Saving the file with `toDataUrl` results in the image being [skewed](https://app.box.com/s/t0s2i00q9igwen4minv75dumj3db5ex0) on screen.  The data does still appear to save correctly though.

**Comment by OculusMode** [comment]
Same happens with me :'(

**Comment by jinwoo-kim-nhn** [comment]
It is not currently reappearance, so close it.
