### ISSUE TITLE
Image resize presets

### ISSUE THREAD

**Issue by iTzMeRafa** [nhn/tui.image-editor#690]
Hey,

is there a way to define size presets for the image?
As for now you are able to set the width and height of an image individually + keep aspect ratio.

I would need something like this:
![image](https://user-images.githubusercontent.com/36051055/146976451-ad5f7498-703f-4c2b-8665-64874ed01a07.png)

Which, onClick, sets the width and height as defined.

**Comment by lja1018** [comment]
@iTzMeRafa 
There is no feature to provide a resize preset yet. I'll consider it.
