### ISSUE TITLE
In `selectionStyle`, what is cornerStyle candidate?

### ISSUE THREAD

**Issue by eomttt** [nhn/tui.image-editor#694]
**Summary**
            selectionStyle: {
              cornerStyle: 'circle',
              cornerSize: 18,
              cornerColor: '#fff',
              cornerStrokeColor: '#fff',
              transparentCorners: false,
              lineWidth: 2,
              borderColor: '#fff',
            },

what is `cornerStyle` candidate?
circle ? triangle? rectangle?? and has another?

**Comment by lja1018** [comment]
@eomttt 
The `cornerStyle` options can be 'rect' or 'circle'.
