### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by MUSTAQ1995** [nhn/tui.image-editor#697]
can anyone please help me with the download button, am not able to use the file-server  to download, the file, but the download of the file is working normal in the api example of documents, but when we install and run its taking us to the new blank page with the edited image, so can i need to download on click button.

**Comment by MUSTAQ1995** [comment]
small correction in question,file-saver it is  not file-server.

**Comment by lja1018** [comment]
@MUSTAQ1995 
Can you upload the example code?
