### ISSUE TITLE
How to maintain canvas image size using crop, redo and undo function?

### ISSUE THREAD

**Issue by ChiYoungKim-CYK** [nhn/tui.image-editor#705]
Hello.

I wanted to maintain image size when it load. so I used imageEditor.loadImageFromFile and then called imageEditor._grahics.resize(dimensions).

However, when i used these three functions, canvas size was changed.

* image size : 6600 * 2283, I wanted to maintain 1280 * 720.
1. Crop
 - After called, width & height attribute, max-width & max-height style was changed.
2. Undo & Redo
 - and then using undo & redo, it changed original image size.

**Comment by lja1018** [comment]
@ChiYoungKim-CYK 
Cropping or resizing changes the size of the image.
If you need the size before the change, save it before the change.
