### ISSUE TITLE
Hide menu from toolbar.

### ISSUE THREAD

**Issue by kirti18patel** [nhn/tui.image-editor#708]
Hello, 
I am using ` "@toast-ui/react-image-editor": "^3.15.2"`

Is there any way to hide menu (like delete, deleteAll and Load) from toolbar? Because I am using url of an image and when clicking on delete or deleteAll, it is throwing a runtime error. I am attaching screenshot of this error. 

I actually want to hide these three, if there is possible way please share. Thanks.
![Screenshot 2022-02-10 010831](https://user-images.githubusercontent.com/74840827/153348458-a96a0e1d-dce5-4665-bb1a-8161a86d8d9a.png)

**Comment by lja1018** [comment]
@kirti18patel 
Thank you for the question.
There is no way to hide menus(delete, delete all, etc.) other than editing menus such as crop.
I will consider the feature of hiding the menu.

**Comment by kirti18patel** [comment]
So how to resolve that error I am getting when click on delete?

**Comment by kirti18patel** [comment]
Also, with adding text functionality, it is not allowing to change text of “Double Click” when click on it. It means adding text is not working as expected. Please share how resolve it.

**Comment by lja1018** [comment]
@kirti18patel 
Can you tell me how to reproduce it in detail?
