### ISSUE TITLE
How do you get the text added on the toast ui image editor? 

### ISSUE THREAD

**Issue by djparulan** [nhn/tui.image-editor#712]
**Summary**
I would like to save on the database the text I added on the toast ui image editor, and I am lost on how to get the text added on the canvas. I can't seem to find the text I added on the toast ui image editor on the console.log using 

  const canvas = useRef(null);
  canvas.current.getInstance();
  console.log('canvas: ', canvas.current.getInstance());

I even tried the onAddText and it only showed the originPosition and clientPosition.

**Screenshots**
![image](https://user-images.githubusercontent.com/31680853/153610410-0a600e95-a542-436c-ba7a-90d8189df5c3.png)

**Version**
"^3.15.2"

**Comment by lja1018** [comment]
@djparulan 
Thank you for the question.
There is no API that reads text directly. But try the following method.
1. Save the id of the added text object.
2. `imageEditor._graphics.getObject(id);`
