### ISSUE TITLE
how to change the "Double Click" value

### ISSUE THREAD

**Issue by GugaAraujo** [nhn/tui.image-editor#715]
I'm trying to customize the text editor by changing the "Double Click" value to some other string.
How could I modify this string?

I'm using Vue in my project.

**Comment by lja1018** [comment]
@GugaAraujo 
Thank you for the question.
There is no way to change the default text of the text object. I'll add it to the next task.

**Comment by GugaAraujo** [comment]
Thanks for your answer. It will be great to have this functionality.
I'll wait for good news :)
