### ISSUE TITLE
Why are you tracking user behavior via GA?

### ISSUE THREAD

**Issue by SvenAlHamad** [nhn/tui.image-editor#73]
Hi, 

your library seems to be tracking the user interactions and posting them to your Google Analytics account. Why is that? This behavior is not mentioned in your docs. How can it be turned off? Such a behavior is strictly forbidden and lawful by GDPR and similar user privacy protection laws. 

**Please point out to others that this is the case as people can have serious legal issues by using this library!**

Here is a screenshot of the request being made by your library to google analytics:

![image](https://user-images.githubusercontent.com/3808420/47041956-f834db00-d181-11e8-918b-915872211cc2.png)

**Comment by dhduc** [comment]
You can add `usageStatistics: false` param to the image editor arguments when you initialize it.
If this way not working, try to find all 'usageStatistics' params on `tui-image-editor.js` file and make sure all 
of them false.

**Comment by SvenAlHamad** [comment]
Thanks @dhduc, later I did find the option parameter to turn off the tracking. But the main point is that these things need to be pointed out because it can cause a serious breach of users' privacy. Or at least the toggle needs to be set to `false` by default.

**Comment by dhduc** [comment]
I don't realize this issue until you reported it, thank for that @SvenAlHamad.
Also, I think the team should be turned off the statistic option as the default for respecting the users' privacy.
