### ISSUE TITLE
add mobile version 

### ISSUE THREAD

**Issue by OlegIv-m** [nhn/tui.image-editor#732]
Good day to everyone! I have question concerning mobile version of tuiIE. I've tryed this article  _https://github.com/nhn/tui.image-editor/blob/master/docs/Apply-Mobile-Version.md_ but_ with no any help. Can you tell me exuct steps to make mobile version working?
i use:

- vue 2 SPA
- @toast-ui/vue-image-editor": "^3.15.2
Thanks.

**Comment by lja1018** [comment]
@OlegIv-m 
The Mobile version is not provided separately. It should be implemented directly using API.
