### ISSUE TITLE
The color value is selected for many times, and the performance is not good

### ISSUE THREAD

**Issue by Edric-Li** [nhn/tui.image-editor#740]
1.Click draw menu then click set color button.

2.Select all color text，then click color button to close color panel.

3.Click the set color button again,select all color text again.(NG)

![imageeditor5](https://user-images.githubusercontent.com/50992790/158730793-cb2d30d9-86aa-45d1-bc2b-2b90581175ba.gif)

**Comment by lja1018** [comment]
@Edric-Li 
The bug is not reproduced. What kind of bug is it exactly?

**Comment by Edric-Li** [comment]
@lja1018 
Sorry, this is not a bug. I'm in my project, added the drag and drop upload feature.
The problem is caused by forgetting to deal with it.
I will close the issues.

**Comment by lja1018** [comment]
@Edric-Li 
Thank you!
