### ISSUE TITLE
get draw object/layer

### ISSUE THREAD

**Issue by scratcher28** [nhn/tui.image-editor#744]
How to separately export a draw object/layer as PNG / blob / DataURI preserving canvas size of image?
![image](https://user-images.githubusercontent.com/778716/160150312-b87e418f-4990-45d7-9255-62885462454c.png)

**Comment by lja1018** [comment]
@scratcher28 
Would you like to try to use `toDataURL`?
Please refer to [this section](https://nhn.github.io/tui.image-editor/latest/ImageEditor#toDataURL).

**Comment by scratcher28** [comment]
Yes, I use toDataURL to export the whole/final image. But since I use drawing tool to paint a mask, I want the drawing layer exported separately (2 pngs).

**Comment by lja1018** [comment]
@scratcher28 
There is no feature to export by layer. Only one image can be exported
