### ISSUE TITLE
How to run tests on this project?

### ISSUE THREAD

**Issue by Mouradif** [nhn/tui.image-editor#747]
In many projects I saw, there's a npm `"test"` script that lets you just run `yarn test` or `npm run test` and it should work out of the box.

In this project, I saw that `jest` was a dependency so I assumed I'd run `npx jest` but all the tests fail because imports with the `@/` prefix are not resolved. What's the correct way to run tests?

Also consider adding the answer to this question to the README.md

**Comment by lja1018** [comment]
@Mouradif 
Have you run `npm run test` on `apps/image-editor`?

**Comment by Mouradif** [comment]
I have now, thanks.

**Comment by Mouradif** [comment]
@lja1018 has this been fixed?

**Comment by lja1018** [comment]
@Mouradif 
I don't know what the problem is because the test runs without any problems.

**Comment by Mouradif** [comment]
There is no problem, I just didn't know I had to go to `apps/image-editor` before running tests, this instruction was nowhere else. But like I said, I know now. I don't have much time to work on this as you may expect but I figured the issue would remain open until I or someone else fixes it, no?

**Comment by Mouradif** [comment]
Sorry, I actually realize that my message "I have now, thanks." is incomplete. I originally added that this should be in the `CONTRIBUTING.md` file where it says to run `npm run test` because one would assume this command should run on the root folder, unless I'm missing something

**Comment by lja1018** [comment]
@Mouradif 
I understand. I think it's reasonable.
