### ISSUE TITLE
Is it impossible to include the Canvas via Direct API instead of includeUI parameter ? (React)

### ISSUE THREAD

**Issue by LotharieSlayer** [nhn/tui.image-editor#755]
**Summary**
Hi,

I'm currently redoing your entire API in React components, but I have a problem.

I'm looking how to integrate the canvas of the image I want to edit via the Direct API in React. (As example 2 of the documentation : https://nhn.github.io/tui.image-editor/latest/tutorial-example02-useApiDirect)
loadImageFromUrl() doesn't seem to work without the includeUI parameter, and even though I've setup the max canvas size.

How can I natively integrate your API into my website?

**Additional context**
For the moment my only solution has been to hide the CSS of the UI but certain usability bugs come up frequently with Crop (where cropzone is null), Shape (which I cannot validate with mouseUp), or Text. (like the codesandbox link from #627) 

Result with includeUI with hidden css : 
![image](https://user-images.githubusercontent.com/49253492/163187600-fcaf1ef8-278a-4760-a484-d87514234817.png)
![image](https://user-images.githubusercontent.com/49253492/163187465-064609ea-dea7-4c9e-91d2-a6712bb4e087.png)

What I would like to do :
![image](https://user-images.githubusercontent.com/49253492/163186493-ea01bc2a-e86c-4fc6-95d6-ecc623200622.png)
![image](https://user-images.githubusercontent.com/49253492/163186680-8363f5ba-aaef-4db0-ad01-664f1c955bc0.png)
 :sob:  :sob:  :sob:  Result : 
First render when mounted
![Capture d’écran_2022-04-14_11-40-12](https://user-images.githubusercontent.com/49253492/163358878-ce487bdf-e716-4b72-a5ef-23e8fb8d0f26.png)
Re-render (no more canvas if I try to re-loadImageFromURL())
![image](https://user-images.githubusercontent.com/49253492/163186949-2bb242a2-d325-43bf-a7b3-6c4efde45cb0.png)

**Version**
TUI Image Editor : v3.15.2
React : v16.13.1

**Comment by LotharieSlayer** [comment]
It looks like issue #624.

**Comment by LotharieSlayer** [comment]
Update:
You can bypass functions that doesn't work (shape and text) by remove the empty menu parameter array of includeUI in my first screenshot, (so it's displaying all the submenus) and then hide the css again with a simple display:"none". By adding and hide all the submenus, there is no more errors and the instance believe that he has open the menu.
(update about crop function : it is only working if your last action was adding a text object, I still don't know the reason...)

If you want to try : 

**UI to set**
```js
// fileLink = URL of your Image
// fileName = The name of the image imported
const props = (fileLink, fileName) => ({
    // INCLUDE UI
    includeUI: {
        loadImage: {
            path: fileLink,
            name: fileName
        },
        initMenu: "",
        uiSize: {
            width: "1908px",
            height: "1000px"
        }
    },
    cssMaxWidth: 1908,
    cssMaxHeight: 1000,

});
```

**CSS trick**
```js
const classes = {
    editor: {
        "& .tui-image-editor-container": {
            overflow: "hidden"
        },
        // Enlever l'help menu pour accéder à "l'historique"
        "& .tui-image-editor-header, .tui-image-editor-help-menu, .tui-image-editor-controls, .tui-image-editor-submenu": {
            display: "none"
        },
        "& .tui-image-editor-main-container": {
            backgroundColor: "transparent !important"
        }
    }
};
```
**Component return**
```js
<div css={classes.editor}>
 <ImageEditor ref={editorRef} {...props(fileLink, fileName)} />
 {/* blablabla */}
</div>
```

**Result**
![image](https://user-images.githubusercontent.com/49253492/163541134-c722d223-7f3b-4e52-8574-51b068238a80.png)

**Comment by lja1018** [comment]
@LotharieSlayer 
It seems to be a problem when using `loadImageFromURL` directly in React. Let me check.
