### ISSUE TITLE
How to prevent object from being deleted?

### ISSUE THREAD

**Issue by celalnuriakgun** [nhn/tui.image-editor#757]
**Summary**
How to prevent object from being deleted? I want to block it when it is wanted to be deleted from the editor.

In the examples made by users on the Fabric.JS website or on sites such as stackoverflow.com, when I press the "delete" or "backspace" key on the keyboard, it is not deleted, so I want to do something like this.

**Version**
3.15.2

**Comment by lja1018** [comment]
@celalnuriakgun 
I don't understand. Can you explain it in more detail?
