### ISSUE TITLE
I want to customize the ratio crop, such as 16:10 or 2:1

### ISSUE THREAD

**Issue by baobeiqie** [nhn/tui.image-editor#761]
**Summary**
I want to customize the ratio crop, such as 16:10 or 2:1, how to do it. thanks

**Version**
3.15.2

**Comment by Elli-Jeon** [comment]
add `imageEditor.setCropRatio` before `imageEditor.crop(imageEditor.getCropRatio)` [this line](https://github.com/nhn/tui.image-editor/blob/44cec555b177ee6e9807c376dff5a054b4fe9f95/apps/image-editor/examples/js/service-basic.js#L403)

[reference] (http://nhn.github.io/tui.image-editor/latest/ImageEditor#setCropzoneRect)

**Comment by baobeiqie** [comment]
sorry i didn't understand imageEditor.crop(imageEditor.getCropRatio)，
I mean, how about adding a 16:10 here。
![image](https://user-images.githubusercontent.com/29722067/164612039-fdeb4e69-3454-4144-b6af-b922ae1a9c7c.png)

**Comment by baobeiqie** [comment]
I'm so sorry, I didn't understand.can you help me。

1. I mean, how about adding a 16:10 here。
![image](https://user-images.githubusercontent.com/29722067/165068322-9eb1cbb2-526e-4128-bb56-4b43ee6d7861.png)
2.I modified the code at line 379 of this link【https://github.com/nhn/tui.image-editor/blob/44cec555b177ee6e9807c376dff5a054b4fe9f95/apps/image-editor/examples/js/service-basic.js#L403】，
Here is my code, but there is a problem.

$btnCrop.on('click', function () {
  imageEditor.startDrawingMode('CROPPER');
  $displayingSubMenu.hide();
  $displayingSubMenu = $cropSubMenu.show();
  imageEditor.setCropRatio(1.25);
});

**Comment by Elli-Jeon** [comment]
@[baobeiqie](https://github.com/baobeiqie)

Good day. 

There are three crop buttons in service basic.js file. 

[btnCrop.on](https://github.com/nhn/tui.image-editor/blob/44cec555b177ee6e9807c376dff5a054b4fe9f95/apps/image-editor/examples/js/service-basic.js#L379), [btnCropApply](https://github.com/nhn/tui.image-editor/blob/44cec555b177ee6e9807c376dff5a054b4fe9f95/apps/image-editor/examples/js/service-basic.js#L402) lastly,  [btnCropCancel](https://github.com/nhn/tui.image-editor/blob/44cec555b177ee6e9807c376dff5a054b4fe9f95/apps/image-editor/examples/js/service-basic.js#L409)


if u click $btnCrop, then `cropper` drawingmode starts, and submenu wii appear. 

```
$btnCrop.on('click', function () {
  imageEditor.startDrawingMode('CROPPER');
  $displayingSubMenu.hide();
  $displayingSubMenu = $cropSubMenu.show();
});
```

after putting 16:10 button in submenu. Add event listner.

``` 
$16:10Btn.on('click', () => {
  imageEditor.setCropzoneRect(16/10); 
})
```

and then click btnCropApply to end the cropper drawing mode.

Hope this will help u.

**Comment by baobeiqie** [comment]
OK, thank you very much. I understand.
