### ISSUE TITLE
How to use applyFilter remove white with control distance

### ISSUE THREAD

**Issue by NarutSH** [nhn/tui.image-editor#766]
![image](https://user-images.githubusercontent.com/49747102/165296149-c92ae0ff-531f-4a94-8e84-3088bf119250.png)

How to use **applyFilter** function by call **remove white** with control **distance**

I already check on document but no remove white sample there 
![image](https://user-images.githubusercontent.com/49747102/165296697-6c665854-4e38-4819-aa2a-67993c34a168.png)

**Comment by lja1018** [comment]
@NarutSH 
How about using it like this?
```js
imageEditor.applyFilter('removeColor', { distance: 0.2 });
```

**Comment by NarutSH** [comment]
> @NarutSH How about using it like this?
> 
> ```js
> imageEditor.applyFilter('removeColor', { distance: 0.2 });
> ```

@lja1018 
IT WORKS, MANY THANKS.
