### ISSUE TITLE
[TypeScript] iterationCount argument missing in redo/undo

### ISSUE THREAD

**Issue by LeakAGeek** [nhn/tui.image-editor#795]
**Describe the bug**

**Type in index.d.ts:**
public redo(): Promise<any>;
public undo(): Promise<any>;

**Should be:** 
public redo(iterationCount: number): Promise<any>;
public undo(iterationCount: number): Promise<any>;

**API:**
![image](https://user-images.githubusercontent.com/54979276/183095737-703bb66f-593f-49ef-bde5-63cc52b5ed5b.png)
![image](https://user-images.githubusercontent.com/54979276/183094864-5e9a57b5-a84f-4d86-8d2b-2c8372989ee5.png)

**Comment by lja1018** [comment]
@LeakAGeek 
Thank you for the missing type report. PR will be reviewed soon.
