### ISSUE TITLE
Image Metadata is lost after download modify image 

### ISSUE THREAD

**Issue by lambamahesh** [nhn/tui.image-editor#805]
@version 3.15.3

## Development Environment
Core JavaScript

#Initialize Code

var imageEditor = new tui.ImageEditor('#tui-image-editor-container', {
        includeUI: {
          loadImage: {
            path: "{{ $content }}", // base64 data
            name: "{{ $type[0] ?? time() }}", // dynamic comming from server
          },
          theme: blackTheme,
          menu: ['crop', 'flip', 'rotate', 'draw', 'shape', 'icon', 'text', 'filter'],
          menuBarPosition: 'bottom',
        },
        cssMaxWidth: 900,
        cssMaxHeight: 700,
        usageStatistics: false,
      });

**Comment by RKTZ** [comment]
Your image is loaded into a canvas who does not preserve any metadata. The color profile and metadata will be lost. Be careful if your source image is not sRGB, the colors you will get back won't be the same.

You could use a lib like sharp js to extract and maybe inject again metadata.

I suggest that you read this SO answer : [https://stackoverflow.com/questions/34027592/does-canvas-imagedata-in-javascript-contain-exif-info](url)

**Comment by lja1018** [comment]
@lambamahesh @RKTZ 
A good proposal. I agree with your proposal.
