### ISSUE TITLE
Adobe RGB converted to sRGB

### ISSUE THREAD

**Issue by RKTZ** [nhn/tui.image-editor#807]
## Version

3.15.2

Hello, I'm importing an image with a Adobe RGB profile but it gets converted to sRGB and I'm losing a lot of information once edited. Do you think it's possible to keep the adobe one ?

Thanks

Edit: After some investigating, it seems that canvas keep only raw pixel datas and get rid of the metadata and works only with sRGB which is the web standard.

A solution would be to extract the metadata beforehand and inject them back into the final image.

Any other suggestions ?

**Comment by lja1018** [comment]
@RKTZ 
That's a good suggestion. However, it seems to be the same proposal as #805. Close.
