### ISSUE TITLE
이미지 재 업로드 후 메뉴 이동 시 이 전 이미지 크기로 변경되는 오류

### ISSUE THREAD

**Issue by SM11187** [nhn/tui.image-editor#825]
안녕하세요 !
tui image-editor 디자인도 깔끔하고 잘 사용중에 있습니다.

테스트 과정에서 버그를 발견했는데 확인 부탁드리겠습니다.

1. 기본 튤립 사진 이미지에서 resize 메뉴로 이동
![image](https://user-images.githubusercontent.com/94828850/202100912-8a25b194-9092-413f-aab0-7d567c95cc13.png)
![image](https://user-images.githubusercontent.com/94828850/202101052-df01e80f-d498-455e-a280-ea2dbd39fab2.png)

2. 이동 후 다른 이미지 업로드 
![image](https://user-images.githubusercontent.com/94828850/202101214-53ae4412-245e-4f21-8159-608f47e0585e.png)

4. 다른 메뉴로 이동 시 이전 이미지인 튤립 사진 사이즈가 적용되어 이미지 깨짐 현상 발생
![image](https://user-images.githubusercontent.com/94828850/202101417-ed797a46-064b-4ef6-9020-4c7b628b038d.png)

저도 이 문제를 해결해야돼서 피드백 부탁드리겠습니다.
감사합니다

**Comment by lja1018** [comment]
@SM11187 
Thank you for your question.
It is a rule to post `image-editor` issues in English, so I would appreciate it if you could upload them again in English.
