### ISSUE TITLE
Introduced through CDN or node_ Modules introduced with error 'Cannot read properties of undefined (reading' create ')'

### ISSUE THREAD

**Issue by SZGG2333** [nhn/tui.image-editor#854]

**Comment by SZGG2333** [comment]
1

**Comment by felanny** [comment]
你怎么解决这个问题的？
How did you solve this problem?

**Comment by SeijuHND** [comment]
How did you solve this problem?

**Comment by SeijuHND** [comment]
> _No description provided._

How did you solve this problem?

**Comment by felanny** [comment]
> > _No description provided._
> 
> How did you solve this problem?

`<script async src="/cdn/tui-image-editor/3.15.3/tui-color-picker.js"></script>
<script async src="/cdn/tui-image-editor/3.15.3/tui-image-editor.min.js"></script>`
